### ISSUE TITLE
[CONTRIBUTION] How to Build on MacOS in 2023 edition (Intel)

### ISSUE THREAD

**Issue by datasith** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#1006]
Building this repo on MacOS (Ventura) on an Intel Mac in 2023 isn't for the faint of heart. Here is how.

Ensure you have the JDK and not just the JRE:
- https://www.oracle.com/java/technologies/downloads/#jdk20-mac

Install dependencies from Homebrew, not from this repo.
```bash
brew install pkg-config openssl cmake gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly log4cplus gst-libav
```

Need to tell `cmake` where OpenSSL lives:
```bash
export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig
```

Turn off dependencies, don't worry about JNI:
```bash
cmake .. -DBUILD_DEPENDENCIES=OFF -DBUILD_GSTREAMER_PLUGIN=ON
```

And finally:
```bash
make
```

**Comment by hassanctech** [comment]
We have these instructions in the README, here: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/README.md#configure

If you think something is unclear or missing, please submit a PR specifying exactly what step was extra and in what way it was broken?  I'm closing this Issue but you're welcome to submit a PR with a contribution with some detailed notes.

We do have to be careful here to note that the PKG_CONFIG_PATH needs to be set to where it was installed the location you specified is the default location for brew.
