### ISSUE TITLE
Not working with AXIS IP Camera

### ISSUE THREAD

**Issue by openedhardware** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#1010]
I tried to stream video from my IP camera to the AWS KVS, but got this error: https://pastebin.pl/view/132d32f3

Could you guys help me figure out why this doesn't work?

Seems 1280x960 resolution is not supported?

**Comment by niyatim23** [comment]
Hi @openedhardware, can you please attach the log file instead of this link as I can't access it?

**Comment by openedhardware** [comment]
Sure, here you go - 
[kvs_log.txt](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/files/11390002/kvs_log.txt)

Thank you!

**Comment by niyatim23** [comment]
Are we talking about the `Bus error`? The log seems to be cut midway. Can you please upload the complete logs? 
Thanks!

**Comment by openedhardware** [comment]
Yes, that is what I see as the last reply:
![image](https://user-images.githubusercontent.com/16890683/236018301-bac73657-946b-4410-8a40-791a66109726.png)

Thank you!

**Comment by sirknightj** [comment]
1280x960 is supported.
```
gst-inspect-1.0 kvssink
...
video/x-h264
          stream-format: avc
              alignment: au
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-h265
              alignment: au
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
```

Is #686 related?

**Comment by openedhardware** [comment]
I tried with `export DALIGNED_MEMORY_MODEL=TRUE`, but same result... :(

**Comment by sirknightj** [comment]
It's a cmake flag, so you need to pass it into cmake:

```bash
cmake .. -DALIGNED_MEMORY_MODEL=TRUE <other cmake flags>
```

Then run `make` again.

**Comment by sirknightj** [comment]
May be safest to delete the `build` folder and do a fresh build in case of cmake cache not taking the updated values.

**Comment by openedhardware** [comment]
That fixed, thank you!
