### ISSUE TITLE
rtsp url of Sricam SP012 as the camera media source

### ISSUE THREAD

**Issue by anmol1ratn** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#104]
I have Sricam SP012 IP camera which I want to use as the media source. I'm using Ubuntu 18.04.
But I don't know how to find rtsp url of the camera. It's one of the tried setup as mentioned in Kinesis-Video Developer Guide. Can you help me with this?
@chehefen 
@MushMal

**Comment by chehefen** [comment]
can you try rtsp://admin:password@ip/onvif1 ? If that does not work. Can you try the urls listed here? https://www.ispyconnect.com/man.aspx?n=Sricam

**Comment by anmol1ratn** [comment]
@chehefen 
Sorry for replying late. I tried the rtsp url which you mentioned and I got the following error.

```
[DEBUG][2018-07-29 15:37:41] Kinesis Video stream VideoStream is Ready.
[DEBUG][2018-07-29 15:37:41] Stream is ready
[DEBUG][2018-07-29 15:37:41] Pipeline OK
[DEBUG][2018-07-29 15:37:41] rtsp://admin:888888@ip/onvif1
[DEBUG][2018-07-29 15:37:41] appsink configured
[DEBUG][2018-07-29 15:37:41] Pipeline built, elements *NOT* yet linked
[DEBUG][2018-07-29 15:37:41] Pipeline playing
Error received from element source: Could not open resource for reading and writing.
Debugging information: gstrtspsrc.c(6775): gst_rtspsrc_retrieve_sdp (): /GstPipeline:rtsp-kinesis-pipeline/GstRTSPSrc:source:
Failed to connect. (Generic error)
[INFO ][2018-07-29 15:37:41] 
freeKinesisVideoClient(): Freeing Kinesis Video Client
```

Do I also have to configure the camera in any way? Is there any guide to achieve this? Coz it's one of the tried setups as mentioned in dev guide.

**Comment by chehefen** [comment]
do you know what the ip address of your camera is? For example, if the ip address is 192.168.0.1, then the rtsp url could be rtsp://admin:password@192.168.0.1/onvif1.

**Comment by anmol1ratn** [comment]
Okay, I got it working. Thanks for the help. :)
