### ISSUE TITLE
[QUESTION] Gstreamer pipeline

### ISSUE THREAD

**Issue by tsuna6** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#1042]
Hi, i just tried to put this string in gstreamer pipeline. 

`gst-launch-1.0 rtspsrc location="rtsp://admin:*****@IPAddress:554" latency=10 ! rtph264depay ! h264parse ! decodebin ! autovideosink`

i'm using hikvision camera, but it wont displayed in gstreamer.
but when i'm trying with this code in cmd, and it works

please advice me about this.

Thanks

**Comment by sirknightj** [comment]
If the error is a pipeline linking error, please try adding `videoconvert` between `decodebin` and `autovideosink` elements. We need some logs (to know what error you are running into) to assist further.

Note that is a general GStreamer question that doesn't involve the GStreamer `kvssink` element. We would recommend reaching out on the GStreamer forums for additional assistance with `autovideosink`.
