### ISSUE TITLE
[LinuxOS] "Kvs_gstreamer_audio_video_sample" not built

### ISSUE THREAD

**Issue by AbhinavSandru** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#1051]
<img width="960" alt="Screenshot 2023-08-22 194104" src="https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/assets/98754726/9814e8ac-bec0-411c-bb06-e49d8316f265">

OS : Linux
Version : Ubuntu 20.04.5

Checking for module 'libkvspicUtils'
--   No package 'libkvspicUtils' found

**Comment by AbhinavSandru** [comment]
<img width="660" alt="image" src="https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/assets/98754726/f0a3fde6-057e-4d12-b05c-c63dbdc1d251">
That wasnt the problem actually, when I give the make command the missing module is getting built but there are actually more missing libraries that need to be built like for example "kvs_gstreamer_sample" "gstkvssink"
<img width="349" alt="image" src="https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/assets/98754726/8a6e0f12-50f9-4ce6-8507-8e4e8074f63a">

**Comment by disa6302** [comment]
Not sure I understand. Can you clarify the exact issue? Your screenshots suggest you have the samples built and the libraries. What is the error?

**Comment by AbhinavSandru** [comment]
The second screenshot is from a youtube video with all the libraries built the first screen are those that were built for me they are incomplete

**Comment by AbhinavSandru** [comment]
I require the kvs_gstreamer_audio_video_sample but it is not built in mine

**Comment by disa6302** [comment]
@AbhinavSandru , 

Please provide the following details:
- What version of the SDK are you building?
- Have you followed the README to install gstreamer on your system?
- What Cmake command are you running? To generate the samples, you need to run `cmake .. -DBUILD_GSTREAMER_PLUGIN=ON`.
