### ISSUE TITLE
i can't push rtsp url and local mp4 video to aws 

### ISSUE THREAD

**Issue by sxj731533730** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#1054]
Hello, I am a developer from China who uses the Hong Kong node in China. I have configured the AWS service based on this video url https://www.youtube.com/watch?v=nVxwX7Q9nPU&t=172s and can only push videos in mkv format to play on AWS, but cannot use rtsp streaming or local mp4 video playback

My local computer configuration is ubutnu20.04, Hong Kong, China IP

你好，我是来自一名中国的开发者，使用中国香港节点，我按照这个视频配置了aws服务，仅仅能推送mkv格式的视频在aws上面播放，而无法使用rtsp流媒体播放和本地的mp4视频播放
 
我的本地电脑配置是ubutnu20.04 ,中国香港ip

**Comment by disa6302** [comment]
@sxj731533730 , 

Please provide the following details:
1. What version of the SDK is being used?
2. When using RTSP URL, did you try a pipeline with another sink to ensure the source works with other sinks?
3. When using local mp4, did you try a pipeline with another sink to ensure the source works with other sinks?

**Comment by sirknightj** [comment]
It looks like you are using `kvs_gstreamer_sample`.

Could you try using this `.mp4` file to confirm that `.mp4` files are able to be uploaded using the sample?
https://catalog.us-east-1.prod.workshops.aws/kinesis-video-streams/en-US/3-stream/2-sample-app#download-the-video-for-playback

Could you also verify that the `demo.mp4` you are attempting to upload is a valid playable `.mp4` file? Does `ffprobe` give any errors?

**Comment by jdelapla** [comment]
Are you able to construct a gstreamer pipeline to pull from the rtsp source and put into a file sink? 

Our sample gives a demonstration of how to pull from an RTSP camera but it's using a specific h264 depayer and pad that may not be applicable to all RTSP cameras.
