### ISSUE TITLE
[QUESTION] DCMAKE_INSTALL_PREFIX not copy all `.so` file provided directory

### ISSUE THREAD

**Issue by fti-sbargule** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#1086]
I use `DCMAKE_INSTALL_PREFIX`

1. Step 1: Cmake  
`root@ubuntuclient02:/home/suyog/amazon-kinesis-video-streams-producer-sdk-cpp/amazon-kinesis-video-streams-producer-sdk-cpp/build# cmake -DCMAKE_INSTALL_PREFIX=/home/suyog/ ..
`
2.  Step 2: Make
`root@ubuntuclient02:/home/suyog/amazon-kinesis-video-streams-producer-sdk-cpp/amazon-kinesis-video-streams-producer-sdk-cpp/build# make `

3.  Step 3: Make Install
`root@ubuntuclient02:/home/suyog/amazon-kinesis-video-streams-producer-sdk-cpp/amazon-kinesis-video-streams-producer-sdk-cpp/build# make `

OutPut:
`root@ubuntuclient02:/home/suyog/lib# ls libKinesisVideoProducer.so`

![Screenshot from 2023-10-18 16-13-38](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/assets/121230355/6cbaa600-f6eb-44ed-bbab-152e691ffaaf)

- `libKinesisVideoProducer.so ` only this file included in lib directory 

-  This build directory  others `.so`  files not included in /home/suyog/lib/ directory. 

![Screenshot from 2023-10-18 16-18-20](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/assets/121230355/3d4abe6d-5b2b-454e-842e-aa547d62f6aa)

- Following image ` libcproducer.so`  this `.so` file not included in /home/suyog/lib/  directory 

![Screenshot from 2023-10-18 16-20-48](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/assets/121230355/7a2310aa-9600-496e-b73b-5aef04a98880)

Please Help me to solve this problem

**Comment by niyatim23** [comment]
Hi @fti-sbargule, thanks for reporting this. I have fixed it in the `develop` branch. It will be available in the next release. 

Closing as this has been fixed!
