### ISSUE TITLE
Resolution issue on macOS High Sierra

### ISSUE THREAD

**Issue by MariaTolstov** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#110]
Hi,
I am trying to run the kinesis_video_gstreamer_sample_app, however I get the following error: 
**Default list of resolutions (1920x1080, 1280x720, 640x480) are not supported by video source.**
I'm on macOS High Sierra with a 720p FaceTime HD camera (which should support 1280x720).

Any help would be much appreciated.

Here is the full output:
./kinesis_video_gstreamer_sample_app my-stream
[INFO ][2018-08-26 12:32:29] Initializing curl.
[INFO ][2018-08-26 12:32:29] 
createKinesisVideoClient(): Creating Kinesis Video Client
[INFO ][2018-08-26 12:32:29] 
heapInitialize(): Initializing native heap with limit size 536870912, spill ratio 0% and flags 0x00000001
[INFO ][2018-08-26 12:32:29] 
heapInitialize(): Creating AIV heap.
[INFO ][2018-08-26 12:32:29] 
heapInitialize(): Heap is initialized OK
[INFO ][2018-08-26 12:32:29] Refreshing credentials. Force refreshing: 0 Now time is: 1535286749 Expiration: 0
[INFO ][2018-08-26 12:32:29] New credentials expiration is 1535289149
[DEBUG][2018-08-26 12:32:29] createDeviceHandler invoked
[INFO ][2018-08-26 12:32:29] 
createDeviceResultEvent(): Create device result event.
[DEBUG][2018-08-26 12:32:29] clientReadyHandler invoked
[DEBUG][2018-08-26 12:32:29] Awaiting for the producer to become ready...
[DEBUG][2018-08-26 12:32:29] Kinesis Video producer is Ready.
[DEBUG][2018-08-26 12:32:29] Client is ready
[INFO ][2018-08-26 12:32:29] Creating Kinesis Video Stream my-stream
[INFO ][2018-08-26 12:32:29] 
createKinesisVideoStream(): Creating Kinesis Video Stream.
[DEBUG][2018-08-26 12:32:29] describeStreamHandler invoked
[DEBUG][2018-08-26 12:32:29] Awaiting for the stream to become ready...
[INFO ][2018-08-26 12:32:29] Refreshing credentials. Force refreshing: 0 Now time is: 1535286749 Expiration: 0
[DEBUG][2018-08-26 12:32:30] describeStream response: {"StreamInfo":{"CreationTime":1.535022586204E9,"DataRetentionInHours":1,"DeviceName":"java-demo-application","KmsKeyId":"arn:aws:kms:us-east-1:369723887231:alias/aws/kinesisvideo","MediaType":"video/h264","Status":"ACTIVE","StreamARN":"arn:aws:kinesisvideo:us-east-1:369723887231:stream/my-stream/1535022586204","StreamName":"my-stream","Version":"V8rgyhHzL3zvpmC618m3"}}
[INFO ][2018-08-26 12:32:30] Discovered existing Kinesis Video stream: arn:aws:kinesisvideo:us-east-1:369723887231:stream/my-stream/1535022586204
[INFO ][2018-08-26 12:32:30] stream arn in stream_info struct: arn:aws:kinesisvideo:us-east-1:369723887231:stream/my-stream/1535022586204
[INFO ][2018-08-26 12:32:30] 
describeStreamResultEvent(): Describe stream result event.
[DEBUG][2018-08-26 12:32:30] streamingEndpointHandler invoked
[INFO ][2018-08-26 12:32:30] Refreshing credentials. Force refreshing: 0 Now time is: 1535286750 Expiration: 0
[DEBUG][2018-08-26 12:32:31] getStreamingEndpoint response: {"DataEndpoint":"https://s-1e415f8b.kinesisvideo.us-east-1.amazonaws.com"}
[INFO ][2018-08-26 12:32:31] streaming to endpoint: https://s-1e415f8b.kinesisvideo.us-east-1.amazonaws.com
[INFO ][2018-08-26 12:32:31] 
getStreamingEndpointResultEvent(): Get streaming endpoint result event.
[DEBUG][2018-08-26 12:32:31] streamingTokenHandler invoked
[INFO ][2018-08-26 12:32:31] Refreshing credentials. Force refreshing: 1 Now time is: 1535286751 Expiration: 1535289149
[INFO ][2018-08-26 12:32:31] New credentials expiration is 1535289151
[INFO ][2018-08-26 12:32:31] 
getStreamingTokenResultEvent(): Get streaming token result event.
[DEBUG][2018-08-26 12:32:31] streamReadyHandler invoked
[DEBUG][2018-08-26 12:32:31] Kinesis Video stream my-stream is Ready.
[DEBUG][2018-08-26 12:32:31] Stream is ready
**Default list of resolutions (1920x1080, 1280x720, 640x480) are not supported by video source**
[INFO ][2018-08-26 12:32:31] 
freeKinesisVideoClient(): Freeing Kinesis Video Client
[INFO ][2018-08-26 12:32:31] 
commonHeapDebugCheckAllocator(): Heap is initialized
[INFO ][2018-08-26 12:32:31] 
commonHeapDebugCheckAllocator(): Heap limit: 				536870912
[INFO ][2018-08-26 12:32:31] 
commonHeapDebugCheckAllocator(): Heap size: 				0
[INFO ][2018-08-26 12:32:31] 
commonHeapDebugCheckAllocator(): Number of allocations: 				0
[INFO ][2018-08-26 12:32:31] 
aivHeapDebugCheckAllocator(): Allocated blocks pointer: 				0x0
[INFO ][2018-08-26 12:32:31] 
aivHeapDebugCheckAllocator(): *******************************************
[INFO ][2018-08-26 12:32:31] 
aivHeapDebugCheckAllocator(): *******************************************
[INFO ][2018-08-26 12:32:31] 
aivHeapDebugCheckAllocator(): Free blocks pointer: 				0x10b574000
[INFO ][2018-08-26 12:32:31] 
aivHeapDebugCheckAllocator(): *******************************************
[INFO ][2018-08-26 12:32:31] 
aivHeapDebugCheckAllocator(): Block:	0x10b574000		size:	536870872
[INFO ][2018-08-26 12:32:31] 
aivHeapDebugCheckAllocator(): *******************************************
[INFO ][2018-08-26 12:32:31] 
heapRelease(): Freeing native heap.
[INFO ][2018-08-26 12:32:31] Freeing Kinesis Video Stream my-stream
[INFO ][2018-08-26 12:32:31] 
freeKinesisVideoStream(): Freeing Kinesis Video stream.
[INFO ][2018-08-26 12:32:31] Curl shutdown.

**Comment by unicornss** [comment]
Hi @MariaTolstov  

Could you please try with command line arguments similar to the one below:

>  **Usage:** AWS_ACCESS_KEY_ID=YourAccessKeyId AWS_SECRET_ACCESS_KEY=YourSecretAccessKey ./kinesis_video_gstreamer_sample_app -w 1280 -h 720 -f 25 -b 512 my-stream

Sometimes the camera does not support all resolutions at 30 fps framerate. You can use the `GST_DEBUG=4` command as below to see that resolutions are supported. 

**Example:**
`GST_DEBUG=4 ./kinesis_video_gstreamer_sample_app -w 1280 -h 720 -f 25 -b 512 my-stream`

Also, you can also run a similar command with the sample application `kvs_producer_plugin_demo` which encapsulates  Kinesis Video Producer as a GStreamer element. Both these sample applications send video from your camera to Kinesis Video Streams.

Let us know if that helps.
