### ISSUE TITLE
[QUESTION] what inexpensive Kinesis Video Stream approved IP Camera can I use to prototype

### ISSUE THREAD

**Issue by ccabanero** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#1129]
A one liner description about the use case and what you are trying to achieve

I am interested in an inexpensive IP camera to demonstrate to my team the value of Kinesis Video Streams as a service to use to send camera feeds to the cloud.

** Logging **
Add relevent SDK logging.  IMPORTANT NOTE:  Please make sure to NOT share AWS access credentials under any circumstance!  Please make sure they are not in the logs.

N/A

** Any design considerations/constraints **
Explain in detail how you would like to integrate our SDK into your solution 

* We have a solution whereby we need to stream IP camera feeds to the cloud.  I am proposing to my team to use Kinesis Video Streams to send camera feeds to AWS - then, to build solutions for feed insights in AWS.
* In general, the solution is: a Raspberry Pi has the Producer C++ SDK gstreamer sample app - and uses this to send an IP Camera feed (vis RTSP) to Kinesis Video Streams.  I have been prototyping with Kinesis Video Streams with a few IP cameras and running into issues.  For example [this issue logged here demonstrates having things setup correctly except for the IP camera hardware configuration](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/issues/1127).
* What I am interested in is a list of inexpensive IP cameras for prototyping that require little to no configuration and can successfully send camera feeds to Kinesis Video stream.  For example, what do AWSLabs team members use for prototyping and can advise on configuration steps? Thank you

** If you would not like to open an issue to discuss your solution in open-platform, please email your question to kinesis-video-support@amazon.com **

**Comment by jdelapla** [comment]
We don't have a curated list of supported IP cameras. We're used on a wide variety of specs and you're welcome to choose whatever works for your needs.
