### ISSUE TITLE
Missing codec private data error

### ISSUE THREAD

**Issue by backdoorcodr** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#12]
Hello,

I am trying to execute the demo application and for that I build the application as instructed and executed `./start `.

The error I am getting is attached: 
![1](https://user-images.githubusercontent.com/34404238/34058442-4d8eb9a0-e1db-11e7-9b13-3e16f8de6d9b.png)

As mentioned that this may be intermittent issue and can be resolved by refresh. However, does not seem to work for me yet.

**Comment by MushMal** [comment]
@backdoorcodr the unit tests do not produce valid h264 frames. They are for throughput/SDK correctness validation purpose only.
