### ISSUE TITLE
Surface Pro Intel avstream camera 2500 green stream img

### ISSUE THREAD

**Issue by Fuzzywuzzy1991** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#148]
Having SDK build for Surface Pro we are finally able to stream to Kinesis Video Stream.
Camera identified by Windows: Intel avstream camera 2500.
We successfully run Stream on our Surface Pro with command gst-launch-1.0 ksvideosrc do-timestamp=TRUE ! video/x-raw,width=640,height=480,framerate=30/1 ! videoconvert ! x264enc bframes=0 key-int-max=10 bitrate=512 ! video/x-h264,profile=baseline,stream-format=avc,alignment=au,width=640,height=480,framerate=30/1 ! kvssink stream-name=“LiveRekognitionVideoAnalysis” access-key= secret-key=

But we got green video on our stream. I have attached a screenshot. 
<img width="1266" alt="screen shot 2018-11-21 at 7 32 56 pm" src="https://user-images.githubusercontent.com/34865253/48917382-239c9b00-ee8f-11e8-995d-eaf80a77c698.png">

Usually photo with this camera looks like better and not green.

Any solutions to improve quality of stream image?

**Comment by eorlovsky** [comment]
@unicornss do you know what kind of this could be? Have the same issue on my side

**Comment by unicornss** [comment]
Hi @Fuzzywuzzy1991 @eorlovsky

 Could you try the following settings

gst-launch-1.0 ksvideosrc do-timestamp=TRUE ! video/x-raw,width=640,height=480,framerate=30/1 ! videoconvert ! video/x-raw,format=I420,width=640,height=480,framerate=30/1 ! x264enc bframes=0 key-int-max=10 bitrate=512 ! video/x-h264,profile=baseline,stream-format=avc,alignment=au,width=640,height=480,framerate=30/1 ! kvssink stream-name=“LiveRekognitionVideoAnalysis” access-key= secret-key=

Also, if you could find the codec format that the camera supports, it will be helpful.  Thanks

**Comment by eorlovsky** [comment]
@unicornss Thanks for the reply. But unfortunately,  your command gives the same result? Is possible to debug the problem? Maybe to enabling DEBUG log? 
Also, what do you mean by "codec format that the camera supports"? Do you have a command to execute to get this info?

**Comment by eorlovsky** [comment]
![377fded8566a43e6b4bdc825c884f55b](https://user-images.githubusercontent.com/861869/48972592-60ef5d00-f036-11e8-82ba-cca75c9702c9.png)

**Comment by unicornss** [comment]
Thanks @eorlovsky.

Could you please check if the camera has the latest driver update? or is it possible to try a USB camera if USB ports are available?
Unfortunately,  we do not have the same camera model to debug why this camera model video has green tint.

**Comment by Fuzzywuzzy1991** [comment]
Hi @unicornss.
How we can use usb camera in our command gst-launch-1.0 ksvideosrc do-timestamp=TRUE ! video/x-raw,width=640,height=480,framerate=30/1 ! videoconvert ! video/x-raw,format=I420,width=640,height=480,framerate=30/1 ! x264enc bframes=0 key-int-max=10 bitrate=512 ! video/x-h264,profile=baseline,stream-format=avc,alignment=au,width=640,height=480,framerate=30/1 ! kvssink stream-name=“LiveRekognitionVideoAnalysis” access-key= secret-key= 
in Windows 10.
Can you help?

**Comment by zhiyua-git** [comment]
Hi @Fuzzywuzzy1991 ,

You can run gst-device-monitor-1.0 to find the device name of your USB device. If your device name is HD Webcam XXX, then your command need to be:

gst-launch-1.0 ksvideosrc **device-name="HD Webcam XXX"** do-timestamp=TRUE ! video/x-raw,width=640,height=480,framerate=30/1 ! videoconvert ! video/x-raw,format=I420,width=640,height=480,framerate=30/1 ! x264enc bframes=0 key-int-max=10 bitrate=512 ! video/x-h264,profile=baseline,stream-format=avc,alignment=au,width=640,height=480,framerate=30/1 ! kvssink stream-name=“LiveRekognitionVideoAnalysis” access-key= secret-key=

**Comment by unicornss** [comment]
Closing this issue for now as @zhiyua-git  has provided the details. Please reopen or create a new request if additional support is required.
