### ISSUE TITLE
How to Build Kinesis Producer cpp on windows

### ISSUE THREAD

**Issue by ibr123** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#15]
Hi,

In the [document](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/kinesisvideo-dg.pdf#gs-console-whatnext)  at the prerequisite section there is a paragraph saying:

> > Your NativeLibraryPath must contain your KinesisVideoProducerJNI file, available at https://
> github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp. The file extension for this file
> will depend on your operating system:
> • KinesisVideoProducerJNI.so for Linux
> • KinesisVideoProducerJNI.dylib for macOS
> • KinesisVideoProducerJNI.dll for Windows (not currently available)
> Note
> Pre-built libraries are not currently available. You must build the libraries yourself for your
> platform.

as stated that there is no ready scripts to build on windows, but how to do that?

Thanks

**Comment by sambithota** [comment]
Is there an answer to this. I am facing the same issue. I am getting this. 
EXCEPTION: UnsatisfiedLinkError: Unsatisfied link error. Loading native library KinesisVideoProducerJNI failed with java.lang.UnsatisfiedLinkError
Because libKinesisVideoProducerJNI.dll is not present. How to generate this in windows?

**Comment by zhiyua-git** [comment]
Thanks for reaching out, we are still looking into the WIndows build and hope to get the Windows solution out soon.

**Comment by sambithota** [comment]
Any update on this one?

**Comment by unicornss** [comment]
We will publish once we get the Windows Build for Kinesis Video Streams in our roadmap.
Closing this for now.

Thanks
-SS

**Comment by sandeepatgetronics** [comment]
Am I right in understanding that as the  KinesisVideoProducerJNI.dll for windows is missing, we cannot use the Producer library when developing in Windows. If we have to use the Producer libary we should either be developing in Linux or macOs. Is that correct?

**Comment by MushMal** [comment]
@sandeepatgetronics you are correct in your assumption. Unfortunately, we don't have any build support for the Windows platform yet. We are planning on closing that gap and supporting Windows as a first class platform in a very near future.

**Comment by LilaRios** [comment]
Hello,

Is there any update for the build support for the Windows platform?

**Comment by zhiyua-git** [comment]
Hi @LilaRios , it is available now. You can use https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java/tree/master/src/main/resources/lib/windows or you can build it following https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/install-instructions-windows-msvc.md
