### ISSUE TITLE
Wrong Log Error, sample_multistream/sample_rtsp

### ISSUE THREAD

**Issue by ohlr** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#152]
Hi,

[kinesis_video_gstreamer_sample_multistream_app.cpp#L375](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/386526e3a4776a1b4049a80f4d2d4b09081284e2/kinesis-video-gst-demo/kinesis_video_gstreamer_sample_multistream_app.cpp#L375)

should be changed to ./kinesis_video_gstreamer_sample_multistream_app

same for rtsp:
[kinesis_video_gstreamer_sample_rtsp_app.cpp#L358](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/kinesis-video-gst-demo/kinesis_video_gstreamer_sample_rtsp_app.cpp#L358)

should be changed to ./kinesis_video_gstreamer_sample_rtsp_app

**Comment by unicornss** [comment]
Thanks @ohlr for notifying us. 

We will be updating the samples soon. Thanks again.
