### ISSUE TITLE
Streaming from PI gives error

### ISSUE THREAD

**Issue by smitshilu** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#16]
Hello,
I have installed producer SDK on pi successfully but I am receiving following error while running sample app.

```
AWS_ACCESS_KEY_ID=############
AWS_SECRET_ACCESS_KEY=################################### ./kinesis_video_gstreamer_sample_app test_stream
```

Error:

```
getStreamingTokenResultEvent(): Get streaming token result event.DEBUG - Kinesis Video stream test_stream is Ready.
DEBUG - Stream is ready
Error received from element source: Internal data stream error.
Debugging information: gstbasesrc.c(2939): gst_base_src_loop (): /GstPipeline:test-pipeline/GstV4l2Src:source:
streaming stopped, reason not-negotiated (-4)

freeKinesisVideoClient(): Freeing Kinesis Video ClientDEBUG - streamDataAvailableHandler invoked
DEBUG - streamClosedHandler invoked

commonHeapDebugCheckAllocator(): Heap is initialized
commonHeapDebugCheckAllocator(): Heap limit: 				536870912
commonHeapDebugCheckAllocator(): Heap size: 				0
commonHeapDebugCheckAllocator(): Number of allocations: 				0
aivHeapDebugCheckAllocator(): Allocated blocks pointer: 				(nil)
aivHeapDebugCheckAllocator(): *******************************************
aivHeapDebugCheckAllocator(): *******************************************
aivHeapDebugCheckAllocator(): Free blocks pointer: 				0x55eab008
aivHeapDebugCheckAllocator(): *******************************************
aivHeapDebugCheckAllocator(): Block:	0x55eab008		size:	536870887
aivHeapDebugCheckAllocator(): *******************************************
heapRelease(): Freeing native heap.INFO - Curl shutdown.

```

**Comment by zhiyua-git** [comment]
Could I ask you to try the following from the readme:

$ vcgencmd get_camera
$ sudo modprobe bcm2835-v4l2
$ ls /dev/video*

If the camera is successfully detected and the driver is loaded then could you please follow with

$ sudo rpi-update
$ sudo shutdown -r 0

Please let me know if this helped

**Comment by zhiyua-git** [comment]
Hi,
We just released SDK Version 1.1.1 which contains an USB camera gstreamer configuration fix. If you were testing on your USB camera, can you try the latest release and see if it solves your issue? Thanks.

**Comment by shiopon01** [comment]
Hi,
I was in trouble too with this problem. (using Raspberry Pi)
However, It worked by correcting line 336 and 356 in `kinesis-video-gst-demo/kinesis_video_gstreamer_sample_app.cpp` 😃
(change the number from 1280 and 720 to 640 and 480)

I think it would be better to write the file name in README.md along with the line number.
Thanks.

**Comment by unicornss** [comment]
Thanks, Shiopon01. Glad you are able to resolve and also posting your notes to help others :)
-SS

**Comment by unicornss** [comment]
Hi  smitshilu ,  Are you still having issues with the install steps with the latest instructions and SDK version?

Thanks
-SS

**Comment by smitshilu** [comment]
I am sorry for late reply. @unicornss I have changed my platform to TX2 so not sure about pi.

**Comment by unicornss** [comment]
Glad to hear that.

Thanks
-SS
