### ISSUE TITLE
object detection in kinesis video stream

### ISSUE THREAD

**Issue by sujithaperumal** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#174]
I have created a kinesis video stream and am streaming my live video through laptop camera. I now want to detect objects present in the video and store the information in dynamodb. Is this is possible to achieve? Any help would be appreciated. Thanks in advance!

**Comment by sujithaperumal** [comment]
I have created a stream processor and started it.The stream processor is running successfully.
{
    "Name": "store-processors",
    "StreamProcessorArn": "arn:aws:rekognition:us-west-2:073686542274:streamprocessor/store-processors",
    "Status": "RUNNING",
    "CreationTimestamp": 1550142822.19,
    "LastUpdateTimestamp": 1550142934.694,
    "Input": {
        "KinesisVideoStream": {
            "Arn": "arn:aws:kinesisvideo:us-west-2:073686542274:stream/ExampleFaceStream/1550142435029"
        }
    },
    "Output": {
        "KinesisDataStream": {
            "Arn": "arn:aws:kinesis:us-west-2:073686542274:stream/AmazonRekognitionExampleFacesStreams"
        }
    },
    "RoleArn": "arn:aws:iam::073686542274:role/ExampleRekognitionRole",
    "Settings": {
        "FaceSearch": {
            "CollectionId": "ExampleFacesCollection",
            "FaceMatchThreshold": 85.5
        }
    }
}

Now, aws says 
Amazon Rekognition Video streams Amazon Rekognition Video analysis information to the Kinesis data stream. The following is a JSON example for a single record.

{
  "InputInformation": {
    "KinesisVideo": {
      "StreamArn": "arn:aws:kinesisvideo:us-west-2:nnnnnnnnnnnn:stream/stream-name",
      "FragmentNumber": "91343852333289682796718532614445757584843717598",
      "ServerTimestamp": 1510552593.455,
      "ProducerTimestamp": 1510552593.193,
      "FrameOffsetInSeconds": 2
    }
  },
  "StreamProcessorInformation": {
    "Status": "RUNNING"
  },
  "FaceSearchResponse": [
    {
      "DetectedFace": {
        "BoundingBox": {
          "Height": 0.075,
          "Width": 0.05625,
          "Left": 0.428125,
          "Top": 0.40833333
        },
        "Confidence": 99.975174,
        "Landmarks": [
          {
            "X": 0.4452057,
            "Y": 0.4395594,
            "Type": "eyeLeft"
          },
          {
            "X": 0.46340984,
            "Y": 0.43744427,
            "Type": "eyeRight"
          },
          {
            "X": 0.45960626,
            "Y": 0.4526856,
            "Type": "nose"
          },
          {
            "X": 0.44958648,
            "Y": 0.4696949,
            "Type": "mouthLeft"
          },
          {
            "X": 0.46409217,
            "Y": 0.46704912,
            "Type": "mouthRight"
          }
        ],
        "Pose": {
          "Pitch": 2.9691637,
          "Roll": -6.8904796,
          "Yaw": 23.84388
        },
        "Quality": {
          "Brightness": 40.592964,
          "Sharpness": 96.09616
        }
      },
      "MatchedFaces": [
        {
          "Similarity": 88.863960,
          "Face": {
            "BoundingBox": {
              "Height": 0.557692,
              "Width": 0.749838,
              "Left": 0.103426,
              "Top": 0.206731
            },
            "FaceId": "ed1b560f-d6af-5158-989a-ff586c931545",
            "Confidence": 99.999201,
            "ImageId": "70e09693-2114-57e1-807c-50b6d61fa4dc",
            "ExternalImageId": "matchedImage.jpeg"
          }
        }
      ]
    }
  ]
}
 where can i find this json record? Or should i write some command to display it? Please help! Thanks!

**Comment by zhiyua-git** [comment]
Hi @sujithaperumal ,

For object detection, you can refer to https://aws.amazon.com/blogs/machine-learning/analyze-live-video-at-scale-in-real-time-using-amazon-kinesis-video-streams-and-amazon-sagemaker/.

For Rekognition integration, you can try the sample [here](https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/master/src/test/java/com/amazonaws/kinesisvideo/parser/examples/KinesisVideoRekognitionIntegrationExampleTest.java#L32), the instruction is [here](https://github.com/aws/amazon-kinesis-video-streams-parser-library#kinesisvideorekognitionintegrationexample). This is a sample drawing a bounding box based on the json Rekognition returns and send back to Kinesis Video. If you just want to get the json output from Rekognition, you can refer to [here](https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/master/src/main/java/com/amazonaws/kinesisvideo/parser/rekognition/processor/RekognitionStreamProcessor.java#L150). 

Hope it helps,
-ZH

**Comment by sujithaperumal** [comment]
Thanks much @zhiyua-git

**Comment by hameedriswan7** [comment]
is possible to store kinesis video stream in S3 or somewhere? as like chunk or some other technique...please share

**Comment by MushMal** [comment]
@hameedriswan7 KVS already has persistent storage if you need to store the data. KVS doesn't store in S3 buckets directly. However, you could use GetMedai API (using AWS SDK) to pull the media and store it in S3.

**Comment by hameedriswan7** [comment]
GetMadia API. for now i am using gstream run for play stream in KVS in Aws. is getmedia help to store live stream in some other buckrtes .please share some reference
