### ISSUE TITLE
Publish Raspberry Pi Getting Started Example

### ISSUE THREAD

**Issue by nickrobinson** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#2]
@gauravgh, In issue #1 you make reference to a raspberry pi getting started guide. Do you have a link to the code referenced in this document. I am particularly interested in getting install_kinesis_video_demo.sh script and associated files.

**Comment by MushMal** [comment]
We will be publishing an update shortly. The updated build script will be able to build on Raspbery PI and the updated application code will be able to run on PI.

**Comment by MushMal** [comment]
The latest commit contains the enhanced install-script and some other fixes for Raspberry PI
