### ISSUE TITLE
ERROR occured during ./install-script in raspberry pi for streaming video in amazon kinesis in gstreamer

### ISSUE THREAD

**Issue by Raghava248** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#206]
![raspikinesis](https://user-images.githubusercontent.com/21008172/57830876-1a9edd80-77d1-11e9-9840-ae36ad703cb5.png)
please help 
@chehefen 
Thank you

**Comment by chehefen** [comment]
can you get the following packages:
```
$ sudo apt-get update
$ sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-base-apps
$ sudo apt-get install gstreamer1.0-plugins-bad gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-tools gstreamer1.0-omx
```
Then run min-install-script? Thanks

**Comment by chehefen** [comment]
Can you tell us about your use case of kvs? Thanks

**Comment by Raghava248** [comment]
Yeah Thank you I solved the problem but the thing is while doing live stream 
Iam facing delay currently Iam using this command
gst-launch-1.0 -v v4l2src device=/dev/video0 ! videoconvert ! video/x-raw,format=I420,width=640,height=480,framerate=30/1 ! x264enc  bframes=0 key-int-max=45 bitrate=500 tune=zerolatency ! video/x-h264,stream-format=avc,alignment=au ! kvssink stream-name=YourStreamName storage-size=128 access-key="YourAccessKey" secret-key="YourSecretKey"
In raspberry pi so please help me how to reduce latency

**Comment by chehefen** [comment]
what kind of latency are you expecting the achieve? are you using the stream for playback or realtime analysis?

**Comment by Raghava248** [comment]
we are using stream for real-time analysis and the delay is around 15 seconds

**Comment by chehefen** [comment]
by default the plugin streams to us-west-2. You can add region="blah" the kvssink plugin to stream to other regions.

**Comment by Raghava248** [comment]
Iam trying to achieve delay less than 5 seconds during streaming video in kinesis video streamig console
so help me if there are any changes in parameters in this command to reduce the delay
gst-launch-1.0 -v v4l2src device=/dev/video0 ! videoconvert ! video/x-raw,format=I420,width=640,height=480,framerate=30/1 ! x264enc bframes=0 key-int-max=45 bitrate=500 tune=zerolatency ! video/x-h264,stream-format=avc,alignment=au ! kvssink stream-name=YourStreamName storage-size=128 access-key="YourAccessKey" secret-key="YourSecretKey"

**Comment by chehefen** [comment]
can you tell us where are you located? If you are streaming from asia, you should use ap-northeast-1 like such
```
gst-launch-1.0 -v v4l2src device=/dev/video0 ! videoconvert ! video/x-raw,format=I420,width=640,height=480,framerate=30/1 ! x264enc bframes=0 key-int-max=45 bitrate=500 tune=zerolatency ! video/x-h264,stream-format=avc,alignment=au ! kvssink stream-name=YourStreamName storage-size=128 access-key="YourAccessKey" secret-key="YourSecretKey" aws-region="ap-northeast-1"
```

**Comment by Raghava248** [comment]
my location is us-esat-1(virginia)
thank you

**Comment by chehefen** [comment]
can you try this pipeline
```
gst-launch-1.0 -v v4l2src device=/dev/video0 ! videoconvert ! video/x-raw,format=I420,width=640,height=480,framerate=30/1 ! x264enc bframes=0 key-int-max=30 bitrate=500 tune=zerolatency ! video/x-h264,stream-format=avc,alignment=au,profile=baseline ! kvssink stream-name=YourStreamName storage-size=128 access-key="YourAccessKey" secret-key="YourSecretKey" aws-region="us-east-1"
```

**Comment by chehefen** [comment]
Can you tell us how are you consuming the video for real-time analytics? Thanks.

**Comment by Raghava248** [comment]
so Iam planning that video stream to store in aws s3 and the use it for further processing

**Comment by MushMal** [comment]
@Raghava248 thanks for the question. I assume you are observing the "latency" by viewing the console playback? Just a note that the console playback is not a "real-time" playback. It's a fragment-based playback which has to get the time index, retrieve the fragment from the store, generate mpeg so the browsers MSE can render the fragments on your browser. Similar to HLS or MPEG-DASH. The variable factor in this mode is not only the fragment duration as the fragment needs to be fully assembled before the playback is attempted but also the storage and indexing latencies.
In general, you can attempt to lower your fragmentation rate by controlling key-int-max and frame rate but the recommendation is to not produce lesser than a second fragments.
If, however, you would like to have a real-time rendering, you might want to use the GetMedia API. The parser library has a number of examples for the decoding/playback as well as downloading the fragments: https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/parser-library.html

**Comment by Raghava248** [comment]
Thank you
