### ISSUE TITLE
Green artifacts in video when streaming on raspberry

### ISSUE THREAD

**Issue by mrtj** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#207]
Hello, did you find the cause / solution of the issue of the green artifacts when streaming on raspberry, mentioned in the releases notes of Release 1.1.2 (January 2018)? It is true that if I lower the resolution to for example 640x480 then the artifacts go away but I would like to stream with a higher resolution.

**Comment by MushMal** [comment]
@mrtj there shouldn't be any issues with it with the latest SDK. Make sure you are using a hardware accelerated encoder on devices like RPi to ensure high-density stream.

**Comment by unicornss** [comment]
Closing this issue for now. Please reopen or create a new one if needed.
