### ISSUE TITLE
How to stream from USB camera to Amazon Kinesis with this source in Android

### ISSUE THREAD

**Issue by kirilldev1010** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#209]
@MushMal 

How are you? 
Please provide me the instructions how I can build kinesis-video-gst-demo with Android NDK. 
I have tried to build it with Android NDK, but always failed. 
Please help me. 
Regards

**Comment by MushMal** [comment]
@kirilldev1010 we have not tried building GStreamer sample with Android. NDK shouldn't be the issue - what you need is Android specific GStreamer so the NDK can match and link the right ABI.

**Comment by MushMal** [comment]
@kirilldev1010 I am resolving this issue for now. Please open separate issues for specifics that we can help.
