### ISSUE TITLE
How do i send GPS data to aws iot and use lambda to collect it back to any other computer

### ISSUE THREAD

**Issue by Raghava248** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#212]

**Comment by MushMal** [comment]
@Raghava248 could you please provide more details? Is this IoT specific question you are trying to get more info? If so, there is a separate project for IoT https://github.com/aws/aws-iot-device-sdk-embedded-C that you can look at.

While you can use KVS SDK to put any type of data, including GPS coordinates, the more specific data streaming services might be a better choice like Kinesis Data Streams.
