### ISSUE TITLE
ERROR - Kinesis Video stream can't be null

### ISSUE THREAD

**Issue by boddob** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#223]
Hi,

Calling "gst-inspect-1.0 kvssink" returns the following error after printing out all the element properties:

ERROR - Kinesis Video stream can't be null
terminate called after throwing an instance of 'std::runtime_error'
  what():  Kinesis Video stream can't be null
Aborted

Running on an aarch64 debian buster distro. The gstreamer tools/libs are v1.14.4

**Comment by chehefen** [comment]
Thanks for letting us know. We are aware of this issue and it will be fixed by the next release.
