### ISSUE TITLE
Gstreamer Metadata

### ISSUE THREAD

**Issue by pasawaya** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#224]
Is it possible to attach metadata when using the Gstreamer command line to produce an HLS stream? I see that [it's possible when using the C++ API](http://lifestyletransfer.com/how-to-add-metadata-to-gstreamer-buffer-in-python/).

**Comment by chehefen** [comment]
Can you tell us about what you are envisioning for attaching metadata using the gstreamer command line? Can you give us more details to help us understand your use case better.

**Comment by pasawaya** [comment]
I haven't fleshed out the exact specifics of my use case but I suppose I'm looking to attach some of the standard metadata the PutMedia API allows for such as producer timestamp/timecode along with some custom metadata such as a camera ID, a latitude-longitude coordinates, etc.

At a high level, I'm essentially trying to decide between the ease of use of a Gstreamer producer and the fine-grained control of a producer implemented with the C++/Java SDK.

**Comment by unicornss** [comment]
The GStreamer plugin (kvssink) uses the SDK underneath. Based on your use case description,either one of the samples should be fine for use case. 

Closing the issue for now. Please reopen or create a new one if needed.
