### ISSUE TITLE
Missing Mac Dependancy

### ISSUE THREAD

**Issue by dpmcgarry** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#23]
lib-pkg is required to be installed on the mac (at least for High Sierra), but isn't mentioned in the readme.  You may want to update it.

**Comment by bdhandap** [comment]
Hi Don McGarry,

Thanks for letting us know. We will add it in the ReadMe file.

Thanks
Babu

**Comment by unicornss** [comment]
Hi Babu, After High Sierra upgrade, I was able to get the install-script working after pkg-config install.  Thanks -SS
