### ISSUE TITLE
Plugin version

### ISSUE THREAD

**Issue by ecolgan** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#231]
It would be nice if the plugin version in GST_PLUGIN_DEFINE in gstkvssink.cpp matched the git tag.  Currently it is a constant  set at 1.0.  This number is displayed via gst-inspect-1.0

**Comment by MushMal** [comment]
Sounds like a good idea - we will take this into an action for further releases

**Comment by MushMal** [comment]
Resolving now ->
