### ISSUE TITLE
jsmn lib not found.. on Raspberry PI

### ISSUE THREAD

**Issue by pankeshpatel** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#237]
I have been trying to run  `./mini-install-script` of `Kinesis-video-native-build` folder. I am getting a message `jsmn lib not found. Installing`.

**Comment by MushMal** [comment]
min-install-script is detecting that you don't have jsmn installed so it tries to pull down and install it. Does the installation result in an error?

**Comment by pankeshpatel** [comment]
No, there is no error in installation. 

I  just realize that the raspberry PI's internet connection was lost some how. Therefore, the `./mini-install-script` was not able to pull the repository from github. 

Won't be nice, if we could write few lines in script that check the the internet connection and print a message, if the internet is not available.

**Comment by MushMal** [comment]
Perhaps adding some check at the start of the script makes sense. Though, checking for the general internet availability is a hard thing to crack. The "pulling down" step itself can be the indicator of the network availability.
