### ISSUE TITLE
Install Script Issue - raspberry pi

### ISSUE THREAD

**Issue by Alex-fanfanfan** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#246]
![WechatIMG145](https://user-images.githubusercontent.com/53839418/62578312-aca90600-b855-11e9-9bbe-1f061c2c2d15.jpeg)
I typed ./min-install-script and got this.

Another issue is that I can't run ./install-script because it said this is going to be more than ten hours and only allowed me to type ./min-install-script.

**Comment by oily126** [comment]
Hi @Alex-fanfanfan , 

Have you installed the dependencies before you run min-install-script?

$ sudo apt-get update
$ sudo apt-get install libssl-dev libcurl4-openssl-dev **liblog4cplus-1.1-9 liblog4cplus-dev**

https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/install-instructions-linux.md#install-steps-for-ubuntu-17x-and-raspbian-stretch-using-apt-get

**Comment by zhiyua-git** [comment]
Hi @Alex-fanfanfan ,

Have you installed the dependencies before you run min-install-script?

$ sudo apt-get update
$ sudo apt-get install libssl-dev libcurl4-openssl-dev **liblog4cplus-1.1-9 liblog4cplus-dev**

https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/install-instructions-linux.md#install-steps-for-ubuntu-17x-and-raspbian-stretch-using-apt-get

**Comment by Alex-fanfanfan** [comment]
`pi@raspberrypi:~/Downloads/log4cplus-1.2.1 $ sudo apt-get install libssl-dev libcurl4-openssl-dev liblog4cplus-1.1-9 liblog4cplus-dev

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package liblog4cplus-1.1-9
E: Couldn't find any package by regex 'liblog4cplus-1.1-9'
`

It showed this. Is that because I did not download the package?

**Comment by chehefen** [comment]
did you run sudo apt-get update?

**Comment by Alex-fanfanfan** [comment]
I did.

**Comment by chehefen** [comment]
can you tell us about what's your raspberry pi model and the os version?

**Comment by Alex-fanfanfan** [comment]
Raspberry Pi 3 Model B
OS version 8

**Comment by chehefen** [comment]
you can try do `sudo apt-get install liblog4cplus-dev` and run `min-install-script` to see if the producer builds. If not you have to upgrade to OS version 9. Dont forget to install all gstreamer dependencies too.

**Comment by chehefen** [comment]
customer managed to build the plugin. closing the issue.

**Comment by str3tch** [comment]
I have the exact same issue. What was the resolution? I have done `sudo apt-get install liblog4cplus-dev` but I still get the same error:

```
/home/pi/git/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-producer/src/DefaultCallbackProvider.cpp: In static member function ‘static void com::amazonaws::kinesis::video::DefaultCallbackProvider::logPrintHandler(UINT32, PCHAR, PCHAR, ...)’:
/home/pi/git/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-producer/src/DefaultCallbackProvider.cpp:308:40: error: ‘LOG4CPLUS_SUPPRESS_DOWHILE_WARNING’ was not declared in this scope
     LOG4CPLUS_SUPPRESS_DOWHILE_WARNING()
                                        ^
/home/pi/git/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-producer/src/DefaultCallbackProvider.cpp:321:39: error: ‘LOG4CPLUS_RESTORE_DOWHILE_WARNING’ was not declared in this scope
     LOG4CPLUS_RESTORE_DOWHILE_WARNING()
```

**Comment by fideliocc** [comment]
Please, can you share the solution? I'm having the same issue here and isn't related to the OS version, I tested it with Raspbian Stretch and Buster (the last OS release). Worth to mention that a few months ago I was able to perform build with `./install-script` (yes, it takes a lot of time to perform). But on this occasion, I find this new message suggesting to use `./min-install-script` instead. 

When I try to run the gstreamer_sample_app after this suggested installation, the stream is created but stopped with the error: 

`log4cplus:ERROR Failed to open file ./log/kvs.log`

I also found that this installation doesn't create the `/bin` directory at `amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-native-build/downloads/local`

Help is appreciated.
