### ISSUE TITLE
WARNING: erroneous pipeline: no element "kvssink" [NVIDIA Jetson Tx2]

### ISSUE THREAD

**Issue by ac4289** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#248]
Hi,
I am trying to use KVS on Jetson TX2 with JetPack 4.2. I compiled KVS producer library as instructed and copied files to `/usr/lib/aarch64-linux-gnu/`.
Here is my command.
```
sudo gst-launch-1.0 nvarguscamerasrc ! 'video/x-raw(memory:NVMM), width=(int)1920, height=(int)1080, format=(string)NV12, framerate=30/1' ! nvtee ! nvvidconv flip-method=0  ! 'video/x-raw, format=(string)NV12, width=640, height=480, framerate=30/1' ! omxh264enc  ! video/x-h264, stream-format=avc, alignment=au ! kvssink stream-name=*********** storage-size=512 access-key=************ secret-key=*********************
```
It worked right after compilation finished. Then I rebooted TX2 and it does not work anymore.
The only line of error message is
```
WARNING: erroneous pipeline: no element "kvssink"
```
But libgstkvssink.so exists under `/usr/lib/aarch64-linux-gnu/gstreamer-1.0`.
Here is the gst-inspect-1.0 output.
```
$ gst-inspect-1.0 kvssink

(gst-plugin-scanner:7820): GStreamer-WARNING **: 16:41:50.069: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstkvssink.so': /usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstkvssink.so: undefined symbol: _ZN3com9amazonaws7kinesis5video18CredentialProvider12getCallbacksEP17__ClientCallbacks
No such element or plugin 'kvssink'
```
How can i fix this error?
Thank you!

**Comment by zhiyua-git** [comment]
Hi @ac4289 ,

You need to add directory of libgstkvssink.so to environment variable GST_PLUGIN_PATH or move it to the directory where gstreamer plugins are in.

**Comment by chehefen** [comment]
It's complaining about not be able to find symbol in libproducer.so. the plugin is dynamically linked to the libproducer.so. Can you do `export LD_LIBRARY_PATH=/path/to/dir` for the directory that has libproducer.so?

**Comment by ac4289** [comment]
> It's complaining about not be able to find symbol in libproducer.so. the plugin is dynamically linked to the libproducer.so. Can you do `export LD_LIBRARY_PATH=/path/to/dir` for the directory that has libproducer.so?

Thank you for helping!
I tried this:
```
export LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/gstreamer-1.0
```
Still does not work.

**Comment by chehefen** [comment]
is that where your libproducer.so is?

**Comment by ac4289** [comment]
> is that where your libproducer.so is?

Yes

**Comment by chehefen** [comment]
what about libcproducer.so?

**Comment by ac4289** [comment]
libcproducer.so is under `/usr/lib/aarch64-linux-gnu/`

**Comment by chehefen** [comment]
can you move it to /usr/lib/aarch64-linux-gnu/gstreamer-1.0 too? and do `export LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/gstreamer-1.0`

**Comment by ac4289** [comment]
> LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/gstreamer-1.0

Does not work. T_T

**Comment by chehefen** [comment]
just wanna confirm libcproducer.so and libproducer.so are all in /usr/lib/aarch64-linux-gnu/gstreamer-1.0?

**Comment by ac4289** [comment]
> just wanna confirm libcproducer.so and libproducer.so are all in /usr/lib/aarch64-linux-gnu/gstreamer-1.0?

Yes

**Comment by unicornss** [comment]
Hi @ac4289  ,

> It worked right after compilation finished. 

Given that it worked first time, could you please run the [`source set_kvs_sdk_env.sh`](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/kinesis-video-native-build/install-script#L692) and see if that helps.

**Comment by ac4289** [comment]
> Hi @ac4289 ,
> 
> > It worked right after compilation finished.
> 
> Given that it worked first time, could you please run the [`source set_kvs_sdk_env.sh`](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/kinesis-video-native-build/install-script#L692) and see if that helps.

No I already tried that. I just reflashed TX2 with JetPack 4.2. I'll see how it goes.

**Comment by ac4289** [comment]
Ok, reflashed TX2 works with KVS. The difference is that the old OS had TVM installed which requires a change of Python path in .bashrc. 
Thank you again for your help!

**Comment by aimroboticsbying** [comment]
I'm getting the same error: no element "kvssink"
plugin scanner says: Failed to load libgstx264.so, undefined symbol x264_deblock_h_chroma_422_intra_neon
Did you have this issue? Do you know how to fix it? Thanks.

**Comment by MushMal** [comment]
Once you've successfully built the plugin, you should set the paths per: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/install-instructions-macos.md#setting-the-environment-variables-for-library-path
