### ISSUE TITLE
Failed to create Kinesis Video Stream - timed out.

### ISSUE THREAD

**Issue by Xiaoron** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#251]
I meet an issue that sometimes can not create Kinesis Video Stream,
Below is my test log, can u help me check?
[kvs_2019081309.log](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/files/3501207/kvs_2019081309.log)

**Comment by aws-kinesis-video** [comment]
What is the application you are running? What region are you in? By default sample applications are using us-west-2 as endpoint, if you have high network latency against us-west-2 endpoint, it is possible to timeout the operation and fail the createStream.

**Comment by zhiyua-git** [comment]
What is the application you are running? What region are you in? By default sample applications are using us-west-2 as endpoint, if you have high network latency against us-west-2 endpoint, it is possible to timeout the operation and fail the createStream.

**Comment by jiangxiaorong** [comment]
@zhiyua-git I develop my producer application base on test sample code under kinesis-video-producer. My camera is set up in China.

**Comment by zhiyua-git** [comment]
You can try to set region as ap-northeast-1 or ap-southeast-2 to get lower latency.

**Comment by jiangxiaorong** [comment]
@zhiyua-git Thanks for your suggestion, actually when I set to ap-southeast-2 I also meet the same issue.

**Comment by zhiyua-git** [comment]
@jiangxiaorong Can you paste a test log with region set to ap-southeast-2? I saw some 2-second delays in the log when state machine is doing state transition and would like to double check if that latency is caused by cross-region access or other source.

**Comment by MushMal** [comment]
@jiangxiaorong do you have more information on the timeout?

**Comment by jiangxiaorong** [comment]
@MushMal thanks you. I think it's because my network is not stable, and add retry when create stream failed. now I can create stream. Thank you again.
