### ISSUE TITLE
Error - ./min-install-script: line 170: make: command not found cp: cannot stat 'libjsmn.a': No such file or directory

### ISSUE THREAD

**Issue by ylulloa** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#254]
I'm going over the step by step guide: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/install-instructions-windows-msys2.md

I can't pass step #5. Error:
./min-install-script: line 170: make: command not found cp: cannot stat 'libjsmn.a': No such file or directory

![image](https://user-images.githubusercontent.com/954941/63195639-2d7bb500-c041-11e9-952c-79a77c458e5c.png)

Running this as Admin in a Windows 10 Pro.

Any suggestion?

**Comment by zhiyua-git** [comment]
Can you double check if you are running ./min-install-script in mingw32 or mingw64 shell? You cannot run it from msys2 shell.

**Comment by ylulloa** [comment]
That was it! Thanks.

**Comment by hussamsayeed** [comment]
$ cd kinesis-video-native-build; ./min-install-script
bash: cd: kinesis-video-native-build: No such file or directory
./min-install-script: line 15: /home/Hussam: No such file or directory

this is the error raising while Building the Kinesis Video Streams Producer SDK using min-install-script.. Anyone please help me out!

**Comment by surekha3079** [comment]
smanda@VSC-WS216 MINGW64 /c/AWS/amazon-kinesis-video-streams-producer-sdk-cpp/build (master)
$ ./min-install-script
bash: ./min-install-script: No such file or directory
Could u pls suggest me..

**Comment by MushMal** [comment]
@surekha3079 please use the latest SDK commits. We have no longer scripts to run. Check out the readme in the root directory to get more info on how to build and get specifics on what prerequisites  to install for Windows.

Once you try and if you have further questions please cut a separate issue as this one is closed
