### ISSUE TITLE
KVS misinterprets video frame resolution

### ISSUE THREAD

**Issue by ecolgan** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#255]
For some rtsp streams, the kvs web client player misinterprets resolution and decoding fails.   On the source end, we generated dot files and mkv files for the stream in question and they all show the correct resolution of 1280x720.  However, the kvs client player claims it is 256 x 528 and so decoding fails entirely.   We can provide a stream and time on KVS that shows this issue.
[upload.zip](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/files/3522761/upload.zip)

**Comment by unicornss** [comment]
Hi @ecolgan 

Could you please clarify

> However, the kvs client player claims it is 256 x 528 and so decoding fails entirely. 

Are you seeing this during playback in the console? or downloading the ingested media fragments through the GetMedia API?

**Comment by ecolgan** [comment]
We are seeing this in the console.

**Comment by unicornss** [comment]
Could you please provide the screen shot from the console to see the details returned on the playback?

Also, can you use the KVS [HLS viewer](https://github.com/aws-samples/amazon-kinesis-video-streams-hls-viewer/blob/master/index.html ) to check the playback on this stream?
https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/hls-playback.html

If you are seeing an issue here, send us the log information (without credentials information) to  kinesis-video-support@amazon.com.

Thanks

**Comment by MixMasterMitch** [comment]
This issue is now resolved.
