### ISSUE TITLE
Could NOT find Log4cplus (missing: LOG4CPLUS_LIBRARIES LOG4CPLUS_INCLUDE_DIR) Log4cplus is not found. Only c producer will be built.

### ISSUE THREAD

**Issue by norbyn** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#257]
I'm reproducing the steps of the guide: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/install-instructions-windows-msys2.md but step #6 is giving me this error:

 Could NOT find Log4cplus (missing: LOG4CPLUS_LIBRARIES LOG4CPLUS_INCLUDE_DIR) Log4cplus is not found. Only c producer will be built.

![2019-08-22_1335](https://user-images.githubusercontent.com/15056974/63536606-f1819d80-c4e1-11e9-8df3-1050d8fa2be2.png)

Running this as Admin in a Windows 10 Enterprise.

Any suggestion?

**Comment by zhiyua-git** [comment]
Hi @norbyn ,

Can you double check if you are running ./min-install-script in mingw32 or mingw64 shell? You cannot run it from msys2 shell.

**Comment by norbyn** [comment]
@zhiyua-git I ran the wrong shell msys2.exe, thanks.

**Comment by BlueClouDragon** [comment]
I have same problem. I ran the command on mingw64 shell
but the same problem with @norbyn 
any solution?
