### ISSUE TITLE
Unable to find kvssink 

### ISSUE THREAD

**Issue by js1972** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#260]
I installed on MacOS using brew and then the mininstall script from the installation instructions. 
It seems that it didn’t build the gstreamer plugin. Or if it did it’s not in the directory your instructions say it should be: 
<YourSdkFolderPath>/kinesis-video-native-build/downloads/local/bin.

Is there some other location it gets put when using the mininstall script?

Using gst-inspect-1.0 kvssink can’t find it..?

**Comment by zhiyua-git** [comment]
It’s in kinesis-video-native-build.

**Comment by js1972** [comment]
you are right. Thanks. We need to update the doc...  ;-)
