### ISSUE TITLE
Streaming starts then stops after a while

### ISSUE THREAD

**Issue by ghost** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#265]
Hello there,

I am pretty new to AWS Kinesis. I am trying to setup a live video stream between a Raspberry Pi 3 B+ with a camera and Kinesis, through the C++ SDK.
I installed all the dependencies for this software (especially for RPi though the Ubuntu / RPi guide), I did add my Access Keys, AWS Region etc ... , but when I start the binary producer this is the only error that I got in the output: 

[ERROR][2019-09-11 13:34:04] Reporting stream error. Errored timecode: 4130000 Status: 1375731808

(This is not my entire output, if you need it I can post it)

On the AWS side, nothing appears on Kinesis.

What is this error about ?

Thanks you for your time.

**Comment by MushMal** [comment]
@TheDeathV2 the status codes are listed here: https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/producer-sdk-errors.html

Seems like the timecodes are not monotonic in your media pipeline. What's the software asset you are using and which version. Could you share more info with full logs?
