### ISSUE TITLE
Is there any way to implement Kinesis Video Stream in java without using KinesisVideoProducerJNI.dll file?

### ISSUE THREAD

**Issue by prakashraj007** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#266]

**Comment by MushMal** [comment]
@prakashraj007 the Kinesis Video Streams Service has public service APIs described here https://docs.aws.amazon.com/en_pv/kinesisvideostreams/latest/dg/API_Reference.html

Once can simply use the service APIs and send the KVS specific MKV packaged encoded media to the service. 

The SDK makes this simpler.

**Comment by prakashraj007** [comment]
@MushMal. Thanks for your reply. I could not find any SDK for java. Can you please share the SDK link to download.
Thanks in advance

**Comment by MushMal** [comment]
@prakashraj007 we have https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java which is Java code that still has JNI interface to this source. Alternatively, as I mentioned, you could use the service API directly using any client, including AWS SDK.

**Comment by prakashraj007** [comment]
sorry, i can't understand what you mean "Service API".

**Comment by MushMal** [comment]
Kinesis Video Stream is a service with well documented service-side API. A developer who has her own HTTP client, can use it directly against the backend services.

**Comment by MushMal** [comment]
Closing for now. Please open a separate issue if needed
