### ISSUE TITLE
Can sample program send a 1920x1080 video by Camera V2?

### ISSUE THREAD

**Issue by shiopon01** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#27]
Hello,

I want to send a 1920x1080 video using Raspberry Pi 3 and Raspberry Pi Camera V2.

I have been able to successfully run kinesis_video_gstreamer_sample_app using Rasp Pi 3 and Camera V2.
However, In the preview of Kinesis video stream it is displayed 1280x720.

Is it possible to send 1920x1080 video by  Camera V2?

**Comment by MushMal** [comment]
@shiopon01 the existing demo/sample app is utilizing the software encoder which will not scale to 1080p. We will be updating the sample soon to utilize the hardware encoder which will. Stay tuned

**Comment by shiopon01** [comment]
I expect to be able to use 1080p.

Thank you for the reply.
Close the issue.
