### ISSUE TITLE
kinesis_video_gstreamer_audio_video_sample_app gets stuck 

### ISSUE THREAD

**Issue by mistersingh179** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#270]
I am running this command:

`GST_DEBUG=4 AWS_ACCESS_KEY_ID=xx AWS_SECRET_ACCESS_KEY=yy AWS_KVS_AUDIO_DEVICE=hw:1,0 ./kinesis_video_gstreamer_audio_video_sample_app test`

And it gets stuck with the last message being:
> Setting video_encode state from Idle to Executing

I do see these 2 warn messages
> audiosrc gstaudiosrc.c:197:audioringbuffer_thread_func:<audiosrc> failed to set thread priority
>audio-resampler audio-resampler.c:274:convert_taps_gint16_c: can't find exact taps

Also I can confirm that running the sample app which records just video, works fine - `kinesis_video_gstreamer_sample_app`

I can also confirm that i do have the audio recording device at hw:1,0 by doing
```
arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: Device [USB PnP Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
```

I can also confirm that the microphone works by recording and playing the audio with command:
```
arecord -D plughw:1,0 -d 3 test.wav
```

Also when i run `gst-device-monitor-1.0` it doesnt detect the audio recording device. Here is its output

```
gst-device-monitor-1.0
Probing devices...


Device found:

	name  : mmal service 16.1
	class : Video/Source
	caps  : video/x-raw, format=(string)YUY2, width=(int)[ 32, 3280, 2 ], height=(int)[ 32, 2464, 2 ], framerate=(fraction)[ 1/1, 90/1 ];
	        video/x-raw, format=(string)UYVY, width=(int)[ 32, 3280, 2 ], height=(int)[ 32, 2464, 2 ], framerate=(fraction)[ 1/1, 90/1 ];
	        video/x-raw, format=(string)I420, width=(int)[ 32, 3280, 2 ], height=(int)[ 32, 2464, 2 ], framerate=(fraction)[ 1/1, 90/1 ];
	        video/x-raw, format=(string)YV12, width=(int)[ 32, 3280, 2 ], height=(int)[ 32, 2464, 2 ], framerate=(fraction)[ 1/1, 90/1 ];
	        image/jpeg, width=(int)[ 32, 3280, 2 ], height=(int)[ 32, 2464, 2 ], framerate=(fraction)[ 1/1, 90/1 ];
	        image/jpeg, width=(int)[ 32, 3280, 2 ], height=(int)[ 32, 2464, 2 ], framerate=(fraction)[ 1/1, 90/1 ];
	        video/x-raw, format=(string)BGRx, width=(int)[ 32, 3280, 2 ], height=(int)[ 32, 2464, 2 ], framerate=(fraction)[ 1/1, 90/1 ];
	        video/x-raw, format=(string)BGR, width=(int)[ 32, 3280, 2 ], height=(int)[ 32, 2464, 2 ], framerate=(fraction)[ 1/1, 90/1 ];
	        video/x-raw, format=(string)RGB, width=(int)[ 32, 3280, 2 ], height=(int)[ 32, 2464, 2 ], framerate=(fraction)[ 1/1, 90/1 ];
	        video/x-raw, format=(string)NV21, width=(int)[ 32, 3280, 2 ], height=(int)[ 32, 2464, 2 ], framerate=(fraction)[ 1/1, 90/1 ];
	        video/x-raw, format=(string)NV12, width=(int)[ 32, 3280, 2 ], height=(int)[ 32, 2464, 2 ], framerate=(fraction)[ 1/1, 90/1 ];
	        video/x-raw, format=(string)YVYU, width=(int)[ 32, 3280, 2 ], height=(int)[ 32, 2464, 2 ], framerate=(fraction)[ 1/1, 90/1 ];
	        video/x-h264, stream-format=(string)byte-stream, alignment=(string)au, width=(int)[ 32, 3280, 2 ], height=(int)[ 32, 2464, 2 ], framerate=(fraction)[ 1/1, 90/1 ];
	properties:
		udev-probed = true
		device.bus_path = /sys/devices/virtual/video4linux/video0
		sysfs.path = /sys/devices/virtual/video4linux/video0
		device.subsystem = video4linux
		device.product.name = "mmal\ service\ 16.1"
		device.capabilities = :capture:video_overlay:
		device.api = v4l2
		device.path = /dev/video0
		v4l2.device.driver = "bm2835\ mmal"
		v4l2.device.card = "mmal\ service\ 16.1"
		v4l2.device.bus_info = platform:bcm2835-v4l2
		v4l2.device.version = 267074 (0x00041342)
		v4l2.device.capabilities = 2233466885 (0x85200005)
		v4l2.device.device_caps = 85983237 (0x05200005)
	gst-launch-1.0 v4l2src ! ...
```

I am using Raspian Buster.

Attached are the logs.
[kinesis_audio_video_sample_app_logs.txt](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/files/3687876/kinesis_audio_video_sample_app_logs.txt)

**Comment by chehefen** [comment]
can you try export AWS_KVS_VIDEO_DEVICE="/dev/video0" too?

**Comment by mistersingh179** [comment]
@chehefen same results. it gets stuck at 

> Setting video_encode state from Idle to Executing

You have asked me to set the video device variable. But i think the issue is with the audio device because:
1. video sample app works fine.
2. gst-device-monitor-1.0 does not see any audio device, even though arecord -l shows it
3. logs have audio warnings

warn messages from the logs:

> 0:00:01.441722980  1308  0x1fcacf0 WARN         audio-resampler audio-resampler.c:274:convert_taps_gint16_c: can't find exact taps
> 0:00:01.438756888  1308 0xa0602830 WARN                audiosrc gstaudiosrc.c:197:audioringbuffer_thread_func:<audiosrc> failed to set thread priority

**Comment by chehefen** [comment]
can you try running this command?
```
gst-launch-1.0 -v v4l2src ! videoconvert ! video/x-raw,format=I420 ! omxh264enc periodicty-idr=45 inline-header=FALSE ! h264parse ! video/x-h264,stream-format=avc,alignment=au ! queue ! matroskamux name=mux ! fakesink name=sink silent=FALSE alsasrc device=hw:1,0 ! avenc_aac ! aacparse ! audio/mpeg,stream-format=raw ! queue ! mux.
```

**Comment by mistersingh179** [comment]
@chehefen i get this:

```
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
ERROR: from element /GstPipeline:pipeline0/GstAlsaSrc:alsasrc0: Internal data stream error.
Additional debug info:
gstbasesrc.c(3055): gst_base_src_loop (): /GstPipeline:pipeline0/GstAlsaSrc:alsasrc0:
streaming stopped, reason not-negotiated (-4)
ERROR: pipeline doesn't want to preroll.
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...
```

**Comment by mistersingh179** [comment]
@chehefen do you have any ideas/hints I could pursue?

**Comment by mistersingh179** [comment]
I was able to resolve this issue by replacing the microphone/camera setup I had with a Logitech C920e Webcam. This indicates that perhaps there is a compatibility issue with the old microphone I was using. 

Hopefully this helps someone else in the future.
