### ISSUE TITLE
Timecodes are not monotonically increasing?

### ISSUE THREAD

**Issue by TheDeathV2** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#272]
Hello,
I am a new user of AWS, and I am trying to make a personal project using Raspberry Pi and cloud. In this project I stream my Pi Camera to Kinesis Video Stream.

At the begin of my project, I had this error status when I did start streaming to kinesis : 0x52000060

Which means "Timecodes are not monotonically increasing", but after a while of trying to debug this sdk, it had been fix without doing anything ...

( During 1 month, the stream did work correctly )
And now this error is back, and I don't know how to handle it.

Thanks for your help, or if you have anything that can help me, I'll take it :)
Best regards.

**Comment by chehefen** [comment]
0x52000060 means the timestamp of your key frames are not monotonically increasing. you can export DEBUG_DUMP_FRAME_INFO=TRUE to see the frame timestamps.

**Comment by MushMal** [comment]
@TheDeathV2 do you still have this issue?

**Comment by disa6302** [comment]
Closing this issue for now. Feel free to reopen/create a new issue in the future.
