### ISSUE TITLE
The Cmakefile does not support make install

### ISSUE THREAD

**Issue by ek9852** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#280]
The cmakefile.txt in kinesis-video-native-build does not written correctly, and missing install.
So make install will not work in kinesis-video-native-build  folder. and it also does not have a find_package(AWS_KINESISI_VIDEO) function provided for applications.
So building an application to support that  library requires some hard code path to the library.
And making build integration into the build system such as Yocto/Buildroot much more difficult.

**Comment by unicornss** [comment]
Hi @ek9852 

> find_package(AWS_KINESISI_VIDEO) function provided for applications

We have plans to make CMakelists work modular (along with external dependencies) and include target export.
