### ISSUE TITLE
Stream Error Status 1375731837

### ISSUE THREAD

**Issue by Xiaoron** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#284]
Hi, I meet a stream error, the error code is 1375731837, can you tell me the meaning of the error code?
Below is log:
streamErrorReportHandler(51): Reproting stream error. Errored time code:15725092270720000, status 1375731837

**Comment by unicornss** [comment]
Hi @Xiaoron 

1375731837 corresponds to the status code 0x5200007d .

0x5200007d | STATUS_ACK_ERR_FRAMES_MISSING_FOR_TRACK | Frames missing for a track.

Ref: https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/producer-sdk-errors.html 

Could you tell us more about your streaming setup and the sample you are using to ingest media into KVS cloud?
