### ISSUE TITLE
Error 2

### ISSUE THREAD

**Issue by weizsw** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#287]
after installed all build tools and run ./min-install-script
received:
[ 68%] Linking C shared library libcproducer.dylib
[ 68%] Built target cproducer
make: *** [all] Error 2

**Comment by unicornss** [comment]
Can you please share the Operating System version you are using to build the SDK and detailed build log?

**Comment by Nerdyvedi** [comment]
@weizsw . Getting the same error on mac os: 10.15.7
How did you fix it?
