### ISSUE TITLE
How to build and run KVS on MIPS?

### ISSUE THREAD

**Issue by chenek** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#296]
We have use MIPS (mipsel) running little endian application and would like to run KVS example. Can someone show steps to build and run KVS example on our MIPS platform.

**Comment by MushMal** [comment]
HI @chenek 

The SDK should be possible to compile for MIPS. The main issue would be to ensure your platform supports unaligned memory access.

You can try to cross compile it for your platform following the steps in install-script. We are not currently supporting cross-compile scripts.

Please open another issue if you need more direct help with a particular issue
