### ISSUE TITLE
MIPS platform test sample program running error   (mipsel running little endian)

### ISSUE THREAD

**Issue by henryChmn** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#303]
We got error when run kvsVideoOnlyStreamingSample to test video stream,
the error message as below:,
![test_log](https://user-images.githubusercontent.com/58592084/70316519-dc453a80-1856-11ea-8b0e-46f9d369f296.png)
please advise,
thanks.

**Comment by MushMal** [comment]
@henryChmn you are attempting to initialize around 13.4MB or memory but this seems to fail. How much available RAM does your device have?

**Comment by henryChmn** [comment]
@MushMal We can run into next state as below,
but we fail to send video to KVS and got failed  as below,
![image](https://user-images.githubusercontent.com/58592084/70430516-ef097a80-1ab5-11ea-969f-78c594c153a3.png)

Ubuntu can send video stream to KVS:
![image](https://user-images.githubusercontent.com/58592084/70430560-09dbef00-1ab6-11ea-9a5c-6f6c7d0fea37.png)

thanks.

**Comment by MushMal** [comment]
@henryChmn From the two images it states explicitly why it fails

1) It complains about the ca cert missing. Please follow the explicit Readme instructions on how to install the ca certificate. https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/install-instructions-linux.md#install-the-certificate-in-the-operating-system-certificate-store
2) It fails with error 0x00000009 which is if you look it up - can't open a file. This is likely when you are trying to run the video only demo that tries to load the frame files from the disk and send. make sure you run it from the native-build directory.

Resolving the issue. Please feel free to reopen if you need more help
