### ISSUE TITLE
is possible to store kinesis video stream in S3 or somewhere? as like chunk or some other technique...please share

### ISSUE THREAD

**Issue by hameedriswan7** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#304]

**Comment by zhiyua-git** [comment]
Hi @hameedriswan7 ,

With a configurable data retention of the KVS stream, your video data will be store during the retention window. You can use GetMedia to retrieve the video through https://github.com/aws/amazon-kinesis-video-streams-parser-library#kinesisvideoexample

If you still want to store the file in S3, you can do it with the file.

**Comment by MushMal** [comment]
Thanks @zhiyua-git for the info. Resolving this for now.
