### ISSUE TITLE
RTMP Support not available

### ISSUE THREAD

**Issue by philross88** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#307]
The RMTP support is not built into docker image or even if it's compiled with the instructions using install script. Please build the rtmps plugins as well.

/gst-launch-1.0 -v rtmpsrc
ERROR: pipeline could not be constructed: no element "rtmpsrc".

**Comment by MushMal** [comment]
@philross88 thanks for reporting. This belongs to plugins-bad. We can evaluate whether to include it in the SDK itself or not. Meanwhile, you can simply pull down the plugin directly and use it - GStreamer and it's plugins are not really part of the SDK.

**Comment by philross88** [comment]
Thanks @MushMal.
Can you please explain with instructions on how to pull down the plugins-bad in the docker image?
Yum in the docker is broken and I don't see an option to pull down the plugins-bad.

Any details would be great.

**Comment by MushMal** [comment]
Resolving as we have no immediate plans on supporting RTMP in the KVS SDK. RTMP can still be supported via GStreamer
