### ISSUE TITLE
configure: error: C++ preprocessor "/lib/cpp" fails sanity check

### ISSUE THREAD

**Issue by zachahuy** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#31]
The README needs to update to require g++ to be installed.

**Comment by unicornss** [comment]
Hi Zachahuy,

Are you referring to 

Install g++: sudo apt-get install g++

g++ --version g++ (Ubuntu 7.2.0-8ubuntu3) 7.2.0 Copyright (C) 2017 Free Software Foundation, Inc. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


Thanks
-SS

**Comment by unicornss** [comment]
Closing this as it has been captured in the Readme. Will re-open if required.
