### ISSUE TITLE
Openssl version 1.1.0f fails with latest Perl 5

### ISSUE THREAD

**Issue by diogoviannaaraujo** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#320]
Hi,

Im using latest Fedora version.

When building the SDK Openssl build fails at configure:17, importing Glob that way was deprecated on late Perl 5 updates.

Updating install script to Openssl 1.1.1d solved this issue

**Comment by zhiyua-git** [comment]
Hi @diogoviannaaraujo ,

Thanks for reporting the issue, we will be updating it soon.

**Comment by disa6302** [comment]
Hello @diogoviannaaraujo , 

I have just pushed a change with the update. Thank you for bringing it up. Feel free to reach out with any questions you might have.
