### ISSUE TITLE
(WARNING: erroneous pipeline: no element "kvssink") ubuntu 18

### ISSUE THREAD

**Issue by Mano009das** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#323]
i am having this issue i have tired solutions to solve it with no success. is it a laptop driver issue?

**Comment by zhiyua-git** [comment]
Hi @Mano009das ,

Can you try setting environment variables as below?
export GST_PLUGIN_PATH=/path/to/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-native-build
export LD_LIBRARY_PATH=/path/to/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-native-build:$LD_LIBRARY_PATH

**Comment by Mano009das** [comment]
thank you for the response .

yes i just did then shall i run  this code? after i did this it gave me the same error. or do i have to install something else.

Ubuntu:

gst-launch-1.0 -v v4l2src device=/dev/video0 ! videoconvert ! video/x-raw,width=640,height=480,framerate=30/1,format=I420 ! x264enc  bframes=0 key-int-max=45 bitrate=500 tune=zerolatency ! h264parse ! video/x-h264,stream-format=avc,alignment=au,profile=baseline ! kvssink name=sink stream-name="my-stream-name" access-key="YourAccessKey" secret-key="YourSecretKey" alsasrc device=hw:1,0 ! audioconvert ! avenc_aac ! queue ! sink.

**Comment by zhiyua-git** [comment]
Hi @Mano009das ,

Can you provide the output of “ls /path/to/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-native-build“? Want to check if you have all the files built. Thanks.

**Comment by Mano009das** [comment]
ok sure give me a min

**Comment by Mano009das** [comment]
~# ls /path/to/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-native-build
ls: cannot access '/path/to/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-native-build': No such file or directory

**Comment by Mano009das** [comment]
may be this is the issue???

**Comment by zhiyua-git** [comment]
Hmm, you need to put your actual directory path in the environment variable, say if your file is in /home/username/workspace/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-native-build then 

export GST_PLUGIN_PATH= /home/username/workspace/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-native-build
export LD_LIBRARY_PATH= /home/username/workspace/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-native-build:$LD_LIBRARY_PATH

**Comment by Mano009das** [comment]
![Screenshot from 2020-01-09 12-28-08](https://user-images.githubusercontent.com/26167304/72045378-ed60eb80-32db-11ea-88f5-db73b4fad107.png)

**Comment by Mano009das** [comment]
okay thank let me try and get back to u

**Comment by Mano009das** [comment]
![Screenshot from 2020-01-09 12-44-50](https://user-images.githubusercontent.com/26167304/72046300-1da98980-32de-11ea-9fb4-d2deeb4ff5c9.png)

**Comment by Mano009das** [comment]
i am getting this output :(

**Comment by zhiyua-git** [comment]
As you are already in kinesis-video-native-build directory, you can do it through
export GST_PLUGIN_PATH=$PWD
export LD_LIBRARY_PATH= $PWD:$LD_LIBRARY_PATH

The path "/root/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-native-build" you provided is wrong.

**Comment by Mano009das** [comment]
thank you for the solution it was a hardware compatibility issue I tired in raspberry pi and it worked fine :)
