### ISSUE TITLE
Illegal instruction in getSamplingFreqAndChannelFromAacCpd function under MIPS platform

### ISSUE THREAD

**Issue by henryChmn** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#332]
We had a problem when trying to run KvsAacAudioVideoStreamingSample example code under our camera with MIPS platform, Illegal instruction as below,
seems relative the parameter assign address as below,
![image](https://user-images.githubusercontent.com/58592084/73508443-f2b2e100-4416-11ea-9c7e-f57184fc8fbb.png)

Illegal instruction:
*pSamplingFrequency = gMkvAACSamplingFrequencies[samplingRateIdx];

the correct address as below,
![image](https://user-images.githubusercontent.com/58592084/73508466-02cac080-4417-11ea-9b68-1a01ddf69227.png)

The sample code run under Ubuntu are well.
![image](https://user-images.githubusercontent.com/58592084/73509083-ecbdff80-4418-11ea-9bd8-f9f4b9f6a8d7.png)

also I check the address assign in Ubuntu as below, 
![image](https://user-images.githubusercontent.com/58592084/73510705-ff870300-441d-11ea-9996-c8e92553971d.png)

the address assign in MIPS platform as below, 
![image](https://user-images.githubusercontent.com/58592084/73510752-3c52fa00-441e-11ea-8c10-0042556d9c08.png)

**Comment by henryChmn** [comment]
fixed by modify mkvgenAdaptCodecPrivateData function call

**Comment by MushMal** [comment]
@henryChmn could you please give us a little more information? Is this still an issue on MIPS?

**Comment by henryChmn** [comment]
@MushMal  It's an issue on MIPS for current example code on the git.
We fixed it by modify PIC library function call to access the parameter.

it's seems relative memory allocate as below, 
allocationSize = SIZEOF(KinesisVideoStream) + tagsSize + trackInfoSize + MKV_SEGMENT_UUID_LEN;
pKinesisVideoStream = (PKinesisVideoStream) MEMCALLOC(1, allocationSize);

**Comment by MushMal** [comment]
@henryChmn thanks for the info but I am still unsure how this breaks as both of the locations you've provided would work just fine. Are you fixing up for alignment memory/non-tight packed build?

**Comment by henryChmn** [comment]
@MushMal  it's working in Ubuntu but not MIPS. 
Inside the function call can't give the parameter value, only outside the function call could do that.
I'm not fixed alignment memory/non-tight packed build just avoid assign value this parameter inside the function call.

**Comment by MushMal** [comment]
@henryChmn thanks for bearing with me here. The inspection of the code looks good - we do provide a valid pointer to DOUBLE which gets filled by the function. Perhaps we see an issue with the compiler handling double out of alignment.
