### ISSUE TITLE
Fix documentation for frame_timecodes

### ISSUE THREAD

**Issue by sharadrj** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#341]
Documentation for frame_timecodes doesn't look right. (https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/how-data.html#how-data-header-streamdefinition)
 
It says "If true, Kinesis Video Streams stamps the frames when they are received. If false, Kinesis Video Streams uses the decode time of the received frames." However, looking at the code, it seems like the reverse. 

The documentation should probably say something to this effect: 
"if true, Kinesis Video Streams uses the decode time (dts and pts received from encoder) of the received frames. If false, Kinesis Video Streams stamps the frames when they are received with system-generated time values."

**Comment by disa6302** [comment]
Closing. Tagged this in issue #423 to keep all documentation related items at one place

**Comment by hassanctech** [comment]
Related issues were all closed but this was never fixed.  Re-opening.

**Comment by sirknightj** [comment]
Tracking internally.
