### ISSUE TITLE
Outdated OpenSSL

### ISSUE THREAD

**Issue by chmod750** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#355]
Hello,
The OpenSSL version used is 1_1_0f. Would it be possible to upgrade it to 1.1.1d?
Thanks

**Comment by disa6302** [comment]
Hello @chmod750 ,

The install-script will automatically install openssl1.1.1d for you.

**Comment by chmod750** [comment]
> Hello @chmod750 ,
> 
> The install-script will automatically install openssl1.1.1d for you.

THanks for your reply. I noticed there is outdated usage in installation script. For example in kinesis-video-native-build/windows-install.bat:
`if not exist "openssl-OpenSSL_1_1_0f" (
    echo "Openssl doesn't exist, installing into %CURRENTDIR%"
    if not exist "openssl-1.1.0f.zip" (
        powershell -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest https://github.com/openssl/openssl/archive/OpenSSL_1_1_0f.zip -OutFile openssl-1.1.0f.zip"
    )`

**Comment by disa6302** [comment]
Ah! Understood. Good catch. Must have missed updating this while updating install-script with openssl1.1.1d. Will have a patch up soon for this. Thank you for pointing it out!
