### ISSUE TITLE
Execution environment 

### ISSUE THREAD

**Issue by francoisdutoit** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#37]
Hi,

I'm getting the following build error in Eclipse on Ubuntu 17.10

"Build path specifies execution environment JavaSE-1.7. There are no JREs installed in the workspace that are strictly compatible with this environment."  	kinesisvideo-java-demo

As per Install Steps for Ubuntu 17.x I installed openjdk-8-jdk

How can I resolve this issue?

Thanks!

**Comment by unicornss** [comment]
Can you please create the issue in the Java SDK https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java  as that would be a more appropriate environment for your question.

**Comment by francoisdutoit** [comment]
Thanks...will do :)
