### ISSUE TITLE
Is it possible to use Python to send Video to Kinesis 

### ISSUE THREAD

**Issue by ishangupta3** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#373]
I would like to use python to send my video stream to kinesis video stream - is that possible?

**Comment by MushMal** [comment]
@ishangupta3 KVS SDK doesn't have a support for Python yet. This is something that we are looking at supporting sometime in the future based on the customer demand.

This said, it's possible to create Python bindings on top of the current assets.

Resolving for now
