### ISSUE TITLE
IS_RETRIABLE_ERROR and IS_RECOVERABLE_ERROR

### ISSUE THREAD

**Issue by ib1368** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#393]
Hello,

I am creating this issue for clarification.

In https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/3ae1b0224b8b3e8a6aa32b5dba8b223f158b36c0/kinesis-video-gst-demo/kinesis_video_gstreamer_audio_video_sample_app.cpp#L288 we stop the pipeline, if the error is not recoverable and retriable.

- So as library user we shouldn't do any further step if it is retriable or recoverable? It automatically ignore the error and continues?
- What is the difference between being retriable and being recoverable?
- Why aren't some other errors recoverable or retriable?

**Comment by disa6302** [comment]
Closing this issue. Feel free to open an issue with any other questions you might have!
