### ISSUE TITLE
where is ./install_kinesis_video_demo.sh ?

### ISSUE THREAD

**Issue by anandpanchal** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#4]
hi,

please help me locate ./install_kinesis_video_demo.sh file.

thanks
anand

**Comment by imyoungyang** [comment]
Hi.. 
any response for the step 41  ./install_kinesis_video_demo.sh at the following file?

https://s3-us-west-2.amazonaws.com/kinesis-video-streaming/kinesis-video-raspberry-pi-getting-started.pdf

**Comment by MushMal** [comment]
Apologies for the delay. We will be publishing an update shortly which will make the install-script work for PI too. The gstreamer demp app will be updated to work on PI.

**Comment by MushMal** [comment]
The latest commit updates the build scripts and the instructions for the Raspberry PI
