### ISSUE TITLE
Cmake libopenssl failed

### ISSUE THREAD

**Issue by jasdeepsd** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#411]
When running the cmake i get this issue:
Error 1
make[1]: * [CMakeFiles/Makefile2:73: CMakeFiles/project_libopenssl.dir/all] Error 2
make: * [Makefile:84: all] Error 2
CMake Error at CMake/Utilities.cmake:55 (message):
  CMake step for libopenssl failed: 2
Call Stack (most recent call first):
  CMakeLists.txt:69 (build_dependency)

I couldn't seem to find anything online for this issue.

**Comment by disa6302** [comment]
@jasdeepsd ,

There is not much information in whatever output you posted. Can you post the rest of the lines before this?
That will have some information on the issue.

**Comment by jasdeepsd** [comment]
here's the full error
![image](https://user-images.githubusercontent.com/42454067/79612245-51a8fd80-80ca-11ea-895a-0c33a0d1718c.png)
