### ISSUE TITLE
Issue with gstreamer sample app

### ISSUE THREAD

**Issue by jasdeepsd** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#412]
I managed to build everything but I get the issue:
-bash: ./kinesis_video_gstreamer_sample_app: No such file or directory

is there a step that I missed?

**Comment by disa6302** [comment]
Where are you running it from?

**Comment by jasdeepsd** [comment]
I installed it a raspberry pi

**Comment by disa6302** [comment]
Please run it from the build directory

Also, make sure you run cmake with -DBUILD_GSTREAMER_PLUGIN=ON option

**Comment by jasdeepsd** [comment]
Couldnt find the executable and ran make with that option, but it didn't help.

**Comment by disa6302** [comment]
@jasdeepsd ,

Please run cmake with the option and not make

Also, for reference, please check the github readme. It clearly mentions all the flags you can use with cmake. Thanks!

**Comment by jasdeepsd** [comment]
That was my bad, yes i ran it with make. GUess ill try the other options

**Comment by disa6302** [comment]
Also, make sure to check if cmake completes successfully. Let us know if you have any other questions!
