### ISSUE TITLE
Build fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by muhammadAgfian96** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#421]
i m trying sending data to kinesis and install this sdk, but get this when running `cmake`:

[ 66%] Performing build step for 'project_log4cplus'
/home/aiti/Downloads/compressed/amazon-kinesis-video-streams-producer-sdk-cpp-master/open-source/liblog4cplus/build/src/project_log4cplus/missing: line 81: aclocal-1.16: command not found
WARNING: 'aclocal-1.16' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
Makefile:934: recipe for target 'aclocal.m4' failed
make[3]: *** [aclocal.m4] Error 127
CMakeFiles/project_log4cplus.dir/build.make:111: recipe for target 'build/src/project_log4cplus-stamp/project_log4cplus-build' failed
make[2]: *** [build/src/project_log4cplus-stamp/project_log4cplus-build] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/project_log4cplus.dir/all' failed
make[1]: *** [CMakeFiles/project_log4cplus.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
CMake Error at CMake/Utilities.cmake:55 (message):
  CMake step for liblog4cplus failed: 2
Call Stack (most recent call first):
  CMakeLists.txt:77 (build_dependency)

-- Configuring incomplete, errors occurred!
See also "/home/aiti/Downloads/compressed/amazon-kinesis-video-streams-producer-sdk-cpp-master/build/CMakeFiles/CMakeOutput.log".

is there anything i missed?

**Comment by MushMal** [comment]
The log shows aclocal is missing. Please install the build prerequisites like the compiler and the build tools. Resolving
