### ISSUE TITLE
Missing documentation in readme

### ISSUE THREAD

**Issue by sharadrj** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#423]
The install guides that have been removed recently contained useful documentation sections that should make its way to the readme. 

Example: 
- [x] Using Docker
- [x] Running the GStreamer RTSP demo application
- [x] Running C++ Unit tests
- [x] Enabling verbose logs
- [x] How to configure logging for producer SDK sample applications.
- [x] Troubleshooting
- [x] Open source dependencies
- [x] Update AWS documentation to reflect the current changes

https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/branch-2018-08-30_17-14-31/install-instructions-macos.md#running-the-gstreamer-webcam-demo-application

**Comment by disa6302** [comment]
AWS Documentation updated. Closing.
