### ISSUE TITLE
Missing docker examples as per documentation

### ISSUE THREAD

**Issue by kennycoder** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#444]
I'm trying to test RTSP docker demo application as per documentation here:
https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/examples-rtsp.html
But Dockerfile and relevant folder is not available.

Thanks in advance.

**Comment by disa6302** [comment]
@kennycoder , 

We are in the process of moving dockerfile to this repo: https://github.com/aws-samples/amazon-kinesis-video-streams-demos

We are also in the process of updating the docs to reflect the same.

**Comment by kennycoder** [comment]
Thank you for the info. I'll close the issue.
