### ISSUE TITLE
No such element or plugin 'kvssink'

### ISSUE THREAD

**Issue by SmitaAhinave** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#448]
System Information:
          Distributor ID:	Ubuntu
          Description:	Ubuntu 18.04.4 LTS
          Release:	18.04

I'm integrating AWS KVS refering CPP library and following exact same steps mentioned.
Build and everything else was successful.
Please find screenshot attached for more detail.

![kvsErr](https://user-images.githubusercontent.com/13129568/81830423-a9b41200-9559-11ea-9084-de032124e2dd.png)

Still I'm getting **No such element or plugin 'kvssink' error.**
I also tried solving this with AWS support but still no luck. They have recommended to post this issue here.

Any help is appreciated.

**Comment by Sean-Der** [comment]
Hey @SmitaAhinave 

The plugin may be blacklisted, can you deleted your GStreamer plugin registry, it is in ~/.cache

**Comment by Sean-Der** [comment]
I also noticed you have copied the libraries into the build folder, that probably will not work. Can your set your LD_LIBRARY_PATH instead.

**Comment by SmitaAhinave** [comment]
> I also noticed you have copied the libraries into the build folder, that probably will not work. Can your set your LD_LIBRARY_PATH instead.

Can you please help me to understand why we need it... it's not mentioned here https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp

**Comment by MushMal** [comment]
@SmitaAhinave it does look odd that GStreamer is unable to load the plugin given the path. Could you perhaps append the path to the kvssink library to the LD_LIBRARY_PATH and to GST_PLUGIN_PATH and check. The GStreamer questions are better answered in GStreamer forums in general.

We have had few customers who set the path from a command line like so: https://stackoverflow.com/questions/2120444/gstreamer-plugin-search-path

**Comment by Sean-Der** [comment]
@SmitaAhinave I can confirm the same error.

First do `export LD_LIBRARY_PATH=`pwd`/open-source/local/lib` (will update the docs)
Then do `rm -rf ~/.cache/gstreamer-1.0` (clear the cache, kvssink will be disabled since it failed to load the first time)

**Comment by SmitaAhinave** [comment]
> @SmitaAhinave I can confirm the same error.
> 
> First do `` export LD_LIBRARY_PATH=`pwd`/open-source/local/lib `` (will update the docs)
> Then do `rm -rf ~/.cache/gstreamer-1.0` (clear the cache, kvssink will be disabled since it failed to load the first time)

Worked after setting LD_LIBRARY_PATH

Thank you so much for the help

**Comment by Sean-Der** [comment]
Thanks for using KVS :)

I am going to update the docs now to mention this. I am doing the final touches today.
