### ISSUE TITLE
install-script missing after build

### ISSUE THREAD

**Issue by ArifSohaib** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#456]
I am following the Raspberry Pi documentation from https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/producersdk-cpp-rpi.html but it looks like the "insteall-script" file which is supposed to be in the build folder according to the docs is missing.
Edit: I tried the master version, 3.0 version and 2.1 version

**Comment by disa6302** [comment]
Please follow the steps in the README.md. We have moved to cmake now. The docs will be updated soon. Thanks!

**Comment by enbochen** [comment]
This piece of information is still outdated in the doc
