### ISSUE TITLE
Tag signal link channel

### ISSUE THREAD

**Issue by huyhoangk50** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#464]
How can I add a new tag the signaling channel with c++ code like I added the "kvs" tag manually in the  
[image](https://drive.google.com/file/d/10J1wPL6oMPG2j2z_-5Y4xieRnVf4sB6O/view?usp=sharing). So that I can monitor this tag. Thank you

**Comment by MushMal** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h#L1112

**Comment by MushMal** [comment]
Resolving. Please re-open/cut a new one if you need further info
