### ISSUE TITLE
Cannot view the streamed MP4 file in the console.

### ISSUE THREAD

**Issue by ravidetroit** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#467]
I have built the c++ kinesis video producer. And i can stream a mp4 file. However i cannot playback the media in the console. I get a no media found error.

**Comment by MushMal** [comment]
Please include more information on what the experience is? Are you seeing black screen? Are you using the same region? Can you include debug producer logs

**Comment by ravidetroit** [comment]
[kvs.log.zip](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/files/4697203/kvs.log.zip)

I get a no media found error.

**Comment by MushMal** [comment]
@ravidetroit looks like the file is uploaded just fine. If the file is "short" it will finish before you get the playback. Try to stream, go to the console. Make sure you select the same region. Select server-side timestamp. Select from some time past before the time you started streaming for the playback to pick up the fragments that langed.

**Comment by ravidetroit** [comment]
[output.zip](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/files/4697653/output.zip)

@MushMal, attached the output of get-inspect-1.0 kvssink. When i execute 
./build/kvs_gstreamer_file_uploader_sample /home/ubuntu/environment/samplevideos/60.mp4

 Failed to construct pipeline: no element "qtdemux"
[ERROR] kvs_gstreamer_file_uploader_sample: Failed to initialize gstreamer pipeline. Have you set GST_PLUGIN_PATH properly?

     For example: export GST_PLUGIN_PATH=<YourSdkFolderPath>/build:$GST_PLUGIN_PATH

echo $GST_PLUGIN_PATH
/home/ubuntu/environment/amazon-kinesis-video-streams-producer-sdk-cpp/build

**Comment by MushMal** [comment]
Seems that it's unable to find the plugins. Could you execute

```
export GST_PLUGIN_PATH=`pwd`/build
export LD_LIBRARY_PATH=`pwd`/open-source/local/lib
```

from the root directory to set the correct paths?

**Comment by ravidetroit** [comment]
echo $GST_PLUGIN_PATH
/home/ubuntu/environment/amazon-kinesis-video-streams-producer-sdk-cpp/build, the path variables are set
echo $LD_LIBRARY_PATH
/home/ubuntu/environment/amazon-kinesis-video-streams-producer-sdk-cpp/open-source/local/lib

**Comment by MushMal** [comment]
Looks correct. Seems that the demux plugin is missing for some reason.

**Comment by ravidetroit** [comment]
Is that a shared library, i can include that explicitly

**Comment by Sean-Der** [comment]
Hey @ravidetroit 

You also need to install the GStreamer 'good plugins'. If you are using homebrew it would be `brew install gst-plugins-good` and for Debian/Ubuntu it would be `apt-get install gstreamer1.0-plugins-good`

**Comment by ravidetroit** [comment]
I now get the following error. Building gstreamer pipeline
[ERROR] kvs_gstreamer_file_uploader_sample: Failed to construct pipeline: no element "h264parse"

**Comment by MushMal** [comment]
This is in bad plugins https://gstreamer.freedesktop.org/documentation/videoparsersbad/h264parse.html?gi-language=c

Try to install that one too 

`apt-get install gstreamer1.0-plugins-bad`

I am guessing that you already have the base plugins installed but give this a try. I think for file uploader this should be it - you wouldn't require plugins-ugly

**Comment by ravidetroit** [comment]
I installed gst-plugins-bad and the errors are now different

log4cplus:ERROR could not open file ./kvs_log_configuration
ERROR - Unable to create Rotating Credential provider. Error status: 0x9
[ERROR] kvs_gstreamer_file_uploader_sample: Unable to set the pipeline to the playing state.

**Comment by MushMal** [comment]
First issue is due to log4cpus config file not being there or the path not being there. Perhaps, copy  the config file from the samples to build directory

The second is complaining about the auth integration. Make sure you set the auth as described in https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/docs/linux.md

**Comment by chehefen** [comment]
This issue has been resolved after working with customer offline.
