### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by jlong29** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#483]
A note in the README.md regarding the necessary include directories to put in your project when doing native C/C++ with the gstreamer plugin would be appreciated. At the moment, I'm guessing a bit based upon the CMakeList.txt in the kinesis-video-gstreamer-plugin and the file kvs_prodcuer_plugin_rtsp_demo.cpp. As a start: what are the basic components of a Makefile/CMakeList.txt for your own project using the kvssink gstreamer element?

**Comment by disa6302** [comment]
@jlong29 , 

Thank you for the suggestion. We will look into this.
