### ISSUE TITLE
CMake Error "does not appear to contain CMakeLists.txt"

### ISSUE THREAD

**Issue by gcoop** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#5]
FYI:

Whilst executing `./kinesis-video-native-build/install-script` I got the following error `CMake Error: The source directory "/Users/Gavin/repos/thirdparty/amazon-kinesis-video-streams-producer-sdk-cpp" does not appear to contain CMakeLists.txt.`. To resolve I moved CMakeLists.txt from kinesis-video-native-build to root of repo. Updated the src paths in CMakeLists.txt to match new locations and reran the command to resolve the issue.

**Comment by MushMal** [comment]
I am wondering whether you executed ./install-script from within the kinesis-video-native-build directory?

**Comment by gcoop** [comment]
No I executed it from the repo root. That's probably why it couldn't locate `CMakeLists.txt`.

**Comment by enusbaum** [comment]
I'm having this issues on my rpi while following the tutorial at

https://s3-us-west-2.amazonaws.com/kinesis-video-streaming/kinesis-video-raspberry-pi-getting-started.pdf

**Comment by zhiyua-git** [comment]
Hi enusbaum,

Please change directory to kinesis-video-native-build and run install-script from there.

**cd kinesis-video-native-build; ./install-script**

We will also fix that on installation guide soon.

Thanks,
-ZH

**Comment by MushMal** [comment]
Apologies again. Please feel free to reach out for any question no matter how small or obvious those are.

**Comment by triggerx** [comment]
Guide is still not updated... what's the deal?

**Comment by hussamsayeed** [comment]
$ cd kinesis-video-native-build; ./min-install-script
bash: cd: kinesis-video-native-build: No such file or directory
./min-install-script: line 15: /home/Hussam: No such file or directory


this is the error raising while Building the Kinesis Video Streams Producer SDK using min-install-script.. Anyone please help me out!

**Comment by MushMal** [comment]
@hussamsayeed you need to navigate to the SDK directory in the terminal and then navigate down to the native build directory by calling `cd kinesis-video-native-build`

**Comment by hussamsayeed** [comment]
![Screenshot (240)](https://user-images.githubusercontent.com/46478199/65584328-5aa37780-df9e-11e9-8c2f-ab2049014919.png)
I already did that.[can see in Screenshot]

**Comment by zhiyua-git** [comment]
Your user name contains space. The script was not able to handle the path, can you replace **$KINESIS_VIDEO_ROOT** with **"$KINESIS_VIDEO_ROOT"** in these two places and retry? 

https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/kinesis-video-native-build/min-install-script#L15
https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/kinesis-video-native-build/min-install-script#L206

**Comment by hussamsayeed** [comment]
Should I replace that code with the code which is there in those links?

**Comment by hussamsayeed** [comment]
Hussam Sayeed@DESKTOP-6TJVREH MINGW64 ~/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-native-build
$ ./min-install-script
Setting up for KVS Producer SDK installation
Current working path cannot have space in it !

**Comment by zhiyua-git** [comment]
Hi @hussamsayeed ,

Seems mingw doesn't support space in the path. Can you either try to install your mingw into directory which contains **no space** in the path or use the **short (8.3) name** as mentioned [here](https://stackoverflow.com/questions/5999507/mingw-make-cant-handle-spaces-in-path)?

You can do **export KINESIS_VIDEO_ROOT="/Your/Updated/Path"** and rerun the min-install-script.

**Comment by hussamsayeed** [comment]
I changed the path and it works. thank you for the support @zhiyua-git 
![Screenshot (242)](https://user-images.githubusercontent.com/46478199/65683993-3c13ae00-e07c-11e9-86f4-b734fb9e3020.png)
![Screenshot (243)](https://user-images.githubusercontent.com/46478199/65683995-3cac4480-e07c-11e9-90fb-a7d2658b0cce.png)

but the problem is segmentation failed[attached].
I followed the this documentation [https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/install-instructions-windows-msys2.md] 

Can anyone please help me out!

**Comment by zhiyua-git** [comment]
@hussamsayeed , you need to put in your **actual** AccessKey/SecretKey in 
export AWS_ACCESS_KEY_ID=YOUR_ACCESS_KEY
export AWS_SECRET_ACCESS_KEY=YOUR_SECRET_ACCESS_KEY
to run it. 

Also make sure you have configured proper Kinesis Video Streams permission for the role of AccessKey/SecretKey you are going to use. It can be as simple as adding AmazonKinesisVideoStreamsFullAccess policy to your role. https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/how-iam.html

**Comment by hussamsayeed** [comment]
@zhiyua-git thank you so much for the suppport!
yeah i gave the actual access keys and also configured the permisiions.. still the same error!!!!!

**Comment by zhiyua-git** [comment]
@hussamsayeed  Can you provide the log for the failure? Thanks.

**Comment by hussamsayeed** [comment]
@zhiyua-git Yeah.. attached the log for the failure.
![Screenshot (245)](https://user-images.githubusercontent.com/46478199/65944755-0f7ede00-e450-11e9-93d9-3f1de7c02e1b.png)

**Comment by zhiyua-git** [comment]
@hussamsayeed , what command did you run? Sample app or gstreamer plugin kvs-sink? Can you provide log with export GST_DEBUG=4? Thanks.

**Comment by hussamsayeed** [comment]
@zhiyua-git I'm following this document [https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/install-instructions-windows-msys2.md]

So when running the sample app im getting the error.[gst-launch-1.0 ksvideosrc ! video/x-raw,width=640,height=480,framerate=30/1 ! videoconvert ! x264enc bframes=0 key-int-max=45 bitrate=512 tune=zerolatency ! video/x-h264,profile=baseline,stream-format=avc,alignment=au ! kvssink stream-name=stream-name access-key=YOUR_ACCESS_KEY secret-key=YOUR_SECRET_ACCESS_KEY_ID
] even after i've changed with my aws keys.

**Comment by zhiyua-git** [comment]
@hussamsayeed,  Can you provide log with **export GST_DEBUG=4**? Thanks.

**Comment by hussamsayeed** [comment]
@zhiyua-git [attached
![Screenshot (275)](https://user-images.githubusercontent.com/46478199/66186626-62e76b00-e6a0-11e9-9a63-a51b7ceeaa16.png)
![Screenshot (276)](https://user-images.githubusercontent.com/46478199/66186627-63800180-e6a0-11e9-89f3-05b3cb3f0319.png)

]

**Comment by chehefen** [comment]
can you copy libcproducer.dll and libproducer.dll to C:\msys64\mingw64\bin and copy libgstkvssink.dll to C:\msys64\mingw64\lib\gstreamer-1.0 and make sure you are not exporting GST_PLUGIN_PATH. Then try your pipeline again.

**Comment by hussamsayeed** [comment]
Thank you so much @zhiyua-git  @chehefen  for the support. I got the output in the kinesis streams!!
