### ISSUE TITLE
[BUG] Can't find install-script after make

### ISSUE THREAD

**Issue by Anshulkaaya** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#502]
mkdir -p amazon-kinesis-video-streams-producer-c/build; 
cd amazon-kinesis-video-streams-producer-c/build; 
cmake ..
make

After this step, can't find install-script after make. Please check snapshot
![Error](https://user-images.githubusercontent.com/37897247/86404666-413a0500-bc6d-11ea-8636-42eff8b5c396.PNG)

**Comment by lherman-cs** [comment]
@Anshulkaaya I'm sorry for the inconvenience. Recently, we updated our build system to remove custom scripts. The script that you're referring, `install-script`, is no longer necessary since calling `cmake ..` will do the same thing.

**Comment by lherman-cs** [comment]
Since there's no actual bug, I'll mark this as resolve. The documentation fix is being tracked here, https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/pull/503.

Please feel free to reopen this issue if you need further assistance.
