### ISSUE TITLE
libopenssl build failure [QUESTION]

### ISSUE THREAD

**Issue by jeromewe** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#504]
make[2]: *** [CMakeFiles/project_libopenssl.dir/build.make:91：build/src/project_libopenssl-stamp/project_libopenssl-download] 错误 1
make[1]: *** [CMakeFiles/Makefile2:73：CMakeFiles/project_libopenssl.dir/all] 错误 2
make: *** [Makefile:84：all] 错误 2
CMake Error at open-source/amazon-kinesis-video-streams-producer-c/CMake/Utilities.cmake:93 (message):
  CMake step for libopenssl failed: 2
Call Stack (most recent call first):
  open-source/amazon-kinesis-video-streams-producer-c/CMakeLists.txt:64 (build_dependency)

-- Configuring incomplete, errors occurred!

**Comment by lherman-cs** [comment]
@jeromewe Sorry for the inconvenience. Could you try to rerun the cmake command again? We've been seeing this strange issue where you need to configure it twice to make it work. Of course this is not ideal, but it should at least solve your issue for now. We will keep this ticket open to keep track this issue to deliver a long term solution.

**Comment by lherman-cs** [comment]
Since the issue has gone stalled, I'll mark this as resolved. Please feel free to reopen it for further assistance!

**Comment by amitrjaiswal1** [comment]
I am facing this build error.....

CMake Error at C:/amazon-kinesis-video-streams-producer-sdk-cpp/open-source/local/libopenssl/build/tmp/project_libopenssl-gitclone.cmake:52 (message):  Failed to update submodules in:  'C:/amazon-kinesis-video-streams-producer-sdk-cpp/open-source/local/libopenssl/build/src/project_libopenssl'ninja: build stopped: subcommand failed.
