### ISSUE TITLE
How to convert compiled/updated c++ SDK into docker?

### ISSUE THREAD

**Issue by thasin96** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#519]
I have cloned `amazon-kinesis-video-streams-producer-sdk-cpp` repository. I have made changes to the SDK. I would like to convert this SDK into docker environment. How to convert this? Do you have specific DockerFile for this?

**Comment by disa6302** [comment]
@thasin96 ,

You can refer to this: https://github.com/aws-samples/amazon-kinesis-video-streams-demos/blob/master/producer-cpp/ that has couple of dockerfiles you can look at
