### ISSUE TITLE
Storage used behind kinesis video streams

### ISSUE THREAD

**Issue by arunc4u91** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#52]
Hello

What's the storage system used as part of kinesis video stream services (whether S3 buckets or it has its own) and is it possible to stream the videos that are already created and stored in local device.

Regards
Arun.

**Comment by unicornss** [comment]
Hi @arunc4u91 .  They are stored in S3 

Ref:

-  https://aws.amazon.com/kinesis/video-streams/. 

The recommended way to get stream is to use the GetMedia API .

 Ref:  

- https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_dataplane_GetMedia.html

- https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/parser-library.html 

> is  it possible to stream the videos that are already created and stored in local 
 device.

We will update the release when  this functionality is available (currently its in our plan).
