### ISSUE TITLE
when i am try to create my application or compile sample app it given fatal error

### ISSUE THREAD

**Issue by rraghav476** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#521]
i am try to build my own application using given sdk or try to run sample app 
it give fata error like gst/gst.h and gtest/gtest.h file not found

**Comment by rraghav476** [comment]
kinesis_video_gstreamer_sample_app.cpp:1:21: fatal error: gst/gst.h: No such file or directory

**Comment by lherman-cs** [comment]
@rraghav476 have you installed the dependency requirements?

Mac:
```
brew install pkg-config openssl cmake gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly log4cplus gst-libav
```

Linux
```
sudo apt-get install libssl-dev libcurl4-openssl-dev liblog4cplus-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-base-apps gstreamer1.0-plugins-bad gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-tools
```

If you have specified, `-DBUILD_DEPENDENCIES=ON`, you still need to install gstreamer and its plugins by yourself.

**Comment by rraghav476** [comment]
@lherman-cs thank for reply
yes i am installed the dependency requirements
by using Linux command as you mention above
OK let me explain how i an going on
step 1 clone the repository
    git clone --recursive https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp.git
step 2 install dependency
    sudo apt-get install libssl-dev libcurl4-openssl-dev liblog4cplus-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev   gstreamer1.0-plugins-base-apps gstreamer1.0-plugins-bad gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-tools
step 3 make build directory
step 4 run cmake and make
and after that I am write my code and run it give fatal error about

**Comment by lherman-cs** [comment]
@rraghav476 Could you check gstreamer's include paths, `pkg-config --cflags-only-I gstreamer-1.0`?

And, could you verify if those paths are searchable from gcc/clang, `gcc -xc -E -v -`? This will give a list of search paths from gcc/clang.

**Comment by rraghav476** [comment]
@lherman-cs on running 
`pkg-config --cflags-only-I gstreamer-1.0`
it return gstreamer paths like
`-I/usr/include/gstreamer-1.0 -I/usr/lib/x86_64-linux-gnu/gstreamer-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linuxgnu/glib-2.0/include`
but these paths are not searchable by gcc/clang
by running 'gcc -xc -E -v -` it return me
![gcc](https://user-images.githubusercontent.com/59862361/88629964-8ebf5b80-d0cd-11ea-9f1e-06ef4dae3e58.png)

**Comment by MushMal** [comment]
Something seems to be wrong with the GStreamer install path. Are you able to run GStreamer commands like gst-launch-1.0 from your command prompt?

**Comment by rraghav476** [comment]
i can't able to run GStreamer using `gst-launch-1.0`
it's return error 
ERROR: pipeline could not be constructed: empty pipeline not allowed

**Comment by MushMal** [comment]
That’s ok. So, it does seem that young have the GStreamer core installed and the path is set. Can you find the gst/gst.h file? Perhaps, you have two separate installations?

**Comment by rraghav476** [comment]
@MushMal 
i can't find gst/gst.h
sorry what do you mean by two separate installations

**Comment by MushMal** [comment]
For some reason your installation of GStreamer does not include the header files. I am not sure why but if you have installed the devel package and it still doesn’t show up then you might want to re-install it. Also, GStreamer forums may be a good source of information as well

**Comment by rraghav476** [comment]
thank you for information

**Comment by MushMal** [comment]
I am going to resolve this issue for now. Please don't hesitate to reopen or cut a new one
