### ISSUE TITLE
libopenssl build failure

### ISSUE THREAD

**Issue by amitrjaiswal1** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#524]
I am facing this build error on Windows machine.....

CMake Error at C:/amazon-kinesis-video-streams-producer-sdk-cpp/open-source/local/libopenssl/build/tmp/project_libopenssl-gitclone.cmake:52 
(message): Failed to update submodules in: 'C:/amazon-kinesis-video-streams-producer-sdk-cpp/open-source/local/libopenssl/build/src/project_libopenssl'ninja: build stopped: subcommand failed.

We are trying to build SDK through MSVC (Visual Studio 2019).

**Comment by MushMal** [comment]
Not really sure what might cause OpenSSL build failures. We have had some issues with parallel build built that usually gets past the failure after the retry. Are you able to replicate the script as in Travis.yaml file when the Travis Ci gets build for Windows?

**Comment by amitrjaiswal1** [comment]
Below is output log...

 [CMake] fatal: unable to access 'https://boringssl.googlesource.com/boringssl/': SSL certificate problem: unable to get local issuer certificate
[CMake] fatal: clone of 'https://boringssl.googlesource.com/boringssl' into submodule path 'C:/amazon-kinesis-video-streams-producer-sdk-cpp/open-source/local/libopenssl/build/src/project_libopenssl/boringssl' failed
[CMake] Failed to clone 'boringssl'. Retry scheduled

**Comment by lherman-cs** [comment]
@amitrjaiswal1 it seems that the issue is within your system, it failed to get public certificates. Could you try to use `curl https://boringssl.googlesource.com/boringssl/`? It should give you the same error.

**Comment by amitrjaiswal1** [comment]
@lherman-cs Got below error for 'curl https://boringssl.googlesource.com/boringssl/'
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.

**Comment by MushMal** [comment]
@amitrjaiswal1 the build/runtime failure is not really related to KVS and we won't be able to help much. Perhaps you could ask the question in OpenSSL forums and they might help.

Alternatively, you could clean up your system and ensure you have a non-broken OpenSSL libraries..

**Comment by amitrjaiswal1** [comment]
@MushMal will do. Thanks for prompt update.

**Comment by fertrevino** [comment]
Did you manage to find a solution? Facing the same problem...
