### ISSUE TITLE
How to configure region for each stream in kvs_gstreamer_multistream_sample.cpp

### ISSUE THREAD

**Issue by thasin96** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#530]
I have modified the exisiting kvs_gstreamer_multistream_sample.cpp to assign individual stream name for each stream instead of stream_name_n when is 0, 1, 2,...n-1. Is it possible to configure stream region for each stream in kvs_gstreamer_multistream_sample.cpp?

**Comment by MushMal** [comment]
The SDK is not designed for having a single client object streaming to different regions. For that, you might need to create separate client objects, each having it's own stream.
