### ISSUE TITLE
[QUESTION] MAX_FRAGMENT_DURATION_REACHED?

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#537]
We are getting the following error:
As a result of this error, it takes a long time to connect to the AWS.
We are using gstreamer rstpsrc with kvssink.
Any idea where this is coming from?
We also found the two posts and wondering if they are relevant?
https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/issues/147
https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/issues/253

[DEBUG] [10-08-2020 13:20:07:425.122 GMT] postWriteCallback(): Curl post body write function for stream with handle: 1C8259185F2B and upload handle: 6 returned: {"EventType":"ERROR","FragmentTimecode":1597065596575,"FragmentNumber":"91343852333288683254220252678785835020226515305","ErrorCode":"MAX_FRAGMENT_DURATION_REACHED","ErrorId":4002}
… …
[DEBUG] [10-08-2020 13:25:00:159.674 GMT] postWriteCallback(): Curl post body write function for stream with handle: 1C8259185F2B and upload handle: 8 returned: {"EventType":"ERROR","

**Comment by MushMal** [comment]
Yes, per attached closed issues, you are getting max fragment duration error due to large fragments (over 10seconds). Please ensure you have proper fragmentation set in your pipeline. 

Resolving for now. Please feel free to reopen if you have questions related to KVS
