### ISSUE TITLE
[QUESTION] How do the kvvsink framerate and key-frame-fragmentation properties work?

### ISSUE THREAD

**Issue by js1972** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#539]
I am using the kvssink gstreamer plugin to stream from rtsp cameras to kvs and then consume them in a mobile app (ios and android).

I note that kvssink has a `framerate` property that defaults to 25. How does this affect the stream. For example - if my camera is set to 10 fps, is kvssink then doubling up the frames to try and get to 25 fps? Do I need to manually set the fps property to the same value as my camera?

Or does this property not actually do anything to the framerate... From reading the source it seems that its only being used in buffer size calculations (but I may be wrong).
I notice that in all the provided gst-launch-1.0 example you don't set the property.

`key-frame-fragmentation` - the default is TRUE. When or why would you set this to false? I'm just trying to understand its purpose... I have issue #441 and am wondering how this setting interplays with that?

**Comment by MushMal** [comment]
@js1972 you are correct, the KVS specific parameter frame rate is only used for buffer optimization. The actual frame rate should be configured upstream in the video source and possibly the encoder.
