### ISSUE TITLE
RTSP Docker inside FARGATE using IAM roles

### ISSUE THREAD

**Issue by vighnu** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#558]
Wanted to know if it is possible to push data to Kinesis Streams from the RTSP docker demo running as an ECS task using IAM roles (not using a dedicated user) without any source code change.

**Comment by MushMal** [comment]
Sorry, the SDK supports a few credential providers. You will need to build your own similar to the ones that exist - such as IoT or others
