### ISSUE TITLE
Cmake cannot run as it doesnt appear to contain CMakeLists.txt

### ISSUE THREAD

**Issue by lincolnchoo** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#559]
Was trying to follow this guide : https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/producer-sdk-win.html but received the following error

$ cmake ..
CMake Error: The source directory "C:/msys64/home/xxx/amazon-kinesis-video-streams-producer-c/build/amazon-kinesis-video-streams-producer-c" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by MushMal** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#download

Clone recursively to include the submodules. Resolving. Please reopen if needed
