### ISSUE TITLE
Transfer rate to Kinesis too low

### ISSUE THREAD

**Issue by tiensu** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#564]
I hear that Kinesis Video Stream can work with real-time video.
I tried, but the video stream from my IP camera to Kinesis Video Stream too slow.
This is my command: 
**_gst-launch-1.0 rtspsrc location=rtsp://admin:admin@10.1.34.222:554/ch01/0 short-header=TRUE ! rtph264depay ! kvssink stream-name="stream-d9" storage-size=512 access-key="***" secret-key="***" aws-region="ap-northeast-1"_**
My Internet speed is hight, about 90Mbps upload (test by SpeedTest.net)
Initial transfer_rate is hight (5Mbps) then gradually decrease to around 500Kbps.
I view video on "https://aws-samples.github.io/amazon-kinesis-video-streams-media-viewer/", it delays about 1 minute.
Did I make something wrong?

**Comment by disa6302** [comment]
@tiensu ,

Updates?

**Comment by disa6302** [comment]
@tiensu , 

Closing this issue for now since it has gone stale. Please feel free to reach out if you have any questions or you can reopen this issue as well. Thanks!
