### ISSUE TITLE
smanda@VSC-WS216 MINGW64 /c/AWS/amazon-kinesis-video-streams-producer-sdk-cpp/build (master)

### ISSUE THREAD

**Issue by surekha3079** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#565]
smanda@VSC-WS216 MINGW64 /c/AWS/amazon-kinesis-video-streams-producer-sdk-cpp/build (master)
$ ./min-install-script
bash: ./min-install-script: No such file or directory
Could u pls suggest me..

_Originally posted by @surekha3079 in https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/issues/254#issuecomment-692572626_

**Comment by MushMal** [comment]
As commented on the other post. Check out the readme in the root directory
