### ISSUE TITLE
vs-buildtools-install.bat not working in MSVC

### ISSUE THREAD

**Issue by surekha3079** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#566]
iam trying to build c++ sdk through url : https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/producer-sdk-win.html#producer-sdk-win-msvc
In 4th step iam unable to run this "vs-buildtools-install.bat" file.
Showing error as-- C:\AWS\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-native-build>vs-buildtools-install.bat
'vs-buildtools-install.bat' is not recognized as an internal or external command,
operable program or batch file.

**Comment by surekha3079** [comment]
Divya,
Iam new to this AWS.Could u pls provide your mail id for contact. It will be helpful to me

**Comment by MushMal** [comment]
@surekha3079 we can't give out personal emails. If you have questions regarding KVS itself, you could cut issues and get some help. If you need to provide or discuss direct matters that require privacy, you could compile an email and send it to kinesis-video-support@amazon.com.

Alternatively, we would encourage you to reach out to your AWS Account Management Team. You can do so from the AWS console.

**Comment by surekha3079** [comment]
Ok Thanku.
