### ISSUE TITLE
The CXX compiler identification is unknown

### ISSUE THREAD

**Issue by surekha3079** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#567]
Hi, I took latest build .When iam running cmake .. -G "NMake Makefiles" iam facing below error.I installed cmake,pkg-config,gstreamer,VS build tools 2019 also

smanda@VSC-WS216 MINGW64 /c/Users/smanda/amazon-kinesis-video-streams-producer-sdk-cpp-3.0.0/build
$ cmake .. -G "NMake Makefiles"
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:8 (project):

**Comment by disa6302** [comment]
@surekha3079 ,

Can you please attach the rest of the logs?

Are you using mingw? If yes, you might have to export CXX

**Comment by disa6302** [comment]
This is a sample you could use: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/.github/build_windows.bat

Also, check out the windows build in .travis.yml for the steps and see if it works

**Comment by surekha3079** [comment]
Actually below is the process iam doing.
1)Download the latest from Release 3.0.0 (14th May 2020) 
By following Readme.mdinstalled `pkg-config` and `CMake` and gstreamer for MINGW64
![1](https://user-images.githubusercontent.com/71141805/93506314-b72f3d80-f939-11ea-9bf0-3711fa6e36c4.jpg)
2)Running ‘ cmake .. -G "NMake Makefiles" ’  command in build location.Iam getting below error
![2](https://user-images.githubusercontent.com/71141805/93506371-c910e080-f939-11ea-88fb-89809c0adf63.jpg)
But I installed build tools also by selected c++ build tools.
![3](https://user-images.githubusercontent.com/71141805/93506432-e34abe80-f939-11ea-8408-08180decaa12.jpg)

**Comment by MushMal** [comment]
You need to debug this yourself a little. For some reason the paths are not being set properly. Perhaps, add the compiler paths to your %PATH% variable. VS also installs a VS shell that has those paths setup. Check VS support pages and the documentation on how to get that done

**Comment by surekha3079** [comment]
Thanku .Now i was able to run by referring **build_windows.bat** file. cmake is able to identify compiler.
But iam facing one issue like..I installed curl and set the path in environment variables also
CMake Error at CMakeLists.txt:106 (find_package):
  Could not find a package configuration file provided by "CURL" with any of
  the following names:

    CURLConfig.cmake
    curl-config.cmake

  Add the installation prefix of "CURL" to CMAKE_PREFIX_PATH or set
  "CURL_DIR" to a directory containing one of the above files.  If "CURL"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by disa6302** [comment]
@surekha3079 , 

Based on https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/issues/569, looks like your build is working. Closing this issue. Feel free to reach out if you have any more questions.
