### ISSUE TITLE
[ 68%] Linking C shared library libcproducer.dylib [ 68%] Built target cproducer make: *** [all] Error 2

### ISSUE THREAD

**Issue by RayChanDatalityLab** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#571]
after installed all build tools and run ./min-install-script
received:
[ 68%] Linking C shared library libcproducer.dylib
[ 68%] Built target cproducer
make: *** [all] Error 2

I am using macOS 10.15.6

**Comment by MushMal** [comment]
Please use the latest code/release . Use the instructions in the readme.md and not the min install script. The documentation in the AWS docs is stale. The build is now based on cmake script
