### ISSUE TITLE
No media found Verify that you are streaming to ap-south-1 and the fragment timecodes are correct, or download the Kinesis Video Streams Producer SDK to set up your device.

### ISSUE THREAD

**Issue by surekha3079** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#586]
Hi, Files generated for amazon-kinesis-video-streams-producer-sdk-cpp producer sdk. but while streaming through gstreamer command facing error in console application.

![error in console login](https://user-images.githubusercontent.com/71141805/95682087-039c2f00-0c01-11eb-8f28-82f18c8f28d1.PNG)

Getting error in console login.
Any suggestions..

**Comment by MushMal** [comment]
1) Check if you are streaming and consuming in the same region
2) Debug your producer and see whether it’s able to successfully stream the media.

You can search the list of issues on how to enable the debug verbosity in GStreamer and KVS producer.

Please cut a new issue when you narrow down the reason.
