### ISSUE TITLE
[QUESTION] Curl 32 bits asked when Curl 64bits is built 

### ISSUE THREAD

**Issue by PierreSau** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#592]
Trying to compile KVS C++ producer sdk on windows 10 / VSC 2017 via the x64 native command tool as ml64.exe is needed.
I tried to compile via this command : cmake -G "NMake Makefiles" -DBUILD_GSTREAMER_PLUGIN=ON
After building project_libcurl, it was the turn to build libkvspic
And I got the following output. It's not an environmment error. Maybe I found a bug ? 
<img width="1018" alt="help2" src="https://user-images.githubusercontent.com/43744145/96295033-910ac500-0fed-11eb-914d-b5ef106cfdd4.PNG">
If anyone could help me I'll be grateful.
Thanks in advance.

**Comment by lherman-cs** [comment]
@PierreSau it seems that the curl version that we're using is not compatible with your system, could you try to upgrade the curl version here, https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/CMake/Dependencies/libcurl-CMakeLists.txt#L30?

**Comment by PierreSau** [comment]
Hello Thanks for your answer and your help. I tried changing the line as you ask and it still doesn't work.

**Comment by MushMal** [comment]
Are you using 32 or 64 bit command line flags? I believe when you install VS, it creates two shortcuts which have defines for 32 or 64 bit command line tools. You need to ensure you use the right command line.

**Comment by PierreSau** [comment]
I am using x86 native tools Command Prompt.  If you have a better tool to build the project please let me know. But on windows 10 I was unsuccesful trying to use mingw64 via msys2

**Comment by MushMal** [comment]
Use the 64bit version. x86 is setting env vars for 32 bit which confuses the libCurl cmake list. You can file an issue with that project to fix the dependency on the env vars

**Comment by PierreSau** [comment]
Thank you I'll try that asap

**Comment by MushMal** [comment]
Please reopen if you need help

**Comment by keiwong0624** [comment]
Hi all, I am facing the same problem. I have tried both x64 native and x86 native VS command prompt but they do not work. Any idea to resolve this issue.?

**Comment by Lepm11** [comment]
Hi @RW0624 did you solve the problem?
