### ISSUE TITLE
[QUESTION] local rtsp camera is not streaming

### ISSUE THREAD

**Issue by connectiv-source** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#599]
Hi,

I have tested the kinesis streaming using linux containers , it gets well live demo camera eg:

rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov;
https://www.radiantmediaplayer.com/media/big-buck-bunny-360p.mp4;

otherwise, when testing it on my local rtsp camera it is not streamed. I used both the custom command & samples:

$ ./kvs_gstreamer_sample $aws_kvs $rtsp_0./kvs_gstreamer_sample my_kenisis_name my_camera_rtsp

$ gst-launch-1.0 -v rtspsrc location=my_camera_rtsp  short-header=TRUE ! rtph264depay ! video/x-h264, for
mat=avc,alignment=au ! h264parse ! kvssink stream-name=my_kenisis_name storage-size=128
the logs is similar to below:

2020-10-28 16:03:56 [140205810067200] DEBUG - putStreamCurlHandler(): Network thread for Kinesis Video stream: clic with upload handle:
 3 exited. http status: 0
2020-10-28 16:03:56 [140205810067200] WARN - putStreamCurlHandler(): Stream with streamHandle 11863960 has exited without triggering en
d-of-stream. Service call result: 599
2020-10-28 16:03:56 [140205810067200] INFO - kinesisVideoStreamTerminated(): Stream 0xb50798 terminated upload handle 3 with service ca
ll result 599.
2020-10-28 16:03:56 [140205810067200] DEBUG - stepStateMachine(): State Machine - Current state: 0x0000000000000100, Next state: 0x0000
000000000200
2020-10-28 16:03:56 [140205810067200] DEBUG - stepStateMachine(): State Machine - Current state: 0x0000000000000200, Next state: 0x0000
000000000040
2020-10-28 16:03:56 [140205432493824] DEBUG - streamReadyHandler invoked
2020-10-28 16:03:56 [140205432493824] DEBUG - stepStateMachine(): State Machine - Current state: 0x0000000000000040, Next state: 0x0000
000000000080
2020-10-28 16:03:56 [140205432493824] INFO - putStreamResultEvent(): Put stream result event. New upload handle 4
2020-10-28 16:03:56 [140205432493824] DEBUG - stepStateMachine(): State Machine - Current state: 0x0000000000000080, Next state: 0x0000
000000000100
2020-10-28 16:03:56 [140205432493824] DEBUG - Dropping frame with flag %u1024
2020-10-28 16:03:58 [140205432493824] /GstPipeline:pipeline0/GstRTSPSrc:rtspsrc0/GstRtpBin:manager/GstRtpSession:rtpsession1: stats = "
application/x-rtp-session-stats\,\ rtx-drop-count\=\(uint\)0\,\ sent-nack-count\=\(uint\)0\,\ recv-nack-count\=\(uint\)0\,\ source-stat
s\=\(GValueArray\)NULL\,\ rtx-count\=\(uint\)0\;"
INFO - writeHeaderCallback(): RequestId: f8395998-0e5b-6357-a02a-c12a8ba06875
2020-10-28 16:04:01 [140205810067200] DEBUG - postReadCallback(): Pausing CURL read for upload handle: 4
2020-10-28 16:04:01 [140205810067200] DEBUG - Dropping frame with flag %u1024
2020-10-28 16:04:02 [140205432493824] /GstPipeline:pipeline0/GstRTSPSrc:rtspsrc0/GstRtpBin:manager/GstRtpSession:rtpsession1: stats = "
application/x-rtp-session-stats\,\ rtx-drop-count\=\(uint\)0\,\ sent-nack-count\=\(uint\)0\,\ recv-nack-count\=\(uint\)0\,\ source-stat
s\=\(GValueArray\)NULL\,\ rtx-count\=\(uint\)0\;"
/GstPipeline:pipeline0/GstRTSPSrc:rtspsrc0/GstRtpBin:manager/GstRtpSession:rtpsession1: stats = "application/x-rtp-session-stats\,\ rtx
-drop-count\=\(uint\)0\,\ sent-nack-count\=\(uint\)0\,\ recv-nack-count\=\(uint\)0\,\ source-stats\=\(GValueArray\)NULL\,\ rtx-count\=\
(uint\)0\;"
DEBUG - Dropping frame with flag %u1024
2020-10-28 16:04:06 [140205432493824] /GstPipeline:pipeline0/GstRTSPSrc:rtspsrc0/GstRtpBin:manager/GstRtpSession:rtpsession1: stats = "
application/x-rtp-session-stats\,\ rtx-drop-count\=\(uint\)0\,\ sent-nack-count\=\(uint\)0\,\ recv-nack-count\=\(uint\)0\,\ source-stat
s\=\(GValueArray\)NULL\,\ rtx-count\=\(uint\)0\;"
/GstPipeline:pipeline0/GstRTSPSrc:rtspsrc0/GstRtpBin:manager/GstRtpSession:rtpsession1: stats = "application/x-rtp-session-stats\,\ rtx
-drop-count\=\(uint\)0\,\ sent-nack-count\=\(uint\)0\,\ recv-nack-count\=\(uint\)0\,\ source-stats\=\(GValueArray\)NULL\,\ rtx-count\=\
(uint\)0\;"
/GstPipeline:pipeline0/GstRTSPSrc:rtspsrc0/GstRtpBin:manager/GstRtpSession:rtpsession1: stats = "application/x-rtp-session-stats\,\ rtx
-drop-count\=\(uint\)0\,\ sent-nack-count\=\(uint\)0\,\ recv-nack-count\=\(uint\)0\,\ source-stats\=\(GValueArray\)NULL\,\ rtx-count\=\
(uint\)0\;"
DEBUG - Dropping frame with flag %u1024
2020-10-28 16:04:10 [140205432493824] /GstPipeline:pipeline0/GstRTSPSrc:rtspsrc0/GstRtpBin:manager/GstRtpSession:rtpsession1: stats = "
application/x-rtp-session-stats\,\ rtx-drop-count\=\(uint\)0\,\ sent-nack-count\=\(uint\)0\,\ recv-nack-count\=\(uint\)0\,\ source-stat
s\=\(GValueArray\)NULL\,\ rtx-count\=\(uint\)0\;"
/GstPipeline:pipeline0/GstRTSPSrc:rtspsrc0/GstRtpBin:manager/GstRtpSession:rtpsession1: stats = "application/x-rtp-session-stats\,\ rtx
-drop-count\=\(uint\)0\,\ sent-nack-count\=\(uint\)0\,\ recv-nack-count\=\(uint\)0\,\ source-stats\=\(GValueArray\)NULL\,\ rtx-count\=\
(uint\)0\;"
DEBUG - Dropping frame with flag %u1024
2020-10-28 16:04:14 [140205432493824] /GstPipeline:pipeline0/GstRTSPSrc:rtspsrc0/GstRtpBin:manager/GstRtpSession:rtpsession1: stats = "
application/x-rtp-session-stats\,\ rtx-drop-count\=\(uint\)0\,\ sent-nack-count\=\(uint\)0\,\ recv-nack-count\=\(uint\)0\,\ source-stat
s\=\(GValueArray\)NULL\,\ rtx-count\=\(uint\)0\;"
/GstPipeline:pipeline0/GstRTSPSrc:rtspsrc0/GstRtpBin:manager/GstRtpSession:rtpsession1: stats = "application/x-rtp-session-stats\,\ rtx
-drop-count\=\(uint\)0\,\ sent-nack-count\=\(uint\)0\,\ recv-nack-count\=\(uint\)0\,\ source-stats\=\(GValueArray\)NULL\,\ rtx-count\=\
(uint\)0\;"
DEBUG - Dropping frame with flag %u1024
2020-10-28 16:04:18 [140205432493824] /GstPipeline:pipeline0/GstRTSPSrc:rtspsrc0/GstRtpBin:manager/GstRtpSession:rtpsession1: stats = "
application/x-rtp-session-stats\,\ rtx-drop-count\=\(uint\)0\,\ sent-nack-count\=\(uint\)0\,\ recv-nack-count\=\(uint\)0\,\ source-stat
s\=\(GValueArray\)NULL\,\ rtx-count\=\(uint\)0\;"
/GstPipeline:pipeline0/GstRTSPSrc:rtspsrc0/GstRtpBin:manager/GstRtpSession:rtpsession1: stats = "application/x-rtp-session-stats\,\ rtx
-drop-count\=\(uint\)0\,\ sent-nack-count\=\(uint\)0\,\ recv-nack-count\=\(uint\)0\,\ source-stats\=\(GValueArray\)NULL\,\ rtx-count\=\
(uint\)0\;"

**Comment by unicornss** [comment]
> when testing it on my local rtsp camera it is not streamed.

Could you pl. check if your RTSP camera is sending H264 video stream?

**Comment by connectiv-source** [comment]
Thanks @unicornss for you reply.

yes it is H264

**Comment by MushMal** [comment]
@unicornss is right - your camera doesn't seem to produce frames and the producer is timing out and re-streaming. Are you using the latest code BTW? This is incidental to the issue but my suggestion is for you to do some of your own debugging of your camera/rtsp stream. As is, this issue is not actionable unless you provide detailed information so we can see whether it's related to KVS itself. 

One of the steps to debug might be to use a gstreamer pipeline without KVS in it and see whether you have a stable camera/rtsp.

**Comment by connectiv-source** [comment]
Hi @MushMal ,
Thanks for you reply,.

- yes i am using the last sdk running on container
- the camera codec is H264-MPEG- 4 AVC (part10)
- i tried the gstreamer pipline without KVS and it went ok without KVS:
`$ gst-launch-1.0 rtspsrc location=rtsp_url short-header=TRUE ! rtph264depay ! video/x-h264, format=avc, alignment=au ! decodebin ! autovideosink`
I have been strugling on this since a week and I am eagly need to get cameras streaming. I appreciate your help guys.

**Comment by MushMal** [comment]
Seems like it is not related to KVS but rather your camera and the rtsp source.

Try to get more logs by running with debug gstreamer logging enabled. Set the following env variable

export GST_DEBUG=5

Run and see if you can spot any problems.

You can get more help from GStreamer forums.

**Comment by connectiv-source** [comment]
I also tried the full command:

```
gst-launch-1.0 rtspsrc location=$rtsp short-header=TRUE ! rtph264dep
ay ! video/x-h264, format=avc, alignment=au ! h264parse ! kvssink stream-name=$a
ws_kvs storage-size=512 access-key=$aws_access secret-key=$aws_secret aws-region
=$aws_region
```


with below logs:

```
- Current state: 0x0000000000000040, Next state: 0x0000000000000080
2020-10-30 18:22:21 [140126098962176] INFO - putStreamResultEvent(): Put stream
result event. New upload handle 2
2020-10-30 18:22:21 [140126098962176] DEBUG - stepStateMachine(): State Machine
- Current state: 0x0000000000000080, Next state: 0x0000000000000100
2020-10-30 18:22:21 [140126098962176] INFO - writeHeaderCallback(): RequestId: d
caff865-63bb-53dd-84b9-a44729ce4168
2020-10-30 18:22:21 [140126339020544] DEBUG - postReadCallback(): Pausing CURL r
ead for upload handle: 2
2020-10-30 18:22:21 [140126339020544] DEBUG - Dropping frame with flag %u1024
2020-10-30 18:22:21 [140126098962176] DEBUG - Dropping frame with flag %u1024
2020-10-30 18:22:22 [140126098962176] DEBUG - Dropping frame with flag %u1024
2020-10-30 18:22:23 [140126098962176] DEBUG - Dropping frame with flag %u1024
```

**Comment by MushMal** [comment]
The snippets of log you are attaching contain no information. The GStreamer plugin code will drop the frames with flags that it can't handle/process. This is OK in some cases. You should debug into it and see what those are.

Also, per suggestions, have you tried streaming without the KVS sink? Just use autovideosink or something alike. Capture entire log so if there are issues with KVS we could identify it but from what it looks, it's nothing to do with kvs

**Comment by connectiv-source** [comment]
here is the log
[kvs.log](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/files/5467037/kvs.log)

**Comment by MushMal** [comment]
You have a lot of 

[DEBUG] [30-10-2020 18:04:17:998.261 GMT] postWriteCallback(): Curl post body write function for stream with handle: clic and upload handle: 0 returned: {"EventType":"ERROR","FragmentTimecode":1604081040340,"FragmentNumber":"91343852333181571041966462595092227335173489310","ErrorCode":"MAX_FRAGMENT_DURATION_REACHED","ErrorId":4002}

This means that your encoder does not produce I-frames. 

Work with your rtsp camera and ensure it's configured to produce an I-frame every 2-8 seconds

**Comment by MushMal** [comment]
Please resolve this issue if you have no further questions about KVS. We can' help with your camera.

**Comment by connectiv-source** [comment]
@MushMal I am thankful to your help here.

I set it the I-Frame-Interval to 2 seconds as suggest, but still the issue with no success. here's the log:
[kvs.log](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/files/5467126/kvs.log)

**Comment by MushMal** [comment]
You have two issues

1) max fragment duration reached which is an issue with your media source not producing i frames
2) your media pipeline stalls and doesn’t produce frames causing the timeout which in itself is not an issue but you should see why your pipeline stalls.

We won’t be able to help debugging your hardware. Try to see if there are configurations that you can modify. Ensure you have enough bandwidth between the camera and the KVS producer. Run with fakesink to stabilize your media source first. This is the 4th back and forth wround this issue and none that’s KVS related. You can look at the logs for more info.

**Comment by MushMal** [comment]
Closing. Please don't hesitate to cut KVS specific issues with detailed information.
