### ISSUE TITLE
Where is the install-script or min-install-script?

### ISSUE THREAD

**Issue by arnamoy10** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#600]
I am trying to install the library (and the sample applications) in a RPi model 4, but when I try to follow the instructions from this link --> https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/producersdk-cpp-rpi.html#producersdk-cpp-rpi-camera. 

It asks me `chmod +x install-script`

Where do I find this script?  It is not in the repo

**Comment by MushMal** [comment]
The documentation is stale, we no longer use scripts to build but rather cmake itself. More info in the readme page

**Comment by disa6302** [comment]
Closing this issue.
