### ISSUE TITLE
'MAKE_EXE-NOTFOUND' is not recognized as an internal or external command, operable program or batch file.[QUESTION]

### ISSUE THREAD

**Issue by daling11** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#606]
Hi there,

When I using cmake to build the C++ producer sdk on windows, I have this error message:

![WeChat Image_20201106211757](https://user-images.githubusercontent.com/61116916/98432788-d1f77600-208f-11eb-88c0-7ea7458bc826.png)

This is my log file:

[CMakeOutput.log](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/files/5504347/CMakeOutput.log)

What is 'MAKE_EXE-NOTFOUND' command? I installed the make.exe but it didn't work. Does anyone has this problem before?

**Comment by MushMal** [comment]
I have not seen any issues like this. Could you make sure you have a clean build with the correct dependencies set. We have a windows Travis.ci build and the script that you can check out. Also, try to shorten the path and retry

**Comment by MushMal** [comment]
Any updates on this issue?

**Comment by daling11** [comment]
Sorry I forgot to update. I try to use X64 Native Tools Command Prompt instead of Cmake Gui and the problem fixed. Thank you very much for your help!

**Comment by aqiao** [comment]
@daling11 , the ` X64 Native Tools Command Prompt` you mentioned is the Windows build-in command line prompt?, i faced the same issue, and i used the Windows default command line prompt with administrator privilige
