### ISSUE TITLE
[QUESTION]While uninitialising the stream, do we need putEoFr()?

### ISSUE THREAD

**Issue by Subburaj47** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#610]
When uninitialising the stream, here's the sequence we follow (when both audio and video exists in the stream).
1) flush
2) putEofr
3) stop
4) freeStream

Should there be a putEofr necessarily available in this flow? We have a SIGABRT due to an assertion failure of the stream handle in **KinesisVideoStream::putFrame** consistently during the putEoFr call (only in the above said uninitialisation sequence).

Any thoughts around this would be greatly helpful.

**Comment by MushMal** [comment]
@Subburaj47 could you please give us a little more details about the assertion? We don't have asserts in the SDK.

If you are driving the fragmentation on your side, there is no need for putEofr on teardown. StopSync should take care of properly streaming out the remainder of the buffer, receive the last persisted ACK for the last streamed fragment and only then return.

**Comment by Subburaj47** [comment]
@MushMal  I meant about this line in the code where there is an assertion to check the stream_handle.
https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/3.0.0/src/KinesisVideoStream.cpp#L28

Regarding the usage we have the following which was working without any glitch in the previous SDK versions.
`    data->putFrameHelper->flush();

    data->putFrameHelper->putEofr();

    data->kinesis_video_stream->stop();

    data->kinesis_video_producer->freeStream(data->kinesis_video_stream);`

While working with the 3.0.0 SDK, we see an assertion failure during the stream uninitialisation (with the code snippet mentioned above). FYI, we are marking the key frames in the application side to fragment the clip. 
Could you pls share your thoughts on why there is an assertion failure only in the 3.0.0 SDK? Also, do you suggest to pull out the putEoFr( ) and add a stopSync( ) instead of stop( )?

**Comment by MushMal** [comment]
I see, yes indeed we do have asserts in C++ codebase. In this case, it seems that you are trying to putFrame after the stream has been torn down or something like that.

If you are driving the fragmentation then you no longer need the putEoFr. In fact,  in multi-track it would end up with an error 0x52000084 which is specifically guarding against trying to fragment using key-frame fragmentation and at the same time using EoFR in the frame order coordinator designed to do the fragmentation itself.

Regarding stop vs stopSync. Stop API is a "prompt" API - it stops any further frame production into the stream by setting flags and changing the internal state. It doesn't await for the stream finalization. Finalization is to stream out the existing buffer contents, put EoS to trigger session teardown from the backend, await for the final persisted ACK. In the async case the applications would kick off stop and then continue as soon they either get an error callback or stream stopped callback. StopSync API does the Sync and awaiting (with a configurable timeout) for the finalization.

**Comment by Subburaj47** [comment]
Thanks for the info @MushMal . I have removed the putEoFr() during the application's uninit.
