### ISSUE TITLE
[QUESTION] Producing a stream to Kinesis Video through Python using GStreamer?

### ISSUE THREAD

**Issue by AWOL-Jamie** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#621]
Is there a way to use GStreamer Python bindings to capture a capture card and implement the CPP plugin to stream to kinesis? 

Thanks in advance!

**Comment by disa6302** [comment]
@AWOL-Jamie ,

We do not have python bindings support for gstreamer yet. Closing since there is nothing we can do for the use case.
