### ISSUE TITLE
[BUG] Documentation link is missing

### ISSUE THREAD

**Issue by rodrigo-merino** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#626]
**Logging**
Add relevent SDK logging.  IMPORTANT NOTE:  Please make sure to NOT share AWS access credentials under any circumstance!  Please make sure they are not in the logs.

**Describe the bug*

**In the following URL,
https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/docs/linux.md#running-c-unit-tests,

the link set the credentials before running the unit tests is not working. Can you please fix the link? Thanks.**

**To Reproduce**

**Expected behavior**

**SDK version number**
Include the SDK version you are running. If it is a specific commit on master branch, include that

**Open source building**
If it is a build issue, include 3rd party library version and steps to how you are building it

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Linux, Windows]
 - Processor: [e.g. ARMv5]
 - Version [e.g. 18.04]

**Additional context**

**Comment by disa6302** [comment]
Will fix this ASAP. Thanks for reporting.
