### ISSUE TITLE
[BUG] There is not HEAP_DEBUB nor LOG_STREAMING in CMakeList.txt

### ISSUE THREAD

**Issue by rodrigo-merino** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#627]
**Logging**
Add relevent SDK logging.  IMPORTANT NOTE:  Please make sure to NOT share AWS access credentials under any circumstance!  Please make sure they are not in the logs.

**Describe the bug**

Can you please fix the documentation? Following this link:
https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/docs/linux.md#enabling-verbose-logs

There is neither HEAP_DEBUG nor LOG_STREAMING in CMakeList.txt file. I haven't found them in my installation. They can't be found neither in here https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/CMakeLists.txt nor anywhere else in this repo https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/search?q=HEAP_DEBUG

Please fix the documentation to be able to enable debug logs in the producer SDK.

**To Reproduce**

**Expected behavior**

**SDK version number**
Include the SDK version you are running. If it is a specific commit on master branch, include that

**Open source building**
If it is a build issue, include 3rd party library version and steps to how you are building it

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Linux, Windows]
 - Processor: [e.g. ARMv5]
 - Version [e.g. 18.04]

**Additional context**

**Comment by disa6302** [comment]
@rodrigo-merino , 

Looks like you are right. We will look into this ASAP
