### ISSUE TITLE
Could you expose a new kvssink plugin property to indicate memory overflow/underflow in bandwidth restriction situations?

### ISSUE THREAD

**Issue by rgroleau** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#632]
We are using the producer through the gstreamer kvssink plugin on embedded platforms that have cellular (LTE) modems.

Very often, the bandwidth will vary during the live stream, and in such situations we need to dynamically adjust the encoder bitrate (reduce it when less bandwidth is available, and increase it back when the bandwidth comes back to a higher speed and better latency).

Right now we rely on psutils to monitor the memory use of the kvssink/producer, and when the memory usage gets too high we reduce the encoder bitrate, and when the memory usage gets back to a more reasonable threshold we increase the bitrate back to a higher quality setting. This is clearly not optimal.

It would be much better for us if kvssink would expose a plugin property (readable only) or a gst-plugin callback so that we can get a clearer, specific information about whenever kvssink has difficulty uploading in a timely manner its frames (due to bandwidth limitations). The property could be called I don't know, latency, or overflow, in bytes or seconds.

Any other suggestion on how to implement this would be great too, if this is already a standard feature of the producer sdk (gst-plugin part).

**Comment by MushMal** [comment]
Dup of #375
