### ISSUE TITLE
[BUG] Documentation build_windows.bat needs to be updated

### ISSUE THREAD

**Issue by rodrigo-merino** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#633]
**Logging**
Add relevent SDK logging.  IMPORTANT NOTE:  Please make sure to NOT share AWS access credentials under any circumstance!  Please make sure they are not in the logs.

**Describe the bug**
It is only documentation, but the following file:

https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/.github/build_windows.bat

The file  build_windows.bat has to be updated to the newer version: Microsoft Visual Studio\2019\ so I have changed the first code line:
old:        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
new:      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"

**To Reproduce**

**Expected behavior**

**SDK version number**
Include the SDK version you are running. If it is a specific commit on master branch, include that

**Open source building**
If it is a build issue, include 3rd party library version and steps to how you are building it

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Linux, Windows]
 - Processor: [e.g. ARMv5]
 - Version [e.g. 18.04]

**Additional context**

**Comment by hassanctech** [comment]
This is used by our Travis CI which has VS2017, that is the current version supported in our automated builds, we have not yet moved to VS2019.
