### ISSUE TITLE
[BUG] Not able to build in Windows 10

### ISSUE THREAD

**Issue by rodrigo-merino** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#634]
**Logging**
Add relevent SDK logging.  IMPORTANT NOTE:  Please make sure to NOT share AWS access credentials under any circumstance!  Please make sure they are not in the logs.

**Describe the bug**
The project is not able to build/compile in a Windows 10 platform. CL, CMake and NMake are available in the path, but nevertheless, the project is not able to find them. Please see attached console output.

Thanks.
![1](https://user-images.githubusercontent.com/8721431/102132555-0c54ef80-3e54-11eb-886f-8fb76e1b3a96.JPG)
![2](https://user-images.githubusercontent.com/8721431/102132565-0f4fe000-3e54-11eb-8896-ea4a9b11406e.JPG)

**To Reproduce**

**Expected behavior**
To be able to compile in windows seemlessly.

**SDK version number**
Latest Master branch

**Open source building**
If it is a build issue, include 3rd party library version and steps to how you are building it

**Screenshots**
See attached screenshots.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Processor: [e.g. ARMv5]
 - Version [e.g. 18.04]

**Additional context**

**Comment by MushMal** [comment]
Can you follow the same steps as in Travis CI run for Windows. The readme would also be a good information source.

Resolving. Please cut a new issue with targeted question on what and how does not work.
