### ISSUE TITLE
[BUG] the gst plugin does not free all resources on finalize

### ISSUE THREAD

**Issue by rejeangroleau** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#682]
**Logging**
Logs here won't change much of the outcome, although we have plenty of logs to showcase the memory leak that we noticed on multiple platforms (including both x86_64 and armv7).

**Describe the bug**
When using the gstreamer plugin (gst kvssink), noticably with an application pipeline (e.g. using gst/gst.h or any equivalent), we noticed a very big memory leak when destroying/recreating the pipeline (that uses kvssink). We looked at the code and realized the finalize function for the gstkvssink plugin was just not freeing all resources. We slightly adjusted the code (two lines of change, really) and the huge memory leak went away. We thought of contributing the solution here through a pull request. It is up to you to use it or leave it. We use yocto/bitbake and as such currently apply the patch in a gstreamer1.-kinesis.bb recipe on top of your master branch to solve the problem.

**To Reproduce**
1. Start the pipeline (through an application that will not quit and therefore won't have its badly-freed resources freed-anyways by the kernel when exiting the whole app).
2. Note the memory usage.
3. Stop the pipeline and start it again (without quitting the app that started the gstreamer pipeline).
4. Note the memory usage increase.
5. Rince and repeat until your target device it out of ram thanks to a memory leak.

**Expected behavior**
No memory leak? The gstreamer plugin should free all of its resources when unloaded.

**SDK version number**
The git describe --tags command returns: 3.1.1-3-g6bbd9fd

**Open source building**
N/A

**Screenshots**
N/A

**Platform (please complete the following information):**
 - OS: all (windows, OS X, iOS, Android, linux)
 - Processor: all (i386, x86_64, armhf, armv7, more)
 - Version: all

**Additional context**
N/A

**Comment by disa6302** [comment]
PR merged. Closing. Thanks again @rejeangroleau !
