### ISSUE TITLE
[QUESTION] Could not delete Kinesis Video Stream

### ISSUE THREAD

**Issue by nguyenduynghia** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#692]
Our application will create each Kinesis  Video Stream for  every request.
So video stream will increase everyday.
I couldn't find delete stream function in SDK.
Now, I must use Amazon Console to  delete these stream.
Is there anyway to delete Kinesis Video Stream?

**Comment by disa6302** [comment]
@nguyenduynghia , 

We do have a delete stream API available. 

However, looks like AWS CPP SDK has one. 

https://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_kinesis_video_1_1_kinesis_video_client.html#a91f322e028fbb0dc6ffd177a84762380
