### ISSUE TITLE
[QUESTION] Delay the gstreamer stream

### ISSUE THREAD

**Issue by dorfindoor** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#696]
Hi.
I'm using a gstreamer pip, that has an h264 rtspsrc and a kvssink.
In order to sync my stream with another stream, I need to delay the stream upload for ~1 sec.
I use producer timestamp in my web app when I read the stream, so no buffer inside the pipe helps me because I always get the old producer timestamp, before the delay. Is there any way to delay the timestamp as well?
Or any other solution?

Thanks.

**Comment by hassanctech** [comment]
You may add an `appsink` element there you can retrieve the buffer and modify the timestamp then have an `appsrc` to consume the buffers with the modified timestamps.
