### ISSUE TITLE
how to remove debug kvssink message ?

### ISSUE THREAD

**Issue by waikup83** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#699]
how to remove debug kvssink message ?

i've allready add => putenv("GST_DEBUG=0,kvssink:0"); before initialisation of GStreamer

but a lot of kvssink debug and warning message are out anyway

**Comment by waikup83** [comment]
![image](https://user-images.githubusercontent.com/28206920/117337415-55412b00-ae6b-11eb-9340-33a5385c5ad4.png)

**Comment by disa6302** [comment]
If you want to get rid of KVS messages, you can set log level to SILENT. Check [this](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#setup-desired-log-level).

Not sure what you mean by kvssink messages and I do not understand how you have set the env, but kvssink in itself shouldnt have any logs. It is the producer SDK that would generate logs.

**Comment by waikup83** [comment]
kvssink came from libgstkvssink.so called from the GStreamer =>
gst_parse_launch("appsrc name=frame ! queue max-size-buffers=1 leaky=0 ! h264parse ! avdec_h264 ! queue max-size-buffers=1 leaky=0  ! x264enc key-int-max=10 ! queue max-size-buffers=1 leaky=0 ! kvssink stream-name=camera access-key=xxxxx secret-key=xxxx aws-region=xxx fragment-acks=true absolute-fragment-times=false frame-timecodes=false max-latency=1 replay-duration=0 frame-timestamp=1", NULL);

I set the environment variable from a class constructor in c++ with the putenv command and even if i set => putenv("AWS_KVS_LOG_LEVEL=7"); i get plenty of kinesis and curl debug log

**Comment by disa6302** [comment]
Please run `export AWS_KVS_LOG_LEVEL=7` to see if it works.

**Comment by disa6302** [comment]
Closing assuming question is answered.

**Comment by waikup83** [comment]
i've done it myself on the vm and it still havgin message

**Comment by waikup83** [comment]
... maybe it because i'Ts cant open log file ..
![image](https://user-images.githubusercontent.com/28206920/117345672-cdf8b500-ae74-11eb-80ea-6ed1885a3d2d.png)

**Comment by waikup83** [comment]
nope it's still

**Comment by MushMal** [comment]
@waikup83 the kvssink source is based on CPP repository which is substituting the default logger callback with the log4cplus.  By default it uses the configuration specified here: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/src/gstreamer/gstkvssink.cpp#L106

You can specify your own path by applying the following gst param: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/src/gstreamer/gstkvssink.cpp#L542

There is a sample log4cplus configuration available at: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/samples/kvs_log_configuration

You can write your own to control the verbosity levels.

NOTE: This will be applicable to KVS logs ONLY. You will still need to control GST logs. You can use `export GST_DEBUG=0` to disable the logs

**Comment by waikup83** [comment]
cool it work, thanks you very much !
