### ISSUE TITLE
Error on Mac OS when running cmake -DBUILD_GSTREAMER_PLUGIN=TRUE  -DBUILD_JNI=TRUE

### ISSUE THREAD

**Issue by jacquilenejacob** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#703]
While building the SDK on Mac OS (Big Sur 11.3.1)

CMake Error at /usr/local/Cellar/cmake/3.20.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find JNI (missing: JAVA_INCLUDE_PATH JAVA_AWT_INCLUDE_PATH)

**Comment by disa6302** [comment]
@jacquilenejacob ,

Have you installed openjdk?

**Comment by jacquilenejacob** [comment]
@disa6302  yes.

**Comment by disa6302** [comment]
Hmm. Probably some standard paths have changed on MacOS Bigsur. This SDK has not been tested on BigSur yet. Can you try exporting `JAVA_HOME` and see if it helps?

**Comment by hassanctech** [comment]
@jacquilenejacob 

You also need to do this `export CPATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include`

**Comment by hassanctech** [comment]
@jacquilenejacob This issue hasn't been updated in 11 days, if your issue is resolved please close.

**Comment by disa6302** [comment]
Closing since it has gone stale.
