### ISSUE TITLE
[QUESTION] Getting “ErrorCode”: “KMS_KEY_ACCESS_DENIED”,“ErrorId”:4500 while uploading media on AWS Kinesis

### ISSUE THREAD

**Issue by sskant786** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#706]
I have cloned the code from https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp and followed steps mentioned here. I have created build successfully after resolving few errors.

https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/docs/windows.md#running-the-gst-launch-10-command-to-upload-mkv-file-that-contains-both-audio-and-video as mentioned here am trying to upload a recoded mp4 or mkv files

but am getting the Error
` 2021-06-10 14:39:14 [140697130239744] DEBUG - postWriteCallback(): Curl post body write function for stream with handle: customStream2 and upload handle: 0 returned: {"EventType":"ERROR","FragmentTimecode":1623316156380,"FragmentNumber":"91343852333182690139761976584024119007708395368","ErrorCode":"KMS_KEY_ACCESS_DENIED","ErrorId":4500} `

Though i have full access of AWS Kinesis and S3 buckets. Please suggest if am missing any other required permission? How i can overcome this issue? Any help is appreciated, thanks in advance.

I have also tried with java-producer-code and getting same issue.

**Comment by disa6302** [comment]
@sskant786 ,

Ensure the access permissions you have set are for Kinesis Video Streams. You can follow this to ensure all permissions are set accurately: https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/how-iam.html

Assuming question is answered, I am closing this issue, feel free to reach out if you have any other questions
