### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by williamlai** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#709]
**Logging**
I met the following error while uploading a media file which has 2 tracks (H264 & AAC).

`AckEvent{ackEventType=ERROR, fragmentTimecode=118694, 
fragmentNumber='91343852333181813802008166463739186817407699468', 
errorCode=FRAGMENT_TIMECODE_LESSER_THAN_PREVIOUS, errorId=4004}
`

**Describe the bug**
According to the web doc, this error occurs when fragment timecode less than previous time code.
`4004 - FRAGMENT_TIMECODE_LESSER_THAN_PREVIOUS - Fragment timecode is less than the timecode previous time code (within a PutMedia call, you cannot send fragments out of order).`

I use mkvinfo to check this media file, and the cluster's timecode does not less than previous timecode.

| + Simple block: track number 2, 1 frame(s), timestamp **00:01:58.694000000**
|  + Frame with size 961
|+ Cluster
| + Cluster timestamp: **00:01:58.694000000**
| + Cluster previous size: 282100
| + Simple block: key, track number 1, 1 frame(s), timestamp 00:01:58.694000000

**To Reproduce**
Upload a media file which has same time code of a cluster and the previous simple block.

**Expected behavior**
Since the timecode of cluster **does not lesser than previous one**, there should be no error.

**SDK version number**
Release 3.1.1

**Open source building**

**Screenshots**

**Platform (please complete the following information):**
 - OS: WSL1
 - Processor: 11th Gen Intel(R) Core(TM) i7-1165G7
 - Version 20H2

**Additional context**

**Comment by disa6302** [comment]
@williamlai , 

Not sure what could be happening, but it is important that the frame timestamps are increasing monotonically. This is a backend requirement. Maybe I am missing something, but from your `mkvdump`, I cannot understand the timestamps of subsequent frames. Please ensure the correct [frame order coordinator mode](https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/296adbd889bf7a193dddc65341209863bf397554/src/client/include/com/amazonaws/kinesis/video/client/Include.h#L865) is used for your media pipeline. You can also go through some previous github issues for some recommendations. 

Closing now. Feel free to reopen if you have any other questions.
