### ISSUE TITLE
[QUESTION] how to send metadata( I want to send some info from camera) to kvs?

### ISSUE THREAD

**Issue by keerthanalakshmi8** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#727]
Hello! I'm using gst-launch-1.0 to export video from camera to kvs. I want to add metadata in kvs . GST_EVENT_CUSTOM_DOWNSTREAM is already written in gstkvskink.cpp . But I dont know how to make it work. I'm new to programming. How to issue custom downstream event and make it work?

**Comment by hassanctech** [comment]
Please see this issue:  https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/issues/620

Unfortunately we do not have a sample demonstrating this, but `GST_EVENT_CUSTOM_DOWNSTREAM` is something provided by GStreamer, you can see here: https://gstreamer.freedesktop.org/documentation/gstreamer/gstevent.html?gi-language=c

Please see the guidance provided in the linked issue.
