### ISSUE TITLE
[QUESTION] How can we set log level of kvsproducer/kvssink to Error or Critical?

### ISSUE THREAD

**Issue by Winneee** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#730]
Hi , I am trying to set log level of kvssink .I tried changing log level using log4cplus but no results.
Do i have to make some changes in source code itself before building kvssink or i can set log level from console ??

**Comment by disa6302** [comment]
What do you mean by setting log level in kvssink. There are 2 ways to set up logging config. For GST related logs, you need to use `export GST_DEBUG<level>`. For CPP SDK logs, you need to modify `kvs_log_configuration` file in the samples directory.

**Comment by disa6302** [comment]
Closing assuming answered.
