### ISSUE TITLE
[QUESTION] Is it possible to stream to jpeg?

### ISSUE THREAD

**Issue by noyeah-man** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#732]
A one liner description about the use case and what you are trying to achieve

** Logging **
Add relevent SDK logging.  IMPORTANT NOTE:  Please make sure to NOT share AWS access credentials under any circumstance!  Please make sure they are not in the logs.

** Any design considerations/constraints **
Explain in detail how you would like to integrate our SDK into your solution 

** If you would not like to open an issue to discuss your solution in open-platform, please email your question to kinesis-video-support@amazon.com **

currently streaming rtsp(ip camera) using aws kvs as follows.

**gst-launch-1.0 --gst-debug-level=2 rtspsrc location=rtsp://test@testcctv.iptime.org:554/stream1 \! rtph264depay ! h264parse ! kvssink stream-name="rtsptest1" \storage-size=512 access-key="mykey" secret-key="mykey" aws-region="ap-northeast-2"**

testing it using LTE router from the outside.

However, I want to lower the frame or convert it to jpeg to stream due to insufficient capacity of router.

Is there any other good way?

I ask for your help me. Thank you.

**Comment by disa6302** [comment]
@noyeah-man , 

We only support H.264/H.265. JPEG is not supported. Lowering the frame rate is probably your best option.
