### ISSUE TITLE
How to use Stream Parser Library Java[QUESTION]

### ISSUE THREAD

**Issue by keerthanalakshmi8** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#736]
Help needed. I have added some metadata from producer side using kvs producer cpp. Now I want to retrieve the metadata using Stream Parserr Library. Documentation says that I need to use FragmentMetadataVistitor to retrieve. I am using IntelliJ but I dont know how to use. I checked src test files. I dont know how to start.  Very new to Java. Can anyone tell how to retrieve metadata?

**Comment by hassanctech** [comment]
This is explained in our docs:  https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/how-meta.html#how-meta-consume

We have an example: KinesisVideoRendererExample, here: https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/master/src/main/java/com/amazonaws/kinesisvideo/parser/examples/KinesisVideoRendererExample.java

Here is some relevant information from the docs:

The `BasicMkvTagProcessor.process` method is called when fragment metadata arrives. You can retrieve the accumulated metadata with GetTags. If you want to retrieve a single metadata item, first call clear to clear the collected metadata, and then retrieve the metadata items again.

If you have further questions you can feel free to open a new issue.
