### ISSUE TITLE
[QUESTION] property not freed when finalize

### ISSUE THREAD

**Issue by waikup83** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#745]
There's a reason why property kms_key_id, aws_region, log_config_path and credential_file_path of structure _GstKvsSink (src/gstreamer/gstkvssink.h line 84) are not freed in gst_kvs_sink_finalize (src/gstreamer/gstkvssink.cpp line 644) function ??

**Comment by MushMal** [comment]
A quick look at it seems that it's a bug. I think it's a good candidate for a PR?

**Comment by waikup83** [comment]
What is a PR ?

**Comment by MushMal** [comment]
Oh sorry, a Pull Request. This is an open source project and every contribution is very welcomed.

**Comment by waikup83** [comment]
pull request #746
