### ISSUE TITLE
[QUESTION] unable to build on windows (CURL 32)

### ISSUE THREAD

**Issue by Lepm11** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#749]
HI.
I'm trying to build on windows 10 and I've this error, somebody knows what could be?
I'm using VSC 2019 on x64 native Tools Command prompt 

If anyone could help me I'll be grateful.

![image](https://user-images.githubusercontent.com/53229595/132270095-2443b7ba-4537-44c7-800d-975ba679e994.png)

**Comment by hassanctech** [comment]
We build on Windows in our Travis CI:

https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/.travis.yml#L108-L117

Can you please try that in case you're doing something different?

**Comment by Lepm11** [comment]
> We build on Windows in our Travis CI:
> 
> https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/.travis.yml#L108-L117
> 
> Can you please try that in case you're doing something different?

I still have the same error and I had to reset the pc, currently I was able to execute the command "Nmake MakeFiles" and the files were created correctly, however, when I running the command "cmake .. -DBUILD_GSTREAMER_PLUGIN = ON -DBUILD_JNI = TRUE" it gives me an error this error Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY

can anybody help me?

**Comment by disa6302** [comment]
@Lepm11 , 

We recently updated CMake version in this PR which could solve the issue: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/pull/748

It has not made to the release yet. Can you see if updating CMake helps your case?

**Comment by Lepm11** [comment]
So far i have not been able to install on windows 10, i tried on ubuntu 20.04 and it worked fine. Windows generates many errors

**Comment by Lepm11** [comment]
in my CMakeList had the following route for the gstreamer:

C:\gstreamer\1.0\x86_64\lib

but my gstramer is installed on C:\gstreamer\1.0\msvc_x86_64\lib

so I changed the route from the CMakeList and its worked on windows 10 !!
I was able to installed on Ubuntu 20.04 and Windows 10.
