### ISSUE TITLE
search for memory leak

### ISSUE THREAD

**Issue by waikup83** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#753]
i'm still searching for leak with kvssink when just stopping/ restarting gstreamer without terminating main progam - #682

** Any design considerations/constraints **
- i have 2 appsrc that push audio / video
- not terminating the program, i'm stop and restart gstreamer loop

making kvssink object with :
	KvsSink = gst_element_factory_make("kvssink", "sink");
	g_object_set(G_OBJECT(KvsSink), "stream-name", app->Stream.StreamName, NULL);
	g_object_set(G_OBJECT(KvsSink), "access-key", app->Stream.StreamAccessKey, NULL);
	g_object_set(G_OBJECT(KvsSink), "secret-key", app->Stream.StreamSecretKey, NULL);
	g_object_set(G_OBJECT(KvsSink), "aws-region", app->Stream.StreamRegion, NULL);

**Comment by waikup83** [comment]
many log4cplus problem with kvssink found by valgrind with two silmultanious thread running gstreamer ans kvssink

[valgrindRaw.log](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/files/7225897/valgrindRaw.log)

**Comment by hassanctech** [comment]
Haven't had a chance to investigate but I see you opened another issue:  https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/issues/765

Which is likely why this is happening if it is an issue, I think we need to implement that.  Feel free to submit a PR if you have the change on your side, that is always welcome!

**Comment by disa6302** [comment]
Closing as dup of #765 .
