### ISSUE TITLE
[QUESTION] Running into this error : ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: Internal data stream error.When trying to stream video from webcam to Kinesis video stream

### ISSUE THREAD

**Issue by MohammedJassem** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#760]
I'm trying to stream video from my webcam while using ubuntu on virtualBox I downloaded the extension pack for the webcam and I run an online test to make sure that the webcam is accessible and after setting up the GStreamer plugins as instructed in this git repo : https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp
I tried to run the command which is Example 2: Encode and Stream Video from a USB Camera on Ubuntu : 
$ gst-launch-1.0 v4l2src do-timestamp=TRUE device=/dev/video0 ! videoconvert ! video/x-raw,format=I420,width=640,height=480,framerate=30/1 ! x264enc  bframes=0 key-int-max=45 bitrate=500 ! video/x-h264,stream-format=avc,alignment=au,profile=baseline ! kvssink stream-name="YourStreamName" storage-size=512 access-key="YourAccessKey" secret-key="YourSecretKey" aws-region="YourAWSRegion"

but I run on this error : 
![Screenshot from 2021-09-21 11-04-55](https://user-images.githubusercontent.com/63448996/134143507-8dc85b11-94f3-4edd-b77d-59c4fa3797a1.png)

and I'm new to GStreamer and Kinesis video stream so I'm not sure how to proceed. Please help me

**Comment by hassanctech** [comment]
Please add the `h264parse` GStreamer element immediately before  the `kvssink` in your pipeline and that should resolve your issue.  If it does not please feel free to re-open the issue.
