### ISSUE TITLE
[QUESTION] Missing codec private data error when I watch the video on the console

### ISSUE THREAD

**Issue by Aylaasia-LiYiyang** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#764]
I recived Missing codec private data error when I watch the video on the console.

I know that CPD needs to be passed in when calling kinesis_video_stream->start(cpd).
But i don't know how to generate it.
How to generate correct cpd without using gstreamer?
Can you help me, thanks!

**Comment by disa6302** [comment]
Closing as duplicate of #766.
