### ISSUE TITLE
GST_STATE_CHANGE_READY_TO_NULL status missing ?

### ISSUE THREAD

**Issue by waikup83** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#765]
Thre is no GST_STATE_CHANGE_READY_TO_NULL status, is it missing???

Line 1387 in gstkvssink.cpp file

 For when we want to close stream  and log4cplus, even if the main program is not finished to free memory ?!

**Comment by Aylaasia-LiYiyang** [comment]
solved
