### ISSUE TITLE
[QUESTION] An error occurred when incoming cpd

### ISSUE THREAD

**Issue by Aylaasia-LiYiyang** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#766]
when calling the kinesis_video_stream->start(cpd) interface . I get error  "Failed to get the size of the buffer for hex decoding the codec private data with: 2"。 
Is there a problem with the input cpd?
How to generate it ?
![image](https://user-images.githubusercontent.com/88696397/135038199-5b15809c-3047-4d49-83fe-0c4de37a6ff6.png)

**Comment by hassanctech** [comment]
The error code you see 2 is `STATUS_INVALID_ARG` as defined here:

https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/common/include/com/amazonaws/kinesis/video/common/CommonDefs.h#L465

This is returned here in `hexDecode`:  https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/utils/src/Hex.c#L159

This error is thrown is the value is not properly hex encoded.  Perhaps you can print out your buffer and see what characters are wrong.

**Comment by disa6302** [comment]
@Aylaasia-LiYiyang ,

What commit are you using? Can you reference [this](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/issues/395) ticket for details?

**Comment by Aylaasia-LiYiyang** [comment]
The hexencode is incorrect, I can see the video after I fix it。
