### ISSUE TITLE
[QUESTION] How to check cloud side logs? Video fails to upload after upgrading GStreamer from v1.14 to v1.18

### ISSUE THREAD

**Issue by behnam354** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#774]
We have been successfully using gstreamer 1.14 along with the kinesis_video_gstreamer_audio_video_sample_app and kinesis_video_gstreamer_sample_app pinned to commit f68a506 for uploading video clips (used that commit with the suggestions [here](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/issues/691)). We've recently upgraded the gstreamer version to 1.18 and the videos don't get uploaded to kinesis (although their log on the producer side says `Finished sending file to kvs producer:` with no errors). I was wondering what's the best way to validate if a video is actually uploaded and if there are logs on the cloud side that we can access? I don't see the video when checking the aws kinesis video stream (media playback) page (that was how we used to validate). 

Please find attached the kvs logs on the producer side: [log_for_aws.txt](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/files/7393456/log_for_aws.txt)

Thank you very much!

**Comment by behnam354** [comment]
After further investigating this, we've noticed a bug in the `gstkvssink.cpp` and `kvs_gstreamer_sample.cpp` codes. Mainly there is a `GST_BUFFER_DTS_IS_VALID` check that decides if a frame needs to be dropped or not. The check is invalid if streaming from a file in offline mode.

The check is at [this line ](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/samples/kvs_gstreamer_sample.cpp#L368) in kvs_gstreamer_sample.cpp and [this line](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/c5d0563c24a9163749cdf640b83f1fb8a1583a6f/src/gstreamer/gstkvssink.cpp#L1092) in gstkvssink.cpp code.

As even stated in the code itself few lines after that check[[here](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/c5d0563c24a9163749cdf640b83f1fb8a1583a6f/src/gstreamer/gstkvssink.cpp#L1099), or [here](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/c5d0563c24a9163749cdf640b83f1fb8a1583a6f/samples/kvs_gstreamer_sample.cpp#L376)], in offline mode (e.g. streaming from a file) the dts from gstreamer is undefined and thus the frame will be dropped. Removing the `GST_BUFFER_DTS_IS_VALID` check resolves the upload issue and allows the mkv file to get uploaded.

**Comment by MushMal** [comment]
I don't quite remember why this check was put in place but certainly this works with most of the file uploads. Thinking about this, perhaps the right choice here is to drop the frame if it contains the header and it has no DTS AND no PTS (instead of OR). @hassanctech what's your take on this?
