### ISSUE TITLE
[QUESTION] RTSP stream pipeline gstreamer with buffer

### ISSUE THREAD

**Issue by vbbandeira** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#775]
Hello there folks,
Is it possible to buffer a broadcast from an RTSP stream for content that was recorded by the cameras before the broadcast start time?

I'm recording 2 RTSP streams into a single Kinesis Video Streams stream, the pipeline I used was something like:

```
gst-launch-1.0 rtspsrc location="rtsp://location.com" short-header=TRUE protocols=GST_RTSP_LOWER_TRANS_TCP ! decodebin ! videoconvert ! comp.sink_0 \
rtspsrc location="rtsp://location.com" short-header=TRUE protocols=GST_RTSP_LOWER_TRANS_TCP ! decodebin ! videoconvert ! comp.sink_1 \
compositor name=comp sink_0::xpos=0 sink_1::xpos=1280 ! x264enc ! kvssink stream-name="test-stream" storage-size=512 access-key="access-key" secret-key="secret-key" aws-region="us-east-1" 
```

However, when I launch the Docker Container it takes an average of 12 seconds to initialize and establish transmission with the AWS server. All video content that is recorded during this start time of transmission is lost and this cannot happen.

I found a solution that creates a kind of buffer, but it only buffers the content that is running after the transmission has started, the pipeline I used was something like:

```
gst-launch-1.0 rtspsrc location="rtsp://location.com" short-header=TRUE protocols=GST_RTSP_LOWER_TRANS_TCP ! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 min-threshold-time=10000000000 ! decodebin ! videoconvert ! comp.sink_0 \
rtspsrc location="rtsp://location.com" short-header=TRUE protocols=GST_RTSP_LOWER_TRANS_TCP ! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 min-threshold-time=10000000000 ! decodebin ! videoconvert ! comp.sink_1 \
compositor name=comp sink_0::xpos=0 sink_1::xpos=1280 ! x264enc ! kvssink stream-name="test-stream" storage-size=512 access-key="access-key" secret-key="secret-key" aws-region="us-east-1"
```

Which doesn't apply to my situation, as I need the buffer before the start. In this case, can anyone tell me how to buffer the recorded content before the transmission starts, so I don't lose what was recorded because of the delay?

**Comment by disa6302** [comment]
@vbbandeira , 

This is not relevant to `kvssink`. You will have to handle the buffering yourselves. All the kvssink does is transmit the frames it receives to KVS. GStreamer forums would be a better place to understand how you can achieve this.
