### ISSUE TITLE
[CONTRIBUTION] Only install gstreamer 1.0

### ISSUE THREAD

**Issue by daveisfera** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#776]
** Describe the issue you are trying to solve **
Two versions of gstreamer are installed, but only 1.0 is used

** Details of the changes **
Only install version 1.0 of gstreamer

** Test cases **
Works with the streaming from cameras that I've been testing with

** Additional context **
Would be nice to do the build in a single `RUN` or as a multi-stage build to dramatically reduce the image size, but this is a another simple step in the right direction

**Comment by disa6302** [comment]
Resolving. PR https://github.com/aws-samples/amazon-kinesis-video-streams-demos/pull/199 merged. Thank you!
