### ISSUE TITLE
Internal data streaming error with FLIR Boson camera

### ISSUE THREAD

**Issue by karshee** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#777]
Hi,

We are using the modalai VOXL which hosts a custom linux platform - we installed the SDK in a docker container and can run test RTSP streams fine with no problem. When we try to use the Boson 640, 32° (HFOV) 14 mm camera with this set up we get an internal data streaming error. We have tried many different gst launch commands to no luck and also implemented some of the solutions suggested in this post - 
https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/issues/343

** Logging **

![Selection_003](https://user-images.githubusercontent.com/42929219/138883509-08d2eeb2-9304-44d4-97bb-92a80960d593.png)

gst-launch-1.0 --gst-debug-level=2 -v v4l2src device=/dev/video2 ! video/x-raw,format=I420 ! videoconvert ! video/x-raw, framerate=60/1 ! x264enc bframes=0 key-int-max=5 bitrate=500 tune=zerolatency ! video/x-h264,stream-format=avc,alignment=au ! kvssink stream-name=MyKVStream storage-size=128 access-key="MyAccessKey" secret-key="MySecretKey" aws-region="eu-central-1" 
![Selection_004](https://user-images.githubusercontent.com/42929219/138883549-8043df8b-f61d-485c-b772-5aa03d1fbdc1.png)

gst-launch-1.0 --gst-debug-level=2 -v v4l2src device=/dev/video2 ! video/x-raw,format=GRAY8 ! videoconvert ! video/x-raw, framerate=60/1 ! x264enc bframes=0 key-int-max=5 bitrate=500 tune=zerolatency ! video/x-h264,stream-format=avc,alignment=au ! kvssink stream-name=MyKVStream storage-size=128 access-key="MyAccessKey" secret-key="MySecretKey" aws-region="eu-central-1" 
![Selection_005](https://user-images.githubusercontent.com/42929219/138883610-ebddabe7-7082-4395-9f11-58691b154a5a.png)

** Any design considerations/constraints **
Our end solution is to implement this into a custom drone we are building. We use AWS IoTCore for MQTT messages for handling the telemetry data and are hoping to use kinesis/gstreamer with the FLIR boson camera. We currently have a solution using ffmpeg streaming to an EC2 but there is high latency of around 20s and we need to be able to manage the stream via kinesis in the end solution.

Thank you for your time and any suggestions in the right direction will be much appreciated.

**Comment by disa6302** [comment]
Closing since this is platform specific. Feel free to reopen or create a new issue if it is a KVS specific issue.

**Comment by karshee** [comment]
We have managed to successfully get a working stream to kinesis AWS via the following command - 

gst-launch-1.0 --gst-debug-level=2 -v v4l2src device=/dev/video2 ! video/x-raw,format=RGB,width=640,height=512,framerate=60/1 ! videoconvert ! x264enc bframes=0 key-int-max=45 bitrate=512 tune=zerolatency ! video/x-h264,profile=baseline,stream-format=avc,alignment=au ! kvssink stream-name=MyKVStream storage-size=128 access-key="XXXXXXX" secret-key="XXXXXX" aws-region="eu-central-1"
