### ISSUE TITLE
Building Gstreamer with -DBUILD_STATIC=ON not working

### ISSUE THREAD

**Issue by karshee** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#782]
We are trying to build Gstreamer with the following cmake command - 
cmake .. -DBUILD_GSTREAMER_PLUGIN=ON -DBUILD_DEPENDENCIES=OFF -DBUILD_STATIC=ON -DALIGNED_MEMORY_MODEL=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_OPENSSL_PLATFORM=linux-armv4

and then when we run make - we are given an error.

We are building on an arm64 architecture but we are building inside a docker container with raspian image - FROM resin/rpi-raspbian:stretch .

** Logging **

![Capture](https://user-images.githubusercontent.com/42929219/140333959-ddbd053f-1f17-4860-beec-b4d0f1e9ae96.PNG)

** Any design considerations/constraints **

We are building this on a custom yocto platform on a modalai VOXL that will be streaming via kinesis and communicating with IOTCore, all inside a container - the end goal is to build with -DBUILD_STATIC=ON so we can just extract the gst-launch-1.0 binary file. We can then include just this in our dockerfile for a light and compact container. It would be great if you have the binary files already or were open to any other suggestions to achieve this as the whole SDK is too large to run on the IOT device.

**Comment by disa6302** [comment]
@karshee ,

Can you ensure STATIC build works on a standard platform first?
I see it is unable to find any of the libraries in the paths.

**Comment by karshee** [comment]
Hey, 
since we have got it working with -DBUILD_STATIC=ON - we first encountered errors of samples failing so we commented out the following lines in CMakeLists.txt 
![editing CMakeLists txt](https://user-images.githubusercontent.com/42929219/140906445-e299f43d-b0f5-44ca-94e5-2652070bed21.JPG)

and the video stream worked with the following outcome after the build -
![make without changing cmakefile](https://user-images.githubusercontent.com/42929219/140906462-2b0ee0a2-60ac-4a66-92b7-7bbccf8cd38a.JPG)
 
but when we try to run the gst-launch-1.0 binary file outside the container we are missing dependencies, we tried copying everything in the build folder over too but x264enc and kvssink are still seen as missing. 
![gst-launch-1 0 outside container](https://user-images.githubusercontent.com/42929219/140906615-7775784f-1813-4fbe-8969-e8a693aa6fa3.JPG)

**Comment by karshee** [comment]
we used this CMAKE command - 
cmake .. -DBUILD_GSTREAMER_PLUGIN=ON -DBUILD_DEPENDENCIES=OFF -DBUILD_STATIC=ON -DALIGNED_MEMORY_MODEL=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_OPENSSL_PLATFORM=linux-armv4

**Comment by disa6302** [comment]
No element "x264enc" indicates that the gstreamer plugins have not been installed successfully. To verify it is a linking issue, can you try to build the SDK without  `-DBUILD_STATIC=ON` and see if it works?

**Comment by karshee** [comment]
Yes it works without -DBUILD_STATIC=ON but our goal is to minimize the overall size of the docker container. We wanted to use -DBUILD_STATIC=ON to try and build the binary files then extract them and just use them in our own dockerfile. Will this work ? or do you have any other suggestions to minimizing the size of the overall kinesis sdk docker container ? as were running it on an IOT device so require minimal storage usage.

**Comment by disa6302** [comment]
As long as your docker container has access to the library paths, it would work. I am closing this now. Please feel free to reach out if you have any more questions.
