### ISSUE TITLE
[QUESTION]  Where to run cmake for Gstreamer?

### ISSUE THREAD

**Issue by akazakci** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#789]
Hi,
I am trying to stream USB camera stream from a raspberry to kinesis.

On the raspberry documentation (/raspberry-pi.md), it is mentioned:
"Ensure you run cmake with BUILD_GSTREAMER_PLUGIN=ON option from build directory"

I am confused as to where I should run this command. Should I locate where the gstreamer has been installed on the OS, find the build folder under it and run a cmake?

Thanks.

**Comment by disa6302** [comment]
Please follow the steps before that. You need to create a build folder in the repo and run from that.
