### ISSUE TITLE
cert.pem not found? 

### ISSUE THREAD

**Issue by HelloEgg** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#79]
Hi. I referred to previous issues on http 0 response.

WARN - HTTP Error 0: Response:
Request URL: https://kinesisvideo.us-west-2.amazonaws.com/describeStream
Request Headers:

So I downloaded the pem, reinstalled the curl and rebooted.

Although cert.pem does exist in etc/ssl folder, kinesis_video_gstreamer_sample_app still wouldn't pick up cert.pem.

Strance thing is that if I run ./curl-config –ca it correctly returns the path value.

Eventually it yields the following error:

describeStreamResultEvent(): Describe stream result event.ERROR - Submitting event result for stream: 4081058 failed with: 1375731728
ERROR - Reporting stream error. Errored timecode: 0 Status: 1375731728
ERROR - Failed to create Kinesis Video Stream - timed out.
terminate called after throwing an instance of 'std::runtime_error'
what(): Failed to create Kinesis Video Stream - timed out.
Aborted

For now, I'm just reinstalling the whole process again, hopefully it would end in 4 hours..
Does anybody ran into similar issue?

**Comment by HelloEgg** [comment]
I’m running it on ubuntu mate of raspberry pi.
Camera model is standard pi camera.

Would it matter deeply?

I’m curious if similar error would occur should I change the camera model in later time.

**Comment by unicornss** [comment]
Thanks for the details.  Are you seeing 

> error setting the certificate verify locations:
  CAfile: /etc/ssl/cert.pem

 in the logs? 

If so, can you please see if the file exists in that directory  `ls -al /etc/ssl/cert.pem` ?

Regarding your other question, the camera type is not related to this cert issue; typically, the Pi camera module is able to send video frames faster than a USB camera.

**Comment by HelloEgg** [comment]
Here is the full error log.. Thank you so much in advance


ERROR - curl perform failed for url https://kinesisvideo.us-west-2.amazonaws.com/describeStream with result Problem with the SSL CA cert (path? access rights?): error setting certificate verify locations:
  CAfile: /etc/ssl/cert.pem
  CApath: none
WARN - HTTP Error 0: Response: 
Request URL: https://kinesisvideo.us-west-2.amazonaws.com/describeStream
Request Headers:
    
    content-type: application/json
    host: kinesisvideo.us-west-2.amazonaws.com
    X-Amz-Date: 20180517T114802Z
DEBUG - describeStream response: 
INFO - Describe stream did not find the stream oceanbridge01 in Kinesis Video (stream will be created)
INFO - 
describeStreamResultEvent(): Describe stream result event.
DEBUG - describeStreamHandler invoked
INFO - Refreshing credentials. Force refreshing: 0 Now time is: 1526557682 Expiration: 0
ERROR - curl perform failed for url https://kinesisvideo.us-west-2.amazonaws.com/describeStream with result Problem with the SSL CA cert (path? access rights?): error setting certificate verify locations:
  CAfile: /etc/ssl/cert.pem
  CApath: none
WARN - HTTP Error 0: Response: 
Request URL: https://kinesisvideo.us-west-2.amazonaws.com/describeStream
Request Headers:
    
    content-type: application/json
    host: kinesisvideo.us-west-2.amazonaws.com
    X-Amz-Date: 20180517T114802Z
DEBUG - describeStream response: 
INFO - Describe stream did not find the stream oceanbridge01 in Kinesis Video (stream will be created)
INFO - 
describeStreamResultEvent(): Describe stream result event.
DEBUG - describeStreamHandler invoked
INFO - Refreshing credentials. Force refreshing: 0 Now time is: 1526557683 Expiration: 0
ERROR - curl perform failed for url https://kinesisvideo.us-west-2.amazonaws.com/describeStream with result Problem with the SSL CA cert (path? access rights?): error setting certificate verify locations:
  CAfile: /etc/ssl/cert.pem
  CApath: none
WARN - HTTP Error 0: Response: 
Request URL: https://kinesisvideo.us-west-2.amazonaws.com/describeStream
Request Headers:
    
    content-type: application/json
    host: kinesisvideo.us-west-2.amazonaws.com
    X-Amz-Date: 20180517T114803Z
DEBUG - describeStream response: 
INFO - Describe stream did not find the stream oceanbridge01 in Kinesis Video (stream will be created)
INFO - 
describeStreamResultEvent(): Describe stream result event.
DEBUG - describeStreamHandler invoked
INFO - Refreshing credentials. Force refreshing: 0 Now time is: 1526557684 Expiration: 0
ERROR - curl perform failed for url https://kinesisvideo.us-west-2.amazonaws.com/describeStream with result Problem with the SSL CA cert (path? access rights?): error setting certificate verify locations:
  CAfile: /etc/ssl/cert.pem
  CApath: none
WARN - HTTP Error 0: Response: 
Request URL: https://kinesisvideo.us-west-2.amazonaws.com/describeStream
Request Headers:
   
    content-type: application/json
    host: kinesisvideo.us-west-2.amazonaws.com
    X-Amz-Date: 20180517T114804Z
DEBUG - describeStream response: 
INFO - Describe stream did not find the stream oceanbridge01 in Kinesis Video (stream will be created)
INFO - 
describeStreamResultEvent(): Describe stream result event

**Comment by HelloEgg** [comment]
another question : /etc/ssl/cert.pem means that cert.pem existing in directory /etc/ssl right???

**Comment by HelloEgg** [comment]
Yup!  Originally, it was limited to root user so I "chmod 400"ed cert.pem.

if I run

ls -al /etc/ssl/cert.pem

it returns "-r--------1 root root 1438"

I referred the following solution:

https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/issues/40.

I followed this solution after chmod 400 cert.pem.

This again yields http error 0, which is same error as above..

**Comment by HelloEgg** [comment]
Also,

curl https://kinesisvideo.us-west-2.amazonaws.com

<MissingAuthenticationTokenException>
<Message>Missing Authentication Token</Message>
</MissingAuthenticationTokenException>

Even though ls -l yields value. Thank you so much in advance!

**Comment by HelloEgg** [comment]
Okay, so I've been goofing around all weekends and here's what I found out:

I kept changing the directory however in vein.

It looks like .curlrc file handles the path of certificate. 
Just in case if program cannot get root access, I tried putting .pem file in Desktop or working directory.

Result is, as expected not working though. 

while following solution in #40 ,  I tried putting wrong directory on purpose

./configure --prefix=$DOWNLOADS/local/ --enable-dynamic --disable-rtsp --disable-ldap --without-zlib --with-ssl=$DOWNLOADS/local/ --with-ca-bundle=/etc/ssl/cert.pem

to 

./configure --prefix=$DOWNLOADS/local/ --enable-dynamic --disable-rtsp --disable-ldap --without-zlib --with-ssl=$DOWNLOADS/local/ --with-ca-bundle=/foo/bar

Of course, after installation, log said that they could not find pem file.

After setting the path file correctly to /etc/ssl/cert.pem, it did locate pem file correctly and did not show error as above..

Also, ./curl-config --ca yields /etc/ssl/cert.pem correctly though

So as a last solution, now I am attempting to put k flag in curl installation file as @JulianKling did in #47 
Do you know how I can do that??

**Comment by HelloEgg** [comment]
[Solved]
Here's an interesting turn of event. 
I've found out that by default, certs are stored in /etc/ssl/certs/ca-certificates.crt

So, I tried adding  contents of cert.pem inside that .crt instead of redirecting the path to etc/ssl.

After, I ran ./configure --prefix=$DOWNLOADS/local/ --enable-dynamic --disable-rtsp --disable-ldap --without-zlib --with-ssl=$DOWNLOADS/local/ --with-ca-bundle=/etc/ssl/certs/ca-certificates.crt

It looks like one of the following should be the reason.
A. curl tries to pick up ca-certificates.crt but redirecting to /etc/ssl/cert.pem causes conflict.
This seems to be unlikely because curl did pick up /etc/ssl/cert.pem. However, we'll never know what Ubuntu would do.. do we?
B.  Writing cert.pem with root access and giving root read permission is not good enough for curl to pick up cert.pem
This seems to be some extra work with ubuntu mate, which seems to be more strict on accessing root file directory. 

If anyone should ever encounter problem that I faced, do add cert.pem to ca-certificates.crt, especially ubuntu mate users.
P.S ca-certificates.crt seems to be file that collected all possible certicates. Also ca-certificate application does attempt to read certificates from ca-certificates.crt. I guess amalgamation of all of these factors above could have contributed to problem. Anyhow, this case is resolved.

**Comment by unicornss** [comment]
Hi @HelloEgg,
We tried in the virtual machine of Ubuntu (MATE) 17.10  and the error does not show if the `/etc/ssl/cert.pem` is present. It shows the error only if the file is **not** present.  

For your reference the directory contents of `/etc/ssl`  shows as follows:

```
labs-VirtualBox:/etc/ssl$ ls -alrt
total 56
-rw-r--r--   1 root root     10835 May 19  2017 openssl.cnf
drwx--x---   2 root ssl-cert  4096 May  9 17:34 private
drwxr-xr-x   2 root root     20480 May  9 17:34 certs
-rw-r--r--   1 root root      1424 May 10 11:16 cert.pem
drwxr-xr-x   4 root root      4096 May 10 11:17 .
drwxr-xr-x 134 root root     12288 May 21 08:40 ..
labs-VirtualBox:/etc/ssl$
```

**Comment by unicornss** [comment]
Hi @HelloEgg 

Thanks for the note to resolve the curl cert issue in the

>  ubuntu mate of raspberry pi

.
