### ISSUE TITLE
WARNING: erroneous pipeline: no element "kvssink"

### ISSUE THREAD

**Issue by THESOCK1999** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#795]
I am trying to stream my webcam to aws kinesis using gstreamer.

I am using the command "gst-launch-1.0 -v v4l2src device=/dev/video0 ! videoconvert ! video/x-raw,format=I420,width=640,height=480,framerate=30/1 ! x264enc  bframes=0 key-int-max=45 bitrate=500 tune=zerolatency ! video/x-h264,stream-format=avc,alignment=au ! kvssink stream-name=.. storage-size=128 access-key=.. secret-key=.."

It then prints the error "WARNING: erroneous pipeline: no element "kvssink"".

I have looked at other solutions on here but I cannot get it to work on my device.

**Comment by disa6302** [comment]
Please ensure the following 2 things:

1. KVS Sink Library exists in the build directory
2. You have run `export GST_PLUGIN_PATH=<path to build folder>`

Please follow the instructions in the README. You can search other past issues as well to get some answers. Closing.

**Comment by THESOCK1999** [comment]
I keep seeing a reference to the build directory. What does this refer to?

**Comment by THESOCK1999** [comment]
Could someone advise me on how I can find/create the build directory?

**Comment by disa6302** [comment]
Again, please follow the readme. 

1. Create a build directory in the root of the repository
2. Move to build directory
3. Run `cmake.. -DBUILD_GSTREAMER_PLUGIN=ON`
4. Run `make`
5. Export the library path
6. Run the sample

**Comment by THESOCK1999** [comment]
When you say root repository, what are you referring to?

**Comment by THESOCK1999** [comment]
I am very new to these programs, and I would really appreciate the help

**Comment by THESOCK1999** [comment]
Does this refer to the /usr directory or is it something else?

**Comment by THESOCK1999** [comment]
Do you need to create your own repository or are you referring to an existing repository?

**Comment by THESOCK1999** [comment]
Could somebody please assist me in understanding this?

**Comment by THESOCK1999** [comment]
I would really appreciate some help on the matter as I cannot find any information to assist me with the instructions that you have given

**Comment by niyatim23** [comment]
By root of the directory, we mean the root directory of this GitHub repository on your system. The file structure should be like 
`amazon-kinesis-video-streams-producer-sdk-cpp/build` where 
`amazon-kinesis-video-streams-producer-sdk-cpp` is the folder created when you cloned the repository. Then, you `cd` into the build directory and perform steps 3 to 6

**Comment by THESOCK1999** [comment]
I did every step like you advised and yet when I run the command "gst-inspect-1.0 kvssink" I get the response "No such element or plugin 'kvssink'" are there any other steps that I can follow to ensure that I didn't do something wrong?
