### ISSUE TITLE
[BUG] Kvssink attribute "file-start-time" is not working with milliseconds

### ISSUE THREAD

**Issue by ReydanFly** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#796]
**Logging**
Relevent SDK logging is attached.

**Describe the bug**
I'm using gst-launch-1.0 and noticed that when uploading video chunks to KVS with the gstreamer kvssink plugin attribute "file-start-time" in **milliseconds** the video stream is created normally but the video chunks can not be found on the stream. Executed command:
`gst-launch-1.0 -v filesrc location=/tmp/P14oRaLFSzeM6JKLHOAV.mp4 do-timestamp=TRUE ! qtdemux name=demux ! queue ! h264parse ! video/x-h264,stream-format=avc,alignment=au ! kvssink name=sink stream-name=HFG_TEST_MILLI streaming-type=offline file-start-time=1637072264103 retention-period=720 demux. ! queue ! aacparse ! sink.`

In the logs I can see many warnings like this:
`1637072274282,"2021-11-16 14:17:54 [140606888503040] WARN - putKinesisVideoFrame(): Failed to submit frame to Kinesis Video client. status: 0x3200000b decoding timestamp: 0 presentation timestamp: 137587856165594577
...`

When executing the same command with the "file-start-time" attribute in seconds than everything works as expected and the chunks are available in the stream.

**Expected behavior**
The video chunks should be uploaded to KVS with the "file-start-time" attribute in milliseconds into the stream.

**SDK version number**
3.2.0

**Additional context**
[log-events-viewer-result.csv](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/files/7548097/log-events-viewer-result.csv)

**Comment by disa6302** [comment]
@ReydanFly ,

File start time must be in seconds. Milliseconds is not allowed. Please see this line of code: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/src/gstreamer/gstkvssink.cpp#L566

Resolving since question is answered.
