### ISSUE TITLE
Stream audio and video from RSTP source 

### ISSUE THREAD

**Issue by luisberga** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#798]
I'm using the [docker-rtsp](https://github.com/aws-samples/amazon-kinesis-video-streams-demos/tree/master/producer-cpp/docker-rtsp) example to produce a rtsp stream. Shall be possible to stream both audio and video? I'm issuing only video (without audio) from a rtsp audio-video source. 

Thanks

**Comment by daave01** [comment]
Hola justo necesito hacer lo que haces tu, sin audio.. tienes alguna guia para lograr eso?

**Comment by luisberga** [comment]
Not yet =/
