### ISSUE TITLE
Build issue on Pi caused by certificate (with solution)

### ISSUE THREAD

**Issue by juliensimon** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#81]
Great repo, thank you.

I just had a minor issue when building the native client. The certificate linked on the repo page didn't work for me. curl failed with 'unable to get local issuer certificate'.

Using the certificate located at https://curl.haxx.se/ca/cacert.pem solved the issue.

Everything else went smoothly and I could stream successfully.

**Comment by MushMal** [comment]
@juliensimon thanks for the feedback. We will look into it. Also, you are super welcome to do a pull request with your changes :)

**Comment by karthickvalentino** [comment]
Should I replace the downloaded file from https://www.amazontrust.com/repository/SFSRootCAG2.pem. I did everything as mentioned but still facing curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html.

I'm using Raspberry Pi 3, model B.

I'm not able to run ./curl-config --ca.
My file structure for ssl is 
/etc/ssl
/etc/ssl/cert.pem
/etc/ssl/certs/
/etc/ssl/private/

I have given permission for all user.

**Comment by karthickvalentino** [comment]
Sorry my bad. I followed the instruction from https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#curl-ssl-issue---unable-to-get-local-issuer-certificate and worked.
