### ISSUE TITLE
[BUG] Stability issue - Streaming stops after 40 mins with a crash

### ISSUE THREAD

**Issue by vaishna-11** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#810]
**Logging**
[INFO ][2022-01-14 23:46:02] Streaming from rtsp source
New pad found: recv_rtp_src_0_41030_96
[INFO ][2022-01-14 23:46:04] Pad link successful
[INFO ][2022-01-14 23:46:04] kinesisVideoStreamFormatChanged(): Stream format changed.
[INFO ][2022-01-14 23:46:04] putStreamResultEvent(): Put stream result event. New upload handle 0
[WARN ][2022-01-14 23:46:04] notifyDataAvailable(): Failed to un-pause curl with error: 43. Curl object 0x207cf720
[INFO ][2022-01-14 23:46:04] writeHeaderCallback(): RequestId: dff2c9f2-90d5-63eb-85ae-c48e4c2a638f

[INFO ][2022-01-15 00:22:59] writeHeaderCallback(): RequestId: 6d42b051-4246-4897-85d8-c62c2745e474
[INFO ][2022-01-15 00:22:59] getStreamingEndpointResultEvent(): Get streaming endpoint result event.
[INFO ][2022-01-15 00:22:59] getStreamingTokenResultEvent(): Get streaming token result event.
[INFO ][2022-01-15 00:22:59] putStreamResultEvent(): Put stream result event. New upload handle 1

**Describe the bug**
While streaming from the rtsp source, the app crashes after 35mins with SEGV.

**To Reproduce**
export AWS_ACCESS_KEY_ID=xxx
export AWS_SECRET_ACCESS_KEY=xxx
./kvs_gstreamer_sample stream_name src_url

**Expected behavior**
Stream should continue to play and the application is not expected to crash.

**SDK version number**
3.2.0

**Screenshots**
Link to the core file - https://1drv.ms/u/s!Ans-vGL_x4lnlRWsMSGSBn9Ku1HN?e=wF7nTx

**Platform (please complete the following information):**
uname -a
OpenWRT Linux 5.4.158 aarch64 GNU/Linux
gstreamer - gstreamer-1.18.1

**Comment by kateyanurag** [comment]
@vaishna-11 a few questions - 
(1) Is this consistently reproducible? 
(2) Have you noticed this crash each time the sample is run for ~40mins or it was just a one-off occurrence?  
(3) How much memory does your device have? Have you confirmed that this is not due to device memory exhaustion?

**Comment by vaishna-11** [comment]
Please find the answers.
1. yes, the issue is consistently reproducible.
2. Issue happens almost most of the times after streaming for approx 40mins. it is not one-off occurence.
3. yes, this is not a memory issue. we have monitored the memory usage while the tests were run.

**Comment by vaishna-11** [comment]
Update:
We are able to recreate the issue much faster when we change DEFAULT_CREDENTIAL_ROTATION_SECONDS to smaller value.

**Comment by disa6302** [comment]
@vaishna-11 ,

What credential provider are you using?

**Comment by vaishna-11** [comment]
This test was based on access secret key. how do we confirm the same for the certificate files?

**Comment by kateyanurag** [comment]
@vaishna-11 I tried reproducing this issue but was not able to see the failure.
Did you make any other code changes in the sample code?

**Comment by niyatim23** [comment]
By "credential provider" we're trying to understand which of the providers listed [here](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/docs/auth.md#kvs-sdk-auth-integration) are you using?

**Comment by MushMal** [comment]
@vaishna-11 rotating credential provider is designed for test purposes only. If you have static credentials such as AWS access key and secret key then you should be using static credentials provider. Most likely, your provider is setting the credential expiration to an expired date/time. What I don't understand is whether this is causing a crash and what's crashing.

* Have the software stabilized on a commodity platform prior flushing on your device
* Ensure the stock samples work on your device before modifying so you can debug your own issues
* Include the detailed crash stack in verbose mode so someone could help perhaps looking at your stack
* For devices, either use IoT credential provider or something similar - don't hard-code static credentials on the device (and hence use Static credential provider).

**Comment by vaishna-11** [comment]
> @vaishna-11 I tried reproducing this issue but was not able to see the failure. Did you make any other code changes in the sample code OR anywhere in the SDK?
> 
> Also what is your rtsp source? I used file as a source in my testing.

@kateyanurag 
No changes were done on the sample app for this testing. 
Source we are trying to use is the rtsp url in the network, as mentioned in the steps to reproduce.
**./kvs_gstreamer_sample stream_name src_url**
**./kvs_gstreamer_sample kvs_example_camera_stream rtsp://192.168.137.1:8554/mystream**

**Comment by vaishna-11** [comment]
@MushMal  @niyatim23 

From our application, we are using IoT based credential provider which makes use of Curl client.
We observed the crash in our application every ~40mins while streaming. We tried playing around the value MAX_ENFORCED_TOKEN_EXPIRATION_DURATION to 3mins and could see that application crashed in 3mins.

So tried similar approach on the sample app too with access/secret key and could recreate the issue and the same happened there as well. There were no changes done at the sample app side.

**Comment by disa6302** [comment]
@vaishna-11 , 

The stack trace you provided seems to be a binary of sorts. It does not have any information to go with it. I have also run the sample as is with default credentials locally and I am unable to reproduce the crash. 
Can you please provide a stack backtrace? You can use `bt` in `gdb` to generate this. Thanks!

**Comment by disa6302** [comment]
Cloding due to no response. We are unable to reproduce this. Please feel free to reopen.
