### ISSUE TITLE
stream audio and video from RTSP source 

### ISSUE THREAD

**Issue by Heena2411** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#812]
Hi 
I am using amazon-kinesis-video-streams-producer-sdk-cpp, tying to play audio+video data directly from RTSP source.
While playing RTSP URL in VLC, able to get audio+video.
Using same RTSPsrc, what changes are required to get audio data over Kinesis server. can anyone please check.

Note : I have added below changes 
Replaced DEFAULT_CONTENT_TYPE "video/h264" macro with "video/h264,audio/aac"
Added separate Track and pipeline for audio. 

Getting below messages contentiously while playing the stream. 
[WARN ] [03-02-2022 14:34:21:371.218 GMT] putKinesisVideoFrame(): Failed to submit frame to Kinesis Video client. status: 0x52000085 decoding timestamp: 32778115 presentation timestamp: 16438988555499550
0:00:03.307935980 1900668 0x7f788001c360 WARN            rtpmp4gdepay gstrtpmp4gdepay.c:684:gst_rtp_mp4g_depay_process:<depay_audio> Detected ADTS header of 7 bytes, skipping
[WARN ] [03-02-2022 14:34:21:387.127 GMT] putKinesisVideoFrame(): Failed to submit frame to Kinesis Video client. status: 0x52000085 decoding timestamp: 32933862 presentation timestamp: 16438988555385407
[WARN ] [03-02-2022 14:34:21:441.332 GMT] putKinesisVideoFrame(): Failed to submit frame to Kinesis Video client. status: 0x52000085 decoding timestamp: 33480239 presentation timestamp: 16438988555692921
0:00:03.375690568 1900668 0x7f788001c360 WARN            rtpmp4gdepay gstrtpmp4gdepay.c:684:gst_rtp_mp4g_depay_process:<depay_audio> Detected ADTS header of 7 bytes, skipping

**Comment by niyatim23** [comment]
Hi @Heena2411, there seems to be an issue with your decoding and presentation timestamps. The error code `0x52000085` indicates `STATUS_MAX_FRAME_TIMESTAMP_DELTA_BETWEEN_TRACKS_EXCEEDED`. Please refer to how the timestamps are set in the [samples](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/samples/kvs_gstreamer_multistream_sample.cpp#L188-L189) to fix this. 

Closing assuming answered, feel free to reopen in case of further questions/issues
