### ISSUE TITLE
Help/Assistance Required for building Producer SDK in Raspi

### ISSUE THREAD

**Issue by Akill047** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#841]
Amazon-Kinesis-Video-streams-producer-sdk-cpp.

Trying to install this producer SDK in my Raspberry pi. Trying to deploy an IP camera. But having trouble in Building the SDK and required libraries. Can you please help me find a proper document which i can follow or help me  in any way possible. 

My Status so far : 

- Built all the necessary libraries except this following. (Getting some errors.)

> [$ sudo apt-get install libssl-dev libcurl4-openssl-dev liblog4cplus-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-base-apps gstreamer1.0-plugins-bad gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-tools]

![Screenshot (82)](https://user-images.githubusercontent.com/93131356/160806124-97846b0c-7856-4925-bb3e-eb77131bdc09.png)
![Screenshot (83)](https://user-images.githubusercontent.com/93131356/160806133-2d1575f6-8eeb-4ac3-92db-004ece89ceec.png)
![Screenshot (84)](https://user-images.githubusercontent.com/93131356/160806135-26b7936a-675f-4ea4-af07-3542faafe2f4.png)
![Screenshot (85)](https://user-images.githubusercontent.com/93131356/160806137-795a295e-1c90-4723-b204-4238173ae644.png)

**Comment by niyatim23** [comment]
Hi @Akill047, I see the same Java error as https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/issues/841 
Closing this issue, let us discuss it on the other ticket. Feel free to reopen / open a new issue for another issue
