### ISSUE TITLE
[QUESTION]  "No package 'libcurl' found" error during cmake on MacOS 12.3 (M1)

### ISSUE THREAD

**Issue by yoi-hibino** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#842]
Hi, I have a problem to build gstreamer plugin on my MacOS 12.3 (M1).  Run

cmake .. -DBUILD_GSTREAMER_PLUGIN=ON -DBUILD_DEPENDENCIES=OFF

and get error as follows:
-- Checking for module 'libcurl'
--   No package 'libcurl' found
CMake Error at /opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/FindPkgConfig.cmake:603 (message):
  A required package was not found
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/FindPkgConfig.cmake:825 (_pkg_check_modules_internal)
  dependency/libkvscproducer/kvscproducer-src/CMakeLists.txt:146 (pkg_check_modules)

I installed curl via homebrew, and I see libcurl.dylib, libcurl.a and libcurl.4.dylib under /opt/homebrew/lib. Do I miss anything? Do I need to configure package information for cmake? Please give me advice. Thanks!

**Comment by yoi-hibino** [comment]
Solved by setup pkg-config. Thanks.

**Comment by giuseppe16180** [comment]
Hi, I have encountered the same problem but could not find a solution. Probably my knowledge of CPP projects is not enough, could you give me some more guidance?
