### ISSUE TITLE
[QUESTION] KVSSink without Gstreamer

### ISSUE THREAD

**Issue by diegocatalao** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#848]
KVS sdk library without gstreamer implementation.

Hello, folks

I've been using kvssink successfully with gstreamer. But I wonder if it is possible to use without it. Can I get the kvs-only documentation without gstream? Is this possible or is the lib only designed for gst?

**Comment by MushMal** [comment]
KVS producer SDKs are independent of GStreamer. You can use the C++ version of the SDK directly from this repository or the C version from https://github.com/awslabs/amazon-kinesis-video-streams-producer-c

**Comment by disa6302** [comment]
Closing assuming answered.

**Comment by diegocatalao** [comment]
Do you have an example demonstrating the use without gstreamer?
