### ISSUE TITLE
KVS producer SDKs are independent of GStreamer. You can use the C++ version of the SDK directly from this repository or the C version from https://github.com/awslabs/amazon-kinesis-video-streams-producer-c

### ISSUE THREAD

**Issue by diegocatalao** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#856]
KVS producer SDKs are independent of GStreamer. You can use the C++ version of the SDK directly from this repository or the C version from https://github.com/awslabs/amazon-kinesis-video-streams-producer-c

_Originally posted by @MushMal in https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/issues/848#issuecomment-1106769461_

Do you have an example demonstrating the use without gstreamer?

**Comment by MushMal** [comment]
It seems that most of the non-gst samples that use pre-packaged frames are in the C producer SDK. You could try to follow those samples and plug-in your media source pipeline. The minimalist sample would be something like creating a producer object, creating a stream object off of the producer and then going into the loop putting frames into the stream. The details are around the callbacks that can be specified to handle the non-default behaviors when it comes to error handling or buffer pressures and the fact that in non-sample cases the developers would need to tie-up the frame production loop with the media pipeline of the actual device they are targeting.
