### ISSUE TITLE
[QUESTION] Does aws kinesis video stream keeps track of current number of users watching the stream? If so how can i get it?

### ISSUE THREAD

**Issue by nivishree** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#862]
Does AWS Kinesis keep tracks of number of users currently watching the stream? For instance if no one is watching the stream the count should be 0, and if 10 people are watching the count should be 10. If so, how to get that data or is there any other way this data can be fetched?

**Comment by disa6302** [comment]
@nivishree,

There is no such mechanism within the SDK. And there is no such mechanism in the console either. The closest metric you can get is GetMediaRequest count or HLS/DASH playback count based on how the stream is being viewed or consumed. But, it is upto the customer to have a centralized mechanism to track number of users watching the stream.
