### ISSUE TITLE
Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY)

### ISSUE THREAD

**Issue by JacopoBandoni** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#866]
I'm trying to install the SDK on a macOS Big Sur version 11.4 on a MacBook Pro.

**### Logging**
Couldn't able to build cmake with Gstreamer and JNI without any errors.

**### To Reproduce**
I performed the following commands in order:
1 - `$ brew install pkg-config openssl cmake gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly log4cplus gst-libav`
2 - `git clone https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp.git`
3 - `mkdir -p amazon-kinesis-video-streams-producer-sdk-cpp/build`
4 - `cd amazon-kinesis-video-streams-producer-sdk-cpp/build`
4 - `cmake .. -DBUILD_GSTREAMER_PLUGIN=ON -DBUILD_JNI=TRUE`

At this point I get the following error:

```
CMake Error at /usr/local/Cellar/cmake/3.23.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.23.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.23.2/share/cmake/Modules/FindJNI.cmake:367 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:189 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/jacopobandoni/Desktop/prova/amazon-kinesis-video-streams-producer-sdk-cpp/build/CMakeFiles/CMakeOutput.log".
See also "/Users/jacopobandoni/Desktop/prova/amazon-kinesis-video-streams-producer-sdk-cpp/build/CMakeFiles/CMakeError.log".
(base) jacopobandoni@MacBook-Pro-di-Jacopo build % cmake --version
cmake version 3.23.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Considerations**
By checking the following issue (https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/issues/843) I noted that I should have defined the JAVA_HOME variable.

But even after setting:
`export JAVA_HOME=/usr/local/Cellar/openjdk/18.0.1`
`export JAVA_INCLUDE_PATH2=$JAVA_HOME/include`

in command line or in .zshrc the previous error stay the same.

**Comment by niyatim23** [comment]
Hi @JacopoBandoni, can you add check if the paths in the following section exist on your Mac and add these lines to the cmake file [here](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/CMakeLists.txt#L33) and see if that works for you?
```
if(APPLE)
      SET(JAVA_INCLUDE_PATH "$ENV{JAVA_HOME}/include")
      SET(JAVA_INCLUDE_PATH2 "/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers/")
      SET(JAVA_AWT_LIBRARY "$ENV{JAVA_HOME}/lib/libawt.dylib")
      SET(JAVA_JVM_LIBRARY "$ENV{JAVA_HOME}/lib/server/libjvm.dylib")
      set(JAVA_AWT_INCLUDE_PATH "$ENV{JAVA_HOME}/include")
  endif()
```

**Comment by niyatim23** [comment]
Closing due to no response. Feel free to reopen the issue in case of any concerns
