### ISSUE TITLE
Unable to stream the video from my webcam to Kinesis Video Stream (on mac)

### ISSUE THREAD

**Issue by keerthanvp** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#867]
Hi,
I need to stream the video from my webcam (on mac) continuously to Kinesis Video Stream.
I have tried running the commands mentioned in [this](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/docs/macos.md) documentation.
I'm getting the following error,
```
ERROR: from element /GstPipeline:pipeline0/GstAVFVideoSrc:avfvideosrc0: Internal data stream error.
Additional debug info:
../libs/gst/base/gstbasesrc.c(3127): gst_base_src_loop (): /GstPipeline:pipeline0/GstAVFVideoSrc:avfvideosrc0:
streaming stopped, reason not-negotiated (-4)
[INFO ] [31-05-2022 11:19:40:359.064 UTC] stopKinesisVideoStreamSync(): Synchronously stopping Kinesis Video Stream 00007fe725037010.
```
```
ERROR: from element /GstPipeline:pipeline0/GstAutoVideoSrc:autovideosrc0/GstAVFVideoSrc:autovideosrc0-actual-src-avfvide: Internal data stream error.
Additional debug info:
../libs/gst/base/gstbasesrc.c(3127): gst_base_src_loop (): /GstPipeline:pipeline0/GstAutoVideoSrc:autovideosrc0/GstAVFVideoSrc:autovideosrc0-actual-src-avfvide:
streaming stopped, reason not-negotiated (-4)
[INFO ] [31-05-2022 11:24:29:732.792 UTC] stopKinesisVideoStreamSync(): Synchronously stopping Kinesis Video Stream 00007fd184089c10.
```

I have verified if my webcam is working fine and i'm able to use it for any video calls or meetings.
I have also tried the following command,
`gst-device-monitor-1.0`
and i see the following error,
```
Probing devices...

Failed to start device monitor!
```
I have tried connecting external webcam and I still see the same errors.
I have done the JNI setup as described in the documentation and I'm able to stream existing sample videos but unable to stream from my webcam.

Kindly help me with this, thank you in advance.

**Comment by disa6302** [comment]
The error seems to be coming from your pipeline. Try out other sinks apart from kvssink to ensure your pipeline works.
