### ISSUE TITLE
[BUG] - No CMAKE_CXX_COMPILER could be found on Ubuntu 22.

### ISSUE THREAD

**Issue by igoralves1** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#868]
**Describe the bug**
Getting the following error when building

**To Reproduce**
1. On Cloned repository
2. Installed required libraries for Ubuntu 22 and cd to build. The cmake version is `3.22.1`
3. Built following instructions: `amazon-kinesis-video-streams-producer-sdk-cpp/build$ cmake .. -DBUILD_GSTREAMER_PLUGIN=ON -DBUILD_JNI=TRUE`
4. Got following output/error:
```
$ ../amazon-kinesis-video-streams-producer-sdk-cpp/build$ cmake .. -DBUILD_GSTREAMER_PLUGIN=ON -DBUILD_JNI=TRUE

-- The CXX compiler identification is GNU 11.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Kinesis Video Cpp Producer path is /home/ila/Documents/vhosts/amazon-kinesis-video-streams-producer-sdk-cpp
-- dependencies install path is /home/ila/Documents/vhosts/amazon-kinesis-video-streams-producer-sdk-cpp/open-source
-- Begin building dependencies.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ila/Documents/vhosts/amazon-kinesis-video-streams-producer-sdk-cpp/open-source/libautoconf
[ 11%] Creating directories for 'project_libautoconf'
[ 22%] Performing download step (download, verify and extract) for 'project_libautoconf'
-- Downloading...
   dst='/home/ila/Documents/vhosts/amazon-kinesis-video-streams-producer-sdk-cpp/open-source/libautoconf/build/src/autoconf-2.69.tar.gz'
   timeout='none'
   inactivity timeout='none'
-- Using src='http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz'
-- [download 0% complete]
...
...
gmake: *** [Makefile:91: all] Error 2
CMake Error at CMake/Utilities.cmake:99 (message):
  CMake step for libautoconf failed: 2
Call Stack (most recent call first):
  CMakeLists.txt:76 (build_dependency)


-- Configuring incomplete, errors occurred!
See also "/home/ila/Documents/vhosts/amazon-kinesis-video-streams-producer-sdk-cpp/build/CMakeFiles/CMakeOutput.log".
See also "/home/ila/Documents/vhosts/amazon-kinesis-video-streams-producer-sdk-cpp/build/CMakeFiles/CMakeError.log".


```

**Expected behavior**
To build the project

**Open source building**
cmake version 3.22.1
g++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Platform (please complete the following information):**
 - OS: [Ubuntu]
 - Processor: [Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz]
 - Version [22]

**Comment by niyatim23** [comment]
Hi @igoralves1,  can you please try a clean build after installing all the dependencies with `sudo apt-get install libssl-dev libcurl4-openssl-dev liblog4cplus-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-base-apps gstreamer1.0-plugins-bad gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-tools`

**Comment by niyatim23** [comment]
Closing due to no response. Feel free to reopen in case of further questions
