### ISSUE TITLE
[QUESTION] No media found error on windows 10

### ISSUE THREAD

**Issue by risho-lizhao** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#872]
Platform:
Windows 10 Pro 21H2
IP Camera: Dahua DH-IPC-HFW2221RN
Latest version of amazon-kinesis-video-streams-producer-sdk-cpp

The situation·:
I could upload the MKV file into Kinesis and watch the video from the console by using the following command:
`kvs_gstreamer_sample.exe my-test-stream <path/to/file.mkv>`

And when I use the following command, I can also see the video taken from the IP camera.
`gst-launch-1.0.exe rtspsrc location=rtsp://<username>:<password>@<IPaddress>:<port> ! rtph264depay ! queue ! h264parse ! decodebin ! videoconvert ! autovideosink`

However, when I run the following command to send the video from the IP camera to Kinesis, an error occurs.
`gst-launch-1.0 rtspsrc location=rtsp://<username>:<password>@<IPaddress>:<port> short-header=TRUE ! rtph264depay ! video/x-h264, format=avc, alignment=au ! h264parse ! kvssink stream-name=my-test-rtsp-stream storage-size=512 access-key=@myAccessKey secret-key=@mySecretKey aws-region=ap-northeast-1`

On the console Video Preview pane, it prompts the following error message:
`No media found Verify that you are streaming to ap-northeast-1 and the fragment timecodes are correct, or download the Kinesis Video Streams Producer SDK to set up your device.`

Here is the Debug log:
[debug_20220622.log](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/files/8953759/debug_20220622.log)

Do anyone have ideas about this error?
Thank you!

**Comment by disa6302** [comment]
Instead of using gst-launch command, can you try running this sample: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/v3.3.1/samples/kvs_gstreamer_sample.cpp

With your RTSP URL as an argument to it? Make sure you set the appropriate region as well while running this.

**Comment by risho-lizhao** [comment]
@disa6302 

Thank you for your reply. Sorry for I am a beginner, so I have two basic questions to confirm.

1. How should I set RTSP URL and Region in the sample?
2. How should I run the sample?

**Comment by disa6302** [comment]
@risho-lizhao , 

Export `AWS_DEFAULT_REGION=<region>`. You can run https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/samples/kvs_gstreamer_sample.cpp by passing rtsp URL in the command line. 

So `./kvs_gstreamer_sample <stream-name> <rtsp-url>`

**Comment by disa6302** [comment]
Closing assuming answered
