### ISSUE TITLE
[QUESTION] Any guides for GSteamer cross compilation?

### ISSUE THREAD

**Issue by ensean** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#874]
As from the README it says that
> Please note that GStreamer is not cross-compiled as a part of the cross-compilation of the KVS-SDK, customers will have to cross-compile it separately.

Do we have some kind of guide for cross compiling GSteamer? Thanks a lot.

**Comment by jdelapla** [comment]
We do not. We provide samples using Gstreamer as a way to capture video data but ultimately our SDK's mission is to upload video data regardless of the source.
