### ISSUE TITLE
Issue with AWS region

### ISSUE THREAD

**Issue by bvasan** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#9]
Hi,
I pulled the latest update and tested the AWS region related fix (Issue #7). 
DEBUG - Awaiting for the stream to become ready...
WARN - HTTP Error 403: Response: {"message":"The security token included in the request is invalid."}
Request URL: https://kinesisvideo.us-west-2.amazonaws.com/describeStream_

The API URI still contains us-west-2. I think the following code in DefaultCallbackProvider.cpp is the root cause. 
    951     if (control_plane_uri_.empty()) {
    952         // Create a fully qualified URI
    953         control_plane_uri_ = CONTROL_PLANE_URI_PREFIX
    954                              + KINESIS_VIDEO_SERVICE_NAME
    955                              + "."
    956                              + DEFAULT_AWS_REGION
    957                              + CONTROL_PLANE_URI_POSTFIX;
    
I replaced the variable DEFAULT_AWS_REGION with the variable region and tested it locally. The app is now picking up the correct API URI.  

This may not be the right fix. The relationship between the variables "region" and "control_plane_uri" must be analyzed in detail to identify the appropriate fix.  

Thanks
Babu Srinivasan

**Comment by MushMal** [comment]
Indeed, there was an issue of the remnant DEFAULT region making into the constructor. The latest checkin has the fix for it. Thanks a lot for pointing out - our tests were region scoped. We had expanded to other regions too.
