### ISSUE TITLE
[QUESTION] How to run gst-device-monitor-1.0 without a pulse server

### ISSUE THREAD

**Issue by Texas-Tim** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#902]
I successfully completed the demo and sent video (not sure about audio) to my example stream, but probing for devices using gst-device-monitor-1.0 doesn't work. This issue closely aligns with https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/667 who solved it by disabling the pulse server check

** Logging **
Running GST_DEBUG=2 gst-device-monitor-1.0 I get

Probing devices...

0:00:00.002864000 99093 0x7fdced309190 WARN           devicemonitor gstdevicemonitor.c:517:gst_device_monitor_start:<devicemonitor0> No filters have been set, will expose all devices found
0:00:00.002888000 99093 0x7fdced309190 WARN           devicemonitor gstdevicemonitor.c:523:gst_device_monitor_start:<devicemonitor0> No providers match the current filters
Failed to start device monitor!

However, his last step of compiling gst-plugins-good with `-Dpulse=disabled` I'm unsure how to do

**Comment by hassanctech** [comment]
This is a question is more appropriate for the GStreamer forums and does not seem related to `kvssink`. I see from the issue you linked it's related to the compilation of `gst-plugins-good` I have build this before but with automake not with CMake, I suspect if you ask on the GStreamer forums they can point you to how to build it with pulse disabled.
