### ISSUE TITLE
RTSP Stream: Not able to add audio on AWS kinesis-video-streams

### ISSUE THREAD

**Issue by Darktechie-programmer** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#903]
Hi,

I have used the following command for streaming..

gst-launch-1.0 -v rtspsrc location="rtsp://192.168.68.114:5554/playlist.m3u" short-header=TRUE ! rtph264depay ! h264parse ! kvssink access-key=<Access-key> secret-key=<secret-key> stream-name="ExampleStream" storage-size=512 

And my streaming is successfully displayed on the AWS kinesis-video-streams but i want to listen my audio too. but noting work for me, For audio purpose i have used this command

gst-launch-1.0 -v rtspsrc location="rtsp://192.168.68.114:5554/playlist.m3u" short-header=TRUE ! rtph264depay ! h264parse ! kvssink access-key=<Access-key> secret-key=<secret-key> stream-name="ExampleStream" storage-size=512 alsasrc device=hw:1,0 ! audioconvert ! avenc_aac ! queue ! sink.

can enyone help so i can stream my audio and video. 

![image (1)](https://user-images.githubusercontent.com/52384184/189661140-1cf55d80-69a0-4481-b07b-4322d720e97f.png)
![image](https://user-images.githubusercontent.com/52384184/189661181-866e2766-ae37-4968-8047-b8d06a4a09be.png)

**Comment by hassanctech** [comment]
If you're receiving audio and video from RTSP you will need to split the pipeline and have depayer for h264 as well as for the audio (for example: https://gstreamer.freedesktop.org/documentation/rtp/rtpac3depay.html?gi-language=c), then you need to mux these together to a single stream and then send to kvssink.

Here's and example from someone else who tried to do this, if you follow this it should work for you!  If it does not please re-open: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/issues/687#issuecomment-807859411

**Comment by Darktechie-programmer** [comment]
Hi,

i have check all the solution but nothing worked for me, 

Live RTSP link:   rtsp://spicatv.dvrdns.org:555/Al_Ekhbariya_Stream

# Working without audio   # video live working
gst-launch-1.0 -v rtspsrc location="rtsp://spicatv.dvrdns.org:555/Al_Ekhbariya_Stream" short-header=TRUE ! rtph264depay ! h264parse ! kvssink access-key=<access-key> secret-key=<secret-key> stream-name="ExampleStream" storage-size=512 


----- For audio purose used commands:

# First command for audio  # not working

gst-launch-1.0 rtspsrc name=src location="rtsp://spicatv.dvrdns.org:555/Al_Ekhbariya_Stream" short-header=true ! rtph264depay ! h264parse ! kvssink name=sink access-key=<access-key> secret-key=<secret-key> stream-name="ExampleStream" storage-size=1024 aws-region="us-east-2" frame-timecodes=false src. ! rtppcmadepay ! alawdec ! audioresample ! audioconvert ! voaacenc ! aacparse ! queue ! sink.

![first_command](https://user-images.githubusercontent.com/52384184/189879695-32546756-fd78-467a-bbb3-661457288cea.png)
![first_command_part_2](https://user-images.githubusercontent.com/52384184/189879811-a113049a-31a9-4c43-8f0f-5e5ce0ea2445.png)


# Second command for audio  # not working

gst-launch-1.0 rtspsrc name=src location="rtsp://spicatv.dvrdns.org:555/Al_Ekhbariya_Stream" short-header=true ! rtph264depay ! h264parse ! kvssink name=sink access-key=<access-key> secret-key=<secret-key> stream-name="ExampleStream" storage-size=1024 aws-region="us-east-2" frame-timecodes=false src. ! rtpmpadepay ! mpg123audiodec ! audioresample ! audioconvert ! voaacenc ! aacparse ! queue ! sink.

![second_command](https://user-images.githubusercontent.com/52384184/189880193-603bfa4e-943e-4737-8025-a7eb6bfce060.png)
![second_command_part_2](https://user-images.githubusercontent.com/52384184/189880907-54742dd1-2e9c-467e-95d0-d393065e130f.png)


# third command for audio  # not working

gst-launch-1.0 rtspsrc name=src location="rtsp://spicatv.dvrdns.org:555/Al_Ekhbariya_Stream" short-header=true ! rtph264depay ! h264parse ! kvssink name=sink access-key=<access-key> secret-key=<secret-key> stream-name="ExampleStream" storage-size=1024 aws-region="us-east-2" frame-timecodes=false src. ! rtpaacdepay ! queue ! sink.

![Screenshot from 2022-09-13 15-56-54](https://user-images.githubusercontent.com/52384184/189881179-f8715a5a-90cb-42c3-a077-f9e2549624c0.png)

**Comment by Darktechie-programmer** [comment]
Hi, 

Video:
  Codec: h264
  Resolution: 852 X 480
  Bitrate: 1083 kbps VBR

Audio:
  Codec: aac stereo
  Sample rate: 48000
  Bitrate: 67 kbps VBR

I have using these configuration for my rtsp but my audio is not coming on aws kinesis-video-stream. I don't know much about gst-launch-1.0 library, can you please share with me complete command. 

Thanks

**Comment by javieralcantara** [comment]
Having the same issue here. Did anyone solve it?

**Comment by jdelapla** [comment]
Hello, this is a pure gstreamer issue unrelated to the internals of kvssink. Your pads aren't connecting between your rtspsrc and rtpPCMAdepay elements.

Please add a `queue` element between your src and rtpXXXXdepay(s) when doing a tee like this.

`gst-launch-1.0 rtspsrc name=src location="rtsp://192.168.68.114:5554/playlist.m3u" short-header=true ! queue ! rtph264depay ! h264parse ! kvssink name=sink access-key="access-key" secret-key="secret-key" stream-name="ExampleStream" storage-size=1024 aws-region="us-east-2" frame-timecodes=false src. ! queue ! rtppcmadepay ! alawdec ! audioresample ! audioconvert ! voaacenc ! aacparse ! queue ! sink.`

Something like that should work.
Very similar to this issue someone had with a/v pipelines.
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1014
