### ISSUE TITLE
[QUESTION] Offline upload of file, throttle bandwidth

### ISSUE THREAD

**Issue by clogwog** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#911]
Is it possible to upload a file with kvssink streaming-type=offline but limit how fast it tries to upload it ?

I'm uploading a 1 minute mp4 file to kinesis video using :

`gst-launch-1.0 filesrc location=/data/myvideo.mp4 ! qtdemux name=demux demux.video_0 !  h264parse config-interval=-1  ! video/x-h264,stream-format=avc,alignment=au ! kvs.video_0  kvssink name=kvs streaming-type=offline file-start-time=xxxxxx storage-size=512 iot-certificate="......" iot-thing-name="mydevice" stream-name="mystream"`

but it looks like it is eating so much of my bandwidth that nothing else is happening on the network untill the upload finishes (after about 25 seconds) Is there a way to use say 50% of the available bandwidth so the full quality upload will still happen, but a bit slower?

[avg-bandwidth-bps](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/src/gstreamer/gstkvssink.cpp#L508) looks like it can be set, but i can't find the documentation for it except:

Parameter | Description | Unit/ Type | Default
-- | -- | -- | --
avg-bandwidth-bps | The expected average bandwidth for the stream. | Bytes per second | 4194304

what would it do when i set it to something else ? does it still use the full bandwidth if there is more ?

**Comment by MushMal** [comment]
The library doesn't have any provisions currently. You can modify https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/a8091d1a140fbdcb260ba3c8302aa2e4712d2d91/src/source/Response.c#L147 to add CURLOPT_MAX_SEND_SPEED_LARGE to the options 

https://curl.se/libcurl/c/[CURLOPT_MAX_SEND_SPEED_LARGE](https://curl.se/libcurl/c/CURLOPT_MAX_SEND_SPEED_LARGE.html).html

**Comment by clogwog** [comment]
@MushMal thank you, that is very interesting, i'm trying to find a path from kvssink all the way into the depths of the videostreams producer library so it can be passed in. lost my way around createStreamCurl

**Comment by MushMal** [comment]
The higher-level logic creates an API callback provider based on CURL with a call to createCurlApiCallbacks. This sets the actual callbacks in https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/a8091d1a140fbdcb260ba3c8302aa2e4712d2d91/src/source/CurlApiCallbacks.c#L58-L65 which would then be called by the state automata.

The one for streaming is called putStreamCurl which is defined here: https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/a8091d1a140fbdcb260ba3c8302aa2e4712d2d91/src/source/CurlApiCallbacks.c#L1993

It spins up a handler thread that services the streaming itself in https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/a8091d1a140fbdcb260ba3c8302aa2e4712d2d91/src/source/CurlApiCallbacks.c#L2105

A proper solution might be to add plumbing for rate limitation from KVS sink all the way to StreamInfo.StreamCaps, rev the structure for back compat and handle it properly in the CURL callback provider.

For your case though, to avoid all the churn, I would simply recommend calling curl_easy_setopt with CURLOPT_MAX_SENDSPEED_LARGE in the putStreamCurl somewhere here: https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/a8091d1a140fbdcb260ba3c8302aa2e4712d2d91/src/source/CurlApiCallbacks.c#L2044

**Comment by clogwog** [comment]
@MushMal thank you for that. I guess the complexity is the exact reason why this hasn't been done already. Even if i implement the MAX_SENDSPEED_LARGE i would still need to know the total bandwidth and take a percentage of that, set it during the upload and hope the bandwidth doesn't change (we are on 4G so we can't assume this).

I may have a look at traffic shaping instead. 
Thank you for your solution though, it may be a good fallback.

**Comment by MushMal** [comment]
@clogwog I would encourage cutting an issue with a feature to get this implemented. Of course, I would recommend thinking about what other parameters would be interesting to be passed in. Honestly, while this is a little bit of a churn but it's rather a straightforward task to add and I can also help.
