### ISSUE TITLE
[BUG] Firewall error when publishing to KVS with GStreamer. Ports are already open.

### ISSUE THREAD

**Issue by shawn-ev** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#920]
I was referred here by AWS support. I'm hoping someone can help me out.

I have an EC2 running GStreamer trying to send an IP camera stream to KVS. The camera is an Axis P1448-LE. I keep getting this same error when trying to stream. I get his error when trying to stream directly from the camera and when trying to steam from the small camera server on-prem. I can do an rtsp stream to VLC without issue. Additionally, I can push public rtsp streams to KVS without issue. This error is only happening with my camera and server. The error points to the firewall, but I already have 80 and 554 open. I suspect it's a port issue. Are additional ports required?

The error I keep getting is:
```
[WARNING: from element /GstPipeline:pipeline0/GstRTSPSrc:rtspsrc0: Could not read from resource.
Additional debug info:
../gst/rtsp/gstrtspsrc.c(5964): gst_rtspsrc_reconnect (): /GstPipeline:pipeline0/GstRTSPSrc:rtspsrc0:
Could not receive any UDP packets for 5.0000 seconds, maybe your firewall is blocking it. Retrying using a tcp connection.]
```

Here is my ‘sanitized’ gst command. This command works in VLC from every server I've tried. Notice the rtsp link uses port 554.

`gst-launch-1.0 rtspsrc location="rtsp://<username>:<passwd>@<ip_addy>:554/axis-media/media.amp" short-header=TRUE ! rtph264depay ! video/x-h264, format=avc,alignment=au ! kvssink stream-name="my_test_kvs" storage-size=512 access-key="<my_access_key>" secret-key="<my_secret_key>" aws-region="us-east-1"`

Thank you for your time and assistance!

**Comment by disa6302** [comment]
@shawn-ev , 
1. Make sure your RTSP URL is correct and the port is correct.
2. The default ports seem correct, but I suspect your camera is using some other port. 
3. If you are on VPN by any chance, disable it.
