### ISSUE TITLE
[BUG] connection to the stream is failing

### ISSUE THREAD

**Issue by nesvieraquetocos** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#923]
I think the error suggests that the connection to the stream is failing.  I don't think it's the URL because I can see it in VLC

root@DESKTOP-0F1BQDH:~/amazon-kinesis-video-streams-producer-sdk-cpp/build# ./kvs_gstreamer_sample kvs rtsp://xxxxx:xxxxxxxxx@192.168.1.182:554/H264/ch1/main/av_stream
[INFO ] [06-11-2022 04:10:45:766.836 GMT] Using region: us-east-1
[INFO ] [06-11-2022 04:10:45:766.973 GMT] Using aws credentials for Kinesis Video Streams
[INFO ] [06-11-2022 04:10:45:767.060 GMT] Session token detected.
[INFO ] [06-11-2022 04:10:45:768.506 GMT] createKinesisVideoClient(): Creating Kinesis Video Client
[INFO ] [06-11-2022 04:10:45:768.630 GMT] heapInitialize(): Initializing native heap with limit size 134217728, spill ratio 0% and flags 0x00000001
[INFO ] [06-11-2022 04:10:45:768.700 GMT] heapInitialize(): Creating AIV heap.
[INFO ] [06-11-2022 04:10:45:768.782 GMT] heapInitialize(): Heap is initialized OK
[DEBUG] [06-11-2022 04:10:45:769.127 GMT] getSecurityTokenHandler invoked
[DEBUG] [06-11-2022 04:10:45:769.230 GMT] Refreshing credentials. Force refreshing: 0 Now time is: 1667707845769208300 Expiration: 0
[INFO ] [06-11-2022 04:10:45:769.305 GMT] New credentials expiration is 1667711445
[INFO ] [06-11-2022 04:10:45:769.409 GMT] createDeviceResultEvent(): Create device result event.
[DEBUG] [06-11-2022 04:10:45:769.485 GMT] clientReadyHandler invoked
[DEBUG] [06-11-2022 04:10:45:769.528 GMT] Client is ready
[INFO ] [06-11-2022 04:10:45:769.651 GMT] Creating Kinesis Video Stream kvs
[INFO ] [06-11-2022 04:10:45:769.737 GMT] createKinesisVideoStream(): Creating Kinesis Video Stream.
[INFO ] [06-11-2022 04:10:45:769.802 GMT] logStreamInfo(): SDK version: 70f74f14cf27b09f71dc1889f36eb6e04cdd90a8
[DEBUG] [06-11-2022 04:10:45:769.863 GMT] logStreamInfo(): Kinesis Video Stream Info
[DEBUG] [06-11-2022 04:10:45:769.919 GMT] logStreamInfo():      Stream name: kvs
[DEBUG] [06-11-2022 04:10:45:769.938 GMT] logStreamInfo():      Streaming type: STREAMING_TYPE_REALTIME
[DEBUG] [06-11-2022 04:10:45:769.962 GMT] logStreamInfo():      Content type: video/h264
[DEBUG] [06-11-2022 04:10:45:770.020 GMT] logStreamInfo():      Max latency (100ns): 600000000
[DEBUG] [06-11-2022 04:10:45:770.080 GMT] logStreamInfo():      Fragment duration (100ns): 20000000
[DEBUG] [06-11-2022 04:10:45:770.099 GMT] logStreamInfo():      Key frame fragmentation: Yes
[DEBUG] [06-11-2022 04:10:45:770.158 GMT] logStreamInfo():      Use frame timecode: Yes
[DEBUG] [06-11-2022 04:10:45:770.218 GMT] logStreamInfo():      Absolute frame timecode: Yes
[DEBUG] [06-11-2022 04:10:45:770.237 GMT] logStreamInfo():      Nal adaptation flags: 0
[DEBUG] [06-11-2022 04:10:45:770.295 GMT] logStreamInfo():      Average bandwith (bps): 4194304
[DEBUG] [06-11-2022 04:10:45:770.330 GMT] logStreamInfo():      Framerate: 25
[DEBUG] [06-11-2022 04:10:45:770.392 GMT] logStreamInfo():      Buffer duration (100ns): 1200000000
[DEBUG] [06-11-2022 04:10:45:770.461 GMT] logStreamInfo():      Replay duration (100ns): 400000000
[DEBUG] [06-11-2022 04:10:45:770.527 GMT] logStreamInfo():      Connection Staleness duration (100ns): 600000000
[DEBUG] [06-11-2022 04:10:45:770.597 GMT] logStreamInfo():      Store Pressure Policy: 1
[DEBUG] [06-11-2022 04:10:45:770.658 GMT] logStreamInfo():      View Overflow Policy: 1
[DEBUG] [06-11-2022 04:10:45:770.681 GMT] logStreamInfo():      Segment UUID: NULL
[DEBUG] [06-11-2022 04:10:45:770.748 GMT] logStreamInfo():      Frame ordering mode: 0
[DEBUG] [06-11-2022 04:10:45:770.809 GMT] logStreamInfo(): Track list
[DEBUG] [06-11-2022 04:10:45:770.875 GMT] logStreamInfo():      Track id: 1
[DEBUG] [06-11-2022 04:10:45:770.941 GMT] logStreamInfo():      Track name: kinesis_video
[DEBUG] [06-11-2022 04:10:45:771.004 GMT] logStreamInfo():      Codec id: V_MPEG4/ISO/AVC
[DEBUG] [06-11-2022 04:10:45:771.023 GMT] logStreamInfo():      Track type: TRACK_INFO_TYPE_VIDEO
[DEBUG] [06-11-2022 04:10:45:771.042 GMT] logStreamInfo():      Track cpd: NULL
[INFO ] [06-11-2022 04:10:46:410.161 GMT] writeHeaderCallback(): RequestId: 4927c705-17a1-4c37-95e4-d50f3aa401c0
[DEBUG] [06-11-2022 04:10:46:410.472 GMT] describeStreamCurlHandler(): DescribeStream API response: {"StreamInfo":{"CreationTime":1.667704787651E9,"DataRetentionInHours":1,"DeviceName":null,"IngestionChannelARN":null,"IngestionConfiguration":null,"KmsKeyId":"arn:aws:kms:us-east-1:612466452149:alias/aws/kinesisvideo","MediaType":null,"Status":"ACTIVE","StreamARN":"arn:aws:kinesisvideo:us-east-1:612466452149:stream/kvs/1667704787651","StreamName":"kvs","Version":"JQdZnmxJMApKc4PSyLrS"}}
[INFO ] [06-11-2022 04:10:46:412.494 GMT] describeStreamResultEvent(): Describe stream result event.
[WARN ] [06-11-2022 04:11:26:312.896 GMT] describeStreamResult(): Retention period returned from the DescribeStream call doesn't match the one specified in the StreamInfo
[WARN ] [06-11-2022 04:11:26:313.116 GMT] describeStreamResult(): Content type returned from the DescribeStream call doesn't match the one specified in the StreamInfo
[INFO ] [06-11-2022 04:11:27:004.478 GMT] writeHeaderCallback(): RequestId: ee0dab19-1a19-4c96-8cfa-32a94a41b606
[DEBUG] [06-11-2022 04:11:27:004.767 GMT] getStreamingEndpointCurlHandler(): GetStreamingEndpoint API response: {"DataEndpoint":"[https://s-468461da.kinesisvideo.us-east-1.amazonaws.com ](https://s-468461da.kinesisvideo.us-east-1.amazonaws.com/)"}
[INFO ] [06-11-2022 04:11:27:006.614 GMT] getStreamingEndpointResultEvent(): Get streaming endpoint result event.
[DEBUG] [06-11-2022 04:11:27:006.821 GMT] getStreamingTokenHandler invoked
[DEBUG] [06-11-2022 04:11:27:006.971 GMT] Refreshing credentials. Force refreshing: 1 Now time is: 1667707887006958900 Expiration: 1667711485
[INFO ] [06-11-2022 04:11:27:007.093 GMT] New credentials expiration is 1667711487
[INFO ] [06-11-2022 04:11:27:007.249 GMT] getStreamingTokenResultEvent(): Get streaming token result event.
[DEBUG] [06-11-2022 04:11:27:007.533 GMT] streamReadyHandler invoked
[DEBUG] [06-11-2022 04:11:27:008.039 GMT] Stream is ready
[INFO ] [06-11-2022 04:11:27:032.644 GMT] Streaming from rtsp source
Error received from element source: Could not open resource for reading and writing.
Debugging information: gstrtspsrc.c(7469): gst_rtspsrc_retrieve_sdp (): /GstPipeline:rtsp-kinesis-pipeline/GstRTSPSrc:source:
Failed to connect. (Generic error)
[INFO ] [06-11-2022 04:11:47:068.845 GMT] stopKinesisVideoStreamSync(): Synchronously stopping Kinesis Video Stream 000055619193db30.
[DEBUG] [06-11-2022 04:11:47:069.089 GMT] streamClosedHandler invoked for upload handle: 18446744073709551615
[INFO ] [06-11-2022 04:11:47:069.262 GMT] Freeing Kinesis Video Stream kvs
[INFO ] [06-11-2022 04:11:47:069.465 GMT] freeKinesisVideoStream(): Freeing Kinesis Video stream.
[DEBUG] [06-11-2022 04:11:47:069.600 GMT] curlApiCallbacksShutdownActiveRequests(): pActiveRequests hashtable is empty
[INFO ] [06-11-2022 04:11:47:470.386 GMT] Freeing Kinesis Video Stream kvs
[INFO ] [06-11-2022 04:11:47:470.657 GMT] freeKinesisVideoClient(): Freeing Kinesis Video Client
[DEBUG] [06-11-2022 04:11:47:470.730 GMT] curlApiCallbacksShutdownActiveRequests(): pActiveRequests hashtable is empty
[DEBUG] [06-11-2022 04:11:47:871.751 GMT] freeKinesisVideoClientInternal(): Total allocated memory 0
[WARN ] [06-11-2022 04:11:47:872.008 GMT] curlApiCallbacksShutdown(): curlApiCallbacksShutdown called when already in progress of shutting down

**Comment by disa6302** [comment]
@nesvieraquetocos , 

This is not KVS specific. The error indicates that the camera connection could not be established to start with. A few ideas to debug this:
1. Check if you are behind VPN. 
2. Trying it out on VLC is ok, and given it works on that, you might have to look at the flags gstreamer rtspsrc provides to see if you might have to customize your pipeline for the camera you are using. I would suggest starting with gst-launch command and using other sinks (fakesink) for example to ensure the gstreamer pipeline is set appropriately to accept the RTSP source before connecting to the sink.

Closing since this is source specific. Feel free to reopen if you are able to connect to source using gstreamer and are still unable to stream using KVS.
