### ISSUE TITLE
[QUESTION] Regarding Multiple USB camera streams over aws kinesis video stream

### ISSUE THREAD

**Issue by sundaravinayagam** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#924]
Hello Team,

I would like to send  2 usb camera streams to aws kinesis video stream with different stream names.

For example ,

Camera 1(/dev/video0)  to Camera1_Stream
Camera2( /dev/video2) to Camera2_stream name.

Could you please suggest which application will be suitable and also clarify the steps to stream two USB cameras at the same time.

Please help to suggest this on priority.

Thanks,
Sun

**Comment by niyatim23** [comment]
You can create two streams and create two GStreamer pipelines similar to the [sample](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/f68a50697436e8d1285ef297d5817b112841cb73/samples/kvs_gstreamer_audio_video_sample.cpp) here to send media to kvs using the kvssink plugin.

Closing assuming answered. Feel free to reach out with further questions
