### ISSUE TITLE
RTSP Streaming error [QUESTION]

### ISSUE THREAD

**Issue by S0UL4** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#928]
Hello guys,

when i try to stream with kvs_gstreamer_sample through RTSP url (rtsp://192.168.1.134:8554/mystream) i got this error below:

![Screenshot from 2022-12-13 14-03-02](https://user-images.githubusercontent.com/62818840/207328254-2b311a8e-4ae0-4b7c-b6e5-637b6b355ff3.png)

Pad link failed
Error received from element udpsrc0: Internal data stream error.
Debugging information: gstbasesrc.c(3072): gst_base_src_loop (): /GstPipeline:rtsp-kinesis-pipeline/GstRTSPSrc:source/GstUDPSrc:udpsrc0:
streaming stopped, reason not-linked (-1)

Any idea please?

**Comment by S0UL4** [comment]
The problem comes from UDP Buffer i think !
![Screenshot from 2022-12-13 14-42-41](https://user-images.githubusercontent.com/62818840/207341124-542718d3-9dd9-4092-b8e8-ce223ae9339d.png)

Should i increase the UDP BUFFER SIZE ?

**Comment by ryanfogarty** [comment]
I get the same error when streaming from file source but not live source. Increasing buffer size did not resolve for me however.

**Comment by disa6302** [comment]
@S0UL4 , 

What version of gstreamer does your system have? Can you share the OS version details as well?

**Comment by disa6302** [comment]
Resolving due to no response. A few pointers:

1. Test your pipeline using gst-launch-1.0 with fakesink to make sure your source piece of the pipeline works. 
2. If you have VPN enabled, disable it. I have seen RTSP linking errors occur when using VPN.
