### ISSUE TITLE
[QUESTION] Video continuously pauses when streaming from deepstream python app

### ISSUE THREAD

**Issue by razekmaiden** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#942]
Hello everyone. I'm trying to stream video to kinesis from an application using Nvidia Deepstream (based on Gstreamer) on a Jetson Xavier AGX. This application currently reads a video, processes it (inference) and at the end of the pipeline there is kvssink that performs the transmission.

![pipeline](https://user-images.githubusercontent.com/7081707/216429723-38658935-1d65-4cbb-8ac9-48fd6296521d.png)

I've tried setting the iframeinterval parameters of nvv4l2h264enc, along with the fragment-duration and framerate parameters of kvssink. However, when viewing the video in the AWS player, it continually pauses, apparently waiting for the arrival of new fragments ([Video](https://www.youtube.com/watch?v=szFAqRPeXGg)).

I am not an expert in Gstreamer although little by little I have managed to learn. Until now I have mainly tried to vary the aforementioned parameters, without having better results.

I appreciate your time. Regards!!

**Logging**
Add relevent SDK logging.  IMPORTANT NOTE:  Please make sure to NOT share AWS access credentials under any circumstance!  Please make sure they are not in the logs.

> [INFO ] [02-02-2023 19:11:09:663.780 GMT] createKinesisVideoClient(): Creating Kinesis Video Client
> [INFO ] [02-02-2023 19:11:09:663.995 GMT] heapInitialize(): Initializing native heap with limit size 536870912, spill ratio 0% and flags 0x00000001
> [INFO ] [02-02-2023 19:11:09:664.032 GMT] heapInitialize(): Creating AIV heap.
> [INFO ] [02-02-2023 19:11:09:664.119 GMT] heapInitialize(): Heap is initialized OK
> [DEBUG] [02-02-2023 19:11:09:664.876 GMT] getSecurityTokenHandler invoked
> [DEBUG] [02-02-2023 19:11:09:664.959 GMT] Refreshing credentials. Force refreshing: 0 Now time is: 1675365069664951113 Expiration: 0
> [INFO ] [02-02-2023 19:11:09:665.005 GMT] createDeviceResultEvent(): Create device result event.
> [DEBUG] [02-02-2023 19:11:09:665.043 GMT] clientReadyHandler invoked
> [INFO ] [02-02-2023 19:11:09:665.209 GMT] try creating stream
> [INFO ] [02-02-2023 19:11:09:665.273 GMT] Creating Kinesis Video Stream RLBokqksQo7p1g3yujU0_FsJPrfvuGifvcpaHovkw_2
> [INFO ] [02-02-2023 19:11:09:665.309 GMT] createKinesisVideoStream(): Creating Kinesis Video Stream.
> [INFO ] [02-02-2023 19:11:09:665.340 GMT] logStreamInfo(): SDK version: 70f74f14cf27b09f71dc1889f36eb6e04cdd90a8
> [DEBUG] [02-02-2023 19:11:09:665.367 GMT] logStreamInfo(): Kinesis Video Stream Info
> [DEBUG] [02-02-2023 19:11:09:665.393 GMT] logStreamInfo(): 	Stream name: RLBokqksQo7p1g3yujU0_FsJPrfvuGifvcpaHovkw_2 
> [DEBUG] [02-02-2023 19:11:09:665.418 GMT] logStreamInfo(): 	Streaming type: STREAMING_TYPE_REALTIME 
> [DEBUG] [02-02-2023 19:11:09:665.478 GMT] logStreamInfo(): 	Content type: video/h264 
> [DEBUG] [02-02-2023 19:11:09:665.506 GMT] logStreamInfo(): 	Max latency (100ns): 600000000
> [DEBUG] [02-02-2023 19:11:09:665.560 GMT] logStreamInfo(): 	Fragment duration (100ns): 15000000
> [DEBUG] [02-02-2023 19:11:09:665.587 GMT] logStreamInfo(): 	Key frame fragmentation: Yes
> [DEBUG] [02-02-2023 19:11:09:665.630 GMT] logStreamInfo(): 	Use frame timecode: Yes
> [DEBUG] [02-02-2023 19:11:09:665.654 GMT] logStreamInfo(): 	Absolute frame timecode: Yes
> [DEBUG] [02-02-2023 19:11:09:665.678 GMT] logStreamInfo(): 	Nal adaptation flags: 0
> [DEBUG] [02-02-2023 19:11:09:665.702 GMT] logStreamInfo(): 	Average bandwith (bps): 4194304
> [DEBUG] [02-02-2023 19:11:09:665.725 GMT] logStreamInfo(): 	Framerate: 24
> [DEBUG] [02-02-2023 19:11:09:665.750 GMT] logStreamInfo(): 	Buffer duration (100ns): 20000000
> [DEBUG] [02-02-2023 19:11:09:665.774 GMT] logStreamInfo(): 	Replay duration (100ns): 20000000
> [DEBUG] [02-02-2023 19:11:09:665.798 GMT] logStreamInfo(): 	Connection Staleness duration (100ns): 600000000
> [DEBUG] [02-02-2023 19:11:09:665.822 GMT] logStreamInfo(): 	Store Pressure Policy: 1
> [DEBUG] [02-02-2023 19:11:09:665.847 GMT] logStreamInfo(): 	View Overflow Policy: 1
> [DEBUG] [02-02-2023 19:11:09:665.873 GMT] logStreamInfo(): 	Segment UUID: NULL
> [DEBUG] [02-02-2023 19:11:09:665.901 GMT] logStreamInfo(): 	Frame ordering mode: 0
> [DEBUG] [02-02-2023 19:11:09:665.924 GMT] logStreamInfo(): Track list
> [DEBUG] [02-02-2023 19:11:09:665.971 GMT] logStreamInfo(): 	Track id: 1
> [DEBUG] [02-02-2023 19:11:09:665.996 GMT] logStreamInfo(): 	Track name: kinesis_video
> [DEBUG] [02-02-2023 19:11:09:666.035 GMT] logStreamInfo(): 	Codec id: V_MPEG4/ISO/AVC
> [DEBUG] [02-02-2023 19:11:09:666.060 GMT] logStreamInfo(): 	Track type: TRACK_INFO_TYPE_VIDEO
> [DEBUG] [02-02-2023 19:11:09:666.109 GMT] logStreamInfo(): 	Track cpd: NULL
> [INFO ] [02-02-2023 19:11:10:285.398 GMT] writeHeaderCallback(): RequestId: 8ca06d31-1f29-4cfa-9546-9c5ce4328acb
> [DEBUG] [02-02-2023 19:11:10:285.619 GMT] describeStreamCurlHandler(): DescribeStream API response: {"StreamInfo":{"CreationTime":1.675274432424E9,"DataRetentionInHours":2,"DeviceName":"Kinesis_Video_Device","IngestionConfiguration":null,"KmsKeyId":"arn:aws:kms:us-east-1:532644800621:alias/aws/kinesisvideo","MediaType":"video/h264","Status":"ACTIVE","StreamARN":"arn:aws:kinesisvideo:us-east-1:532644800621:stream/RLBokqksQo7p1g3yujU0_FsJPrfvuGifvcpaHovkw_2/1675274432424","StreamName":"RLBokqksQo7p1g3yujU0_FsJPrfvuGifvcpaHovkw_2","Version":"vkTeIiR
> [INFO ] [02-02-2023 19:11:10:287.653 GMT] describeStreamResultEvent(): Describe stream result event.
> [INFO ] [02-02-2023 19:11:10:842.739 GMT] writeHeaderCallback(): RequestId: e4f39920-d608-41ee-b1af-c90f38aaa9c6
> [DEBUG] [02-02-2023 19:11:10:842.962 GMT] getStreamingEndpointCurlHandler(): GetStreamingEndpoint API response: {"DataEndpoint":"https://s-356988f0.kinesisvideo.us-east-1.amazonaws.com"}
> [INFO ] [02-02-2023 19:11:10:845.002 GMT] getStreamingEndpointResultEvent(): Get streaming endpoint result event.
> [DEBUG] [02-02-2023 19:11:10:845.111 GMT] getStreamingTokenHandler invoked
> [DEBUG] [02-02-2023 19:11:10:845.162 GMT] Refreshing credentials. Force refreshing: 1 Now time is: 1675365070845155180 Expiration: 18446744073709551615
> [INFO ] [02-02-2023 19:11:10:845.225 GMT] getStreamingTokenResultEvent(): Get streaming token result event.
> [DEBUG] [02-02-2023 19:11:10:845.274 GMT] streamReadyHandler invoked
> Stream is ready
> Opening in BLOCKING MODE 
> gstnvtracker: Loading low-level lib at /opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
> gstnvtracker: Batch processing is ON
> gstnvtracker: Past frame output is OFF
> [NvMultiObjectTracker] Initialized
> WARNING: [TRT]: Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
> INFO: [Implicit Engine Info]: layers num: 3
> 0   INPUT  kFLOAT input_1         3x544x960       
> 1   OUTPUT kFLOAT output_bbox/BiasAdd 4x34x60         
> 2   OUTPUT kFLOAT output_cov/Sigmoid 1x34x60         
> 
> Opening in BLOCKING MODE 
> [INFO ] [02-02-2023 19:11:14:944.796 GMT] kinesisVideoStreamFormatChanged(): Stream format changed.
> [INFO ] [02-02-2023 19:11:14:945.987 GMT] putStreamResultEvent(): Put stream result event. New upload handle 0
> [DEBUG] [02-02-2023 19:11:14:956.574 GMT] Kinesis Video client and stream metrics
> 	>> Overall storage byte size: 536870912
> 	>> Available storage byte size: 536733870
> 	>> Allocated storage byte size: 137042
> 	>> Total view allocation byte size: 2384
> 	>> Total streams elementary frame rate (fps): 24
> 	>> Total streams transfer rate (bps): 33554432 (32768 Kbps)
> 	>> Current view duration (ms): 0
> 	>> Overall view duration (ms): 0
> 	>> Current view byte size: 136994
> 	>> Overall view byte size: 136994
> 	>> Current elementary frame rate (fps): 24
> 	>> Current transfer rate (bps): 33554432 (32768 Kbps)
> [INFO ] [02-02-2023 19:11:15:592.684 GMT] writeHeaderCallback(): RequestId: d1237db0-2b0b-d3b0-8d75-70a39349ced6
> [DEBUG] [02-02-2023 19:11:15:593.101 GMT] postReadCallback(): Wrote 65524 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:15:717.091 GMT] postReadCallback(): Wrote 65524 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:15:839.814 GMT] postReadCallback(): Wrote 24117 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:15:980.539 GMT] postReadCallback(): Wrote 2987 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:15:980.993 GMT] postWriteCallback(): Curl post body write function for stream with handle: RLBokqksQo7p1g3yujU0_FsJPrfvuGifvcpaHovkw_2 and upload handle: 0 returned: {"EventType":"BUFFERING","FragmentTimecode":1675365074945,"FragmentNumber":"91343852333181541331405519765100789035023748366"}
> 
> [DEBUG] [02-02-2023 19:11:15:981.216 GMT] fragmentAckReceivedHandler invoked
> [DEBUG] [02-02-2023 19:11:16:121.637 GMT] postReadCallback(): Wrote 4523 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:16:262.399 GMT] postReadCallback(): Wrote 5471 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:16:323.065 GMT] postReadCallback(): Wrote 4226 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:16:463.797 GMT] postReadCallback(): Wrote 6442 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:16:604.504 GMT] postReadCallback(): Wrote 12774 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:16:745.255 GMT] postReadCallback(): Wrote 10015 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:16:886.021 GMT] postReadCallback(): Wrote 18706 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:16:946.657 GMT] postReadCallback(): Wrote 21555 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:17:087.530 GMT] postReadCallback(): Wrote 17971 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:17:228.284 GMT] postReadCallback(): Wrote 19111 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:17:369.157 GMT] postReadCallback(): Wrote 17317 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:17:510.314 GMT] postReadCallback(): Wrote 16200 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:17:651.133 GMT] postReadCallback(): Wrote 17053 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:17:792.051 GMT] postReadCallback(): Wrote 15057 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:17:932.951 GMT] postReadCallback(): Wrote 18108 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:17:993.726 GMT] postReadCallback(): Wrote 15210 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:18:134.809 GMT] postReadCallback(): Wrote 17701 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:18:276.047 GMT] postReadCallback(): Wrote 18543 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:18:416.950 GMT] postReadCallback(): Wrote 14902 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:18:557.768 GMT] postReadCallback(): Wrote 14508 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:18:698.601 GMT] postReadCallback(): Wrote 15804 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:18:759.215 GMT] postReadCallback(): Wrote 17277 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:18:900.018 GMT] postReadCallback(): Wrote 17065 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:19:040.795 GMT] postReadCallback(): Wrote 18457 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:19:181.649 GMT] postReadCallback(): Wrote 16710 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:19:322.568 GMT] postReadCallback(): Wrote 15142 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:19:383.245 GMT] postReadCallback(): Wrote 14103 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:19:498.739 GMT] Kinesis Video client and stream metrics
> 	>> Overall storage byte size: 536870912
> 	>> Available storage byte size: 536094151
> 	>> Allocated storage byte size: 776761
> 	>> Total view allocation byte size: 2384
> 	>> Total streams elementary frame rate (fps): 24
> 	>> Total streams transfer rate (bps): 15339208 (14979 Kbps)
> 	>> Current view duration (ms): 0
> 	>> Overall view duration (ms): 1442
> 	>> Current view byte size: 216882
> 	>> Overall view byte size: 774727
> 	>> Current elementary frame rate (fps): 24.975
> 	>> Current transfer rate (bps): 15339208 (14979 Kbps)
> [DEBUG] [02-02-2023 19:11:19:523.993 GMT] postReadCallback(): Wrote 65524 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:19:524.812 GMT] postReadCallback(): Wrote 65524 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:19:525.223 GMT] postReadCallback(): Wrote 65524 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:19:647.311 GMT] postReadCallback(): Wrote 30421 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:19:788.306 GMT] postReadCallback(): Wrote 7741 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:19:788.646 GMT] postWriteCallback(): Curl post body write function for stream with handle: RLBokqksQo7p1g3yujU0_FsJPrfvuGifvcpaHovkw_2 and upload handle: 0 returned: {"EventType":"RECEIVED","FragmentTimecode":1675365074945,"FragmentNumber":"91343852333181541331405519765100789035023748366"}
> 
> [DEBUG] [02-02-2023 19:11:19:788.733 GMT] fragmentAckReceivedHandler invoked
> [DEBUG] [02-02-2023 19:11:19:929.143 GMT] postReadCallback(): Wrote 7004 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:19:929.512 GMT] postWriteCallback(): Curl post body write function for stream with handle: RLBokqksQo7p1g3yujU0_FsJPrfvuGifvcpaHovkw_2 and upload handle: 0 returned: {"EventType":"BUFFERING","FragmentTimecode":1675365076387,"FragmentNumber":"91343852333181541336357279922242311156962792167"}
> 
> [DEBUG] [02-02-2023 19:11:19:929.630 GMT] fragmentAckReceivedHandler invoked
> [DEBUG] [02-02-2023 19:11:20:070.110 GMT] postReadCallback(): Wrote 8801 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:20:070.569 GMT] postWriteCallback(): Curl post body write function for stream with handle: RLBokqksQo7p1g3yujU0_FsJPrfvuGifvcpaHovkw_2 and upload handle: 0 returned: {"EventType":"PERSISTED","FragmentTimecode":1675365074945,"FragmentNumber":"91343852333181541331405519765100789035023748366"}
> 
> [DEBUG] [02-02-2023 19:11:20:070.715 GMT] fragmentAckReceivedHandler invoked
> [DEBUG] [02-02-2023 19:11:20:131.093 GMT] postReadCallback(): Wrote 13261 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:20:272.024 GMT] postReadCallback(): Wrote 9624 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:20:412.845 GMT] postReadCallback(): Wrote 19987 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:20:553.711 GMT] postReadCallback(): Wrote 12192 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:20:614.376 GMT] postReadCallback(): Wrote 37612 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:20:755.236 GMT] postReadCallback(): Wrote 16125 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:20:895.967 GMT] postReadCallback(): Wrote 11191 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:21:036.692 GMT] postReadCallback(): Wrote 8177 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:21:177.500 GMT] postReadCallback(): Wrote 9519 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:21:318.316 GMT] postReadCallback(): Wrote 10781 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:21:378.903 GMT] postReadCallback(): Wrote 16498 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:21:519.783 GMT] postReadCallback(): Wrote 12527 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:21:660.622 GMT] postReadCallback(): Wrote 15900 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:21:801.522 GMT] postReadCallback(): Wrote 11320 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:21:942.390 GMT] postReadCallback(): Wrote 9780 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:22:003.044 GMT] postReadCallback(): Wrote 9356 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:22:143.894 GMT] postReadCallback(): Wrote 28207 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:22:285.006 GMT] postReadCallback(): Wrote 37039 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:22:425.898 GMT] postReadCallback(): Wrote 15690 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:22:566.649 GMT] postReadCallback(): Wrote 8454 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:22:707.543 GMT] postReadCallback(): Wrote 9464 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:22:768.170 GMT] postReadCallback(): Wrote 11394 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:22:908.871 GMT] postReadCallback(): Wrote 8240 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:23:049.539 GMT] postReadCallback(): Wrote 12505 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:23:190.272 GMT] postReadCallback(): Wrote 14992 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:23:330.977 GMT] postReadCallback(): Wrote 11689 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:23:391.555 GMT] postReadCallback(): Wrote 16469 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:23:532.287 GMT] postReadCallback(): Wrote 25853 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:23:673.091 GMT] postReadCallback(): Wrote 17714 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:23:813.829 GMT] postReadCallback(): Wrote 11847 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:23:954.558 GMT] postReadCallback(): Wrote 16433 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:24:014.356 GMT] Kinesis Video client and stream metrics
> 	>> Overall storage byte size: 536870912
> 	>> Available storage byte size: 535902715
> 	>> Allocated storage byte size: 968197
> 	>> Total view allocation byte size: 2384
> 	>> Total streams elementary frame rate (fps): 24
> 	>> Total streams transfer rate (bps): 6791904 (6632 Kbps)
> 	>> Current view duration (ms): 0
> 	>> Overall view duration (ms): 1441
> 	>> Current view byte size: 246042
> 	>> Overall view byte size: 966421
> 	>> Current elementary frame rate (fps): 24.975
> 	>> Current transfer rate (bps): 6791904 (6632 Kbps)
> [DEBUG] [02-02-2023 19:11:24:015.250 GMT] postReadCallback(): Wrote 65524 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:24:015.746 GMT] postReadCallback(): Wrote 65524 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:24:016.205 GMT] postReadCallback(): Wrote 65524 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:24:016.581 GMT] postReadCallback(): Wrote 49470 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:24:157.229 GMT] postReadCallback(): Wrote 12439 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:24:157.677 GMT] postWriteCallback(): Curl post body write function for stream with handle: RLBokqksQo7p1g3yujU0_FsJPrfvuGifvcpaHovkw_2 and upload handle: 0 returned: {"EventType":"RECEIVED","FragmentTimecode":1675365076387,"FragmentNumber":"91343852333181541336357279922242311156962792167"}
> 
> [DEBUG] [02-02-2023 19:11:24:157.841 GMT] fragmentAckReceivedHandler invoked
> [DEBUG] [02-02-2023 19:11:24:298.305 GMT] postReadCallback(): Wrote 7819 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:24:298.699 GMT] postWriteCallback(): Curl post body write function for stream with handle: RLBokqksQo7p1g3yujU0_FsJPrfvuGifvcpaHovkw_2 and upload handle: 0 returned: {"EventType":"BUFFERING","FragmentTimecode":1675365077828,"FragmentNumber":"91343852333181541341309040079383833462330220184"}
> 
> [DEBUG] [02-02-2023 19:11:24:298.797 GMT] fragmentAckReceivedHandler invoked
> [DEBUG] [02-02-2023 19:11:24:439.210 GMT] postReadCallback(): Wrote 7702 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:24:439.666 GMT] postWriteCallback(): Curl post body write function for stream with handle: RLBokqksQo7p1g3yujU0_FsJPrfvuGifvcpaHovkw_2 and upload handle: 0 returned: {"EventType":"PERSISTED","FragmentTimecode":1675365076387,"FragmentNumber":"91343852333181541336357279922242311156962792167"}
> 
> [DEBUG] [02-02-2023 19:11:24:439.848 GMT] fragmentAckReceivedHandler invoked
> [DEBUG] [02-02-2023 19:11:24:580.252 GMT] postReadCallback(): Wrote 7543 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:24:720.965 GMT] postReadCallback(): Wrote 9873 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:24:781.532 GMT] postReadCallback(): Wrote 13079 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:24:922.215 GMT] postReadCallback(): Wrote 15045 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:25:062.935 GMT] postReadCallback(): Wrote 9949 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:25:203.641 GMT] postReadCallback(): Wrote 11106 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:25:344.349 GMT] postReadCallback(): Wrote 8205 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:25:485.053 GMT] postReadCallback(): Wrote 8066 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:25:545.636 GMT] postReadCallback(): Wrote 10450 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:25:686.403 GMT] postReadCallback(): Wrote 24145 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:25:827.223 GMT] postReadCallback(): Wrote 12500 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:25:967.957 GMT] postReadCallback(): Wrote 10623 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:26:108.833 GMT] postReadCallback(): Wrote 12390 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:26:169.439 GMT] postReadCallback(): Wrote 16570 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:26:310.263 GMT] postReadCallback(): Wrote 12425 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:26:451.266 GMT] postReadCallback(): Wrote 36367 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:26:592.265 GMT] postReadCallback(): Wrote 11466 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:26:733.345 GMT] postReadCallback(): Wrote 22019 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:26:874.154 GMT] postReadCallback(): Wrote 20531 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:26:934.777 GMT] postReadCallback(): Wrote 24563 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:27:075.643 GMT] postReadCallback(): Wrote 7799 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:27:216.598 GMT] postReadCallback(): Wrote 12723 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:27:357.380 GMT] postReadCallback(): Wrote 5854 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:27:498.167 GMT] postReadCallback(): Wrote 7676 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:27:638.895 GMT] postReadCallback(): Wrote 8773 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:27:779.731 GMT] postReadCallback(): Wrote 22553 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:27:920.479 GMT] postReadCallback(): Wrote 35652 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:27:981.131 GMT] postReadCallback(): Wrote 17213 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:28:121.869 GMT] postReadCallback(): Wrote 16264 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:28:262.676 GMT] postReadCallback(): Wrote 13621 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:28:403.395 GMT] postReadCallback(): Wrote 8709 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:28:544.099 GMT] postReadCallback(): Wrote 9605 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:28:604.841 GMT] Kinesis Video client and stream metrics
> 	>> Overall storage byte size: 536870912
> 	>> Available storage byte size: 535841654
> 	>> Allocated storage byte size: 1029258
> 	>> Total view allocation byte size: 2384
> 	>> Total streams elementary frame rate (fps): 24
> 	>> Total streams transfer rate (bps): 3464752 (3383 Kbps)
> 	>> Current view duration (ms): 0
> 	>> Overall view duration (ms): 1442
> 	>> Current view byte size: 290123
> 	>> Overall view byte size: 1027482
> 	>> Current elementary frame rate (fps): 24.975
> 	>> Current transfer rate (bps): 3464752 (3383 Kbps)
> [DEBUG] [02-02-2023 19:11:28:684.833 GMT] postReadCallback(): Wrote 65524 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:28:685.336 GMT] postReadCallback(): Wrote 65524 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:28:685.818 GMT] postReadCallback(): Wrote 65524 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:28:686.172 GMT] postReadCallback(): Wrote 65524 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:28:686.488 GMT] postReadCallback(): Wrote 28027 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:28:746.994 GMT] postReadCallback(): Wrote 12175 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:28:887.673 GMT] postReadCallback(): Wrote 9541 bytes to Kinesis Video. Upload stream handle: 0
> [DEBUG] [02-02-2023 19:11:28:888.064 GMT] postWriteCallback(): Curl post body write function for stream with handle: RLBokqksQo7p1g3yujU0_FsJPrfvuGifvcpaHovkw_2 and upload handle: 0 returned: {"EventType":"RECEIVED","FragmentTimecode":1675365077828,"FragmentNumber":"91343852333181541341309040079383833462330220184"}

**Comment by sirknightj** [comment]
Hi @razekmaiden,

I am seeing the following line in your logs:
```
WARNING: [TRT]: Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
```

Could you try running the sample application and check to see if there are any errors with the stream?

**Comment by niyatim23** [comment]
Closing due to no response. Feel free to reopen / open a new issue if the problem persists
